export const clinicalLectureTechniques: Record<string, string[]> = {
  "11|phlegm-heat retention in lung": ["Reducing or even method as specified by the course protocol.","No moxa."],
  "11|phlegm-damp retention in lung": ["Moxa is included in the course protocol only when clinically suitable."],
  "11|phlegm-fluid retention in lung": ["Even method.","Moxa is included in the course protocol only when clinically suitable."],
  "5|stagnation of qi in the chest": ["Reducing or even method as specified by the course protocol."],
  "5|heart blood stasis": ["Reducing or even method as specified by the course protocol."],
  "5|turbid phlegm stagnating in the chest": ["Reducing or even method as specified by the course protocol.","Moxa is included in the course protocol only when clinically suitable."],
  "5|cold stagnation in the chest": ["Even method.","Moxa is included in the course protocol only when clinically suitable."],
  "5|qi and yin deficiency": ["Mixed reinforcing and even methods; follow the course protocol point by point."],
  "5|spleen-kidney yang qi deficiency": ["Mixed reinforcing and even methods; follow the course protocol point by point.","Moxa is included in the course protocol only when clinically suitable."],
  "12|liver qi stagnation": ["Reducing or even method as specified by the course protocol."],
  "35|depressive psychotic pattern: binding depression of qi and phlegm": ["Even method.","Moxa is included in the course protocol only when clinically suitable."],
  "35|depressive psychotic pattern: heart-spleen deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "35|manic psychotic pattern: phlegm-fire harassing interior": ["Reducing method."],
  "35|manic psychotic pattern: exuberant fire with injury to yin": ["Even method."],
  "36|heart-gallbladder qi deficiency disturbing the mind": ["Reinforcing method."],
  "36|qi and heart blood insufficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "36|heart fire hyperactivity due to heart-kidney yin deficiency / heart-kidney disharmony / yin deficiency with effulgent fire": ["Even method."],
  "36|heart yang deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "36|heart oppressed by water and phlegm-fluid": ["Even method."],
  "36|heart obstructed by blood stasis": ["Even method.","Moxa is included in the course protocol only when clinically suitable."],
  "47|attack of internal organs: tense type": ["Reducing method."],
  "47|attack of internal organs: flaccid type": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "1|qi mass: liver qi stagnation": ["Reducing or even method as specified by the course protocol."],
  "1|qi mass: retention of food and phlegm": ["Reducing or even method as specified by the course protocol."],
  "1|blood mass: stagnation of qi and blood": ["Reducing or even method as specified by the course protocol."],
  "1|blood mass: blood stasis knotted in the interior": ["Reducing or even method as specified by the course protocol."],
  "1|blood mass: deficiency of upright qi with blood stasis": ["Even method.","Moxa is included in the course protocol only when clinically suitable."],
  "2|cold in the intestines": ["Reducing or even method as specified by the course protocol.","Moxa is included in the course protocol only when clinically suitable."],
  "2|damp-heat in the intestines": ["Reducing or even method as specified by the course protocol.","No moxa."],
  "2|food retention": ["Reducing or even method as specified by the course protocol.","Moxa is included in the course protocol only when clinically suitable."],
  "2|qi stagnation": ["Reducing or even method as specified by the course protocol."],
  "2|blood stasis": ["Reducing or even method as specified by the course protocol."],
  "2|qi deficiency with empty-cold in the abdomen": ["Reinforcing method."],
  "7|chronic interior heat": ["Reducing method."],
  "7|acute heat in febrile disease": ["Reducing method."],
  "7|cold": ["Mixed reinforcing and reducing methods; follow the course protocol point by point."],
  "7|qi deficiency": ["Reinforcing method."],
  "7|yang deficiency": ["Reinforcing method."],
  "7|blood deficiency": ["Reinforcing method."],
  "7|yin deficiency": ["Reinforcing method.","No moxa."],
  "9|upper xiao: lung heat damaging fluids": ["Even method."],
  "9|middle xiao: excessive stomach heat": ["Even method."],
  "9|lower xiao: kidney yin deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "13|cold-damp retention": ["Reducing or even method as specified by the course protocol.","Moxa is included in the course protocol only when clinically suitable."],
  "13|damp-heat retention": ["Reducing method.","No moxa."],
  "13|food retention": ["Reducing or even method as specified by the course protocol."],
  "13|spleen-stomach deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "13|kidney yang deficiency": ["Reinforcing method."],
  "14|cold-damp blocking spleen": ["Reducing method."],
  "14|damp-heat accumulation": ["Reducing method."],
  "14|spleen qi stagnation with liver blood stasis": ["Reducing method."],
  "14|spleen-kidney yang deficiency": ["Moxa is included in the course protocol only when clinically suitable."],
  "15|damp-heat dysentery": ["Reducing method."],
  "15|epidemic toxic dysentery": ["Reducing method."],
  "15|cold-damp dysentery": ["Mixed reinforcing and reducing methods; follow the course protocol point by point."],
  "15|yin deficiency dysentery": ["Reinforcing method."],
  "15|deficient cold dysentery": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "15|intermittent dysentery": ["Even method."],
  "15|food-resistant dysentery": ["Mixed reinforcing and reducing methods; follow the course protocol point by point."],
  "16|congestion of qi and phlegm": ["Reducing or even method as specified by the course protocol.","Moxa is included in the course protocol only when clinically suitable."],
  "16|depletion of fluids with accumulation of heat": ["Reinforcing method."],
  "16|accumulation of blood stasis": ["Reducing or even method as specified by the course protocol."],
  "16|deficiency of qi with devitalization of yang": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "19|cold invading stomach": ["Reducing method.","Moxa is included in the course protocol only when clinically suitable."],
  "19|food retention": ["Reducing or even method as specified by the course protocol."],
  "19|liver qi invading stomach": ["Reducing or even method as specified by the course protocol."],
  "19|stomach fire": ["Reducing or even method as specified by the course protocol."],
  "19|stomach damp-heat": ["Even method."],
  "19|stomach and liver heat": ["Reducing or even method as specified by the course protocol."],
  "19|blood stasis in stomach": ["Reducing or even method as specified by the course protocol."],
  "19|phlegm-fluids in stomach": ["Even method."],
  "19|stomach-spleen deficient cold": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "19|stomach yin deficiency": ["Reinforcing method."],
  "24|stomach cold": ["Reducing method.","Moxa is included in the course protocol only when clinically suitable."],
  "24|effulgent stomach fire": ["Reducing method."],
  "24|liver qi stagnation": ["Reducing method."],
  "24|spleen-stomach yang deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "24|stomach yin deficiency": ["Reinforcing method."],
  "44|exogenous evils invading stomach": ["Reducing method."],
  "44|food retention": ["Reducing method."],
  "44|phlegm-damp retention": ["Even method.","Moxa is included in the course protocol only when clinically suitable."],
  "44|liver qi invading stomach": ["Even method."],
  "44|spleen-stomach deficiency cold": ["Reinforcing method."],
  "44|stomach yin deficiency": ["Reinforcing method."],
  "22|liver fire blazing with phlegm-heat": ["Reducing method."],
  "22|phlegm and blood stasis": ["Reducing method."],
  "22|liver-heart yin deficiency with phlegm": ["Even method."],
  "23|exterior wind-cold": ["Reducing method."],
  "23|exterior wind-heat": ["Reducing method."],
  "23|exterior wind-damp": ["Reducing method."],
  "23|liver yang rising": ["Mixed reinforcing, reducing, and even methods; follow the course protocol point by point."],
  "23|liver fire": ["Reducing or even method as specified by the course protocol."],
  "23|liver wind": ["Reducing method."],
  "23|liver qi stagnation": ["Mixed reinforcing, reducing, and even methods; follow the course protocol point by point."],
  "23|cold stagnation in liver channel": ["Reducing or even method as specified by the course protocol.","Moxa is included in the course protocol only when clinically suitable."],
  "23|dampness": ["Mixed reinforcing, reducing, and even methods; follow the course protocol point by point."],
  "23|turbid phlegm": ["Mixed reinforcing, reducing, and even methods; follow the course protocol point by point."],
  "23|food retention": ["Reducing or even method as specified by the course protocol."],
  "23|stomach heat": ["Reducing or even method as specified by the course protocol."],
  "23|qi deficiency": ["Reinforcing method."],
  "25|liver qi stagnation": ["Reducing or even method as specified by the course protocol."],
  "25|blood stasis": ["Reducing or even method as specified by the course protocol."],
  "25|damp-heat in liver and gallbladder": ["Even method."],
  "25|liver blood deficiency": ["Mixed reinforcing and even methods; follow the course protocol point by point."],
  "25|liver yin deficiency": ["Mixed reinforcing and even methods; follow the course protocol point by point."],
  "31|extreme repletion of heat toxins": ["Reducing method."],
  "31|yin jaundice: cold-damp in middle burner": ["Even method."],
  "34|typical malaria": ["Reducing method."],
  "34|cold malaria": ["Moxa is included in the course protocol only when clinically suitable."],
  "34|taxation malaria": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "43|turbid phlegm in head / phlegm retention in middle burner": ["Mixed reinforcing, reducing, and even methods; follow the course protocol point by point."],
  "43|qi and blood deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "43|kidney essence deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "18|yang edema: wind-water invading wei qi": ["Reducing method."],
  "18|fire poison": ["Mixed reinforcing and reducing methods; follow the course protocol point by point.","No moxa."],
  "18|dampness": ["Mixed reinforcing and even methods; follow the course protocol point by point.","Moxa is included in the course protocol only when clinically suitable."],
  "18|damp-heat. yin edema: spleen yang deficiency": ["Reducing method."],
  "18|kidney yang deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "30|heat or damp-heat accumulation in bladder": ["Reducing method."],
  "30|decline of mingmen fire / kidney qi or yang insufficiency": ["Reinforcing method."],
  "30|spleen qi deficiency": ["Moxa is included in the course protocol only when clinically suitable."],
  "32|cold-damp invasion": ["Reducing or even method as specified by the course protocol."],
  "32|kidney deficiency": ["Reinforcing method."],
  "39|downward flow of damp-heat": ["Reducing method."],
  "39|heart-spleen deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "39|kidney deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "41|stone lin": ["Reducing method.","No moxa."],
  "41|sticky/cloudy lin": ["Mixed reinforcing, reducing, and even methods; follow the course protocol point by point."],
  "41|fatigue lin": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "42|liver-gallbladder fire rising": ["Reducing method."],
  "42|wind-heat invasion": ["Reducing method."],
  "42|phlegm-fire flaring upward": ["Reducing method."],
  "42|kidney essence deficiency": ["Mixed reinforcing and even methods; follow the course protocol point by point.","Moxa is included in the course protocol only when clinically suitable."],
  "42|spleen-stomach qi deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "4|epistaxis: lung heat": ["Reducing method."],
  "4|stomach heat": ["Reducing method."],
  "4|liver fire": ["Reducing method."],
  "4|liver-kidney yin deficiency": ["Even method."],
  "4|liver fire invading stomach": ["Reducing method."],
  "4|kidney yin deficiency with empty heat": ["Mixed reinforcing and even methods; follow the course protocol point by point."],
  "4|spleen failing to control blood": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "4|yin deficiency with empty heat": ["Reducing or even method as specified by the course protocol.","No moxa."],
  "4|stomach yin deficiency with empty heat": ["Mixed reinforcing and even methods; follow the course protocol point by point.","No moxa."],
  "4|stomach-spleen deficiency": ["Mixed reinforcing and even methods; follow the course protocol point by point."],
  "29|qi stagnation fever": ["Reducing method."],
  "29|blood stasis fever": ["Reducing method."],
  "29|qi deficiency fever": ["Even method."],
  "29|blood deficiency fever": ["Even method."],
  "29|yin deficiency fever": ["Even method."],
  "45|spleen yang deficiency": ["Moxa is conditional; use only for the source-specified indication and when clinically suitable."],
  "45|qi obstruction in collaterals": ["Reducing method."],
  "45|cold-fluid retention in lung": ["Reducing method."],
  "45|spleen-kidney yang deficiency": ["Mixed reinforcing and even methods; follow the course protocol point by point.","Moxa is included in the course protocol only when clinically suitable."],
  "3|heat in lungs injuring yin fluids": ["No moxa."],
  "3|damp-heat invasion": ["Reducing method.","No moxa."],
  "3|cold-damp invasion": ["Mixed reinforcing, reducing, and even methods; follow the course protocol point by point."],
  "3|stomach and spleen deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "3|spleen and heart collapse": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "3|kidney and liver deficiency": ["Reinforcing method."],
  "3|blood stasis in the channels": ["Even method."],
  "26|migratory bi/wind bi": ["Reducing method.","Moxa is included in the course protocol only when clinically suitable."],
  "26|painful bi/cold bi": ["Moxa is included in the course protocol only when clinically suitable."],
  "26|fixed bi/damp bi": ["Reducing method.","Moxa is included in the course protocol only when clinically suitable."],
  "26|heat bi": ["Reducing method."],
  "26|qi and blood deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "17|cold exterior with heat interior": ["Reducing or even method as specified by the course protocol."],
  "17|turbid phlegm in lungs": ["Reducing or even method as specified by the course protocol."],
  "17|lung qi deficiency": ["Reinforcing method.", "Moxa only when clinically suitable."],
  "17|lung yin deficiency": ["Reinforcing method.", "No moxa."],
  "38|lung yin deficiency": ["No moxa."],
  "28|liver fire blazing": ["Reduce the protocol except use even method on BL 1 and reinforce KI 6.", "No moxa."],
  "28|phlegm-fire harassing the mind": ["Reduce except reinforce CV 12 and BL 20.", "No moxa except the source-specified use at ST 45."],
  "28|heart-kidney disharmony": ["Reinforce all points except reduce HT 6."],
  "14|qi stagnation with damp obstruction": ["Reducing method."],
  "22|qi stagnation with phlegm": ["Reducing method."],
  "23|blood stasis": ["Reducing or even method as specified by the course protocol."],
  "23|blood deficiency": ["Reinforcing method."],
  "31|yang jaundice: damp-heat in middle burner with heat predominant": ["Reducing method."],
  "31|yang jaundice: damp-heat in middle burner with damp predominant": ["Reducing method."],
  "27|debilitation of mingmen fire": ["Reinforcing method."],
  "27|kidney deficiency": ["Reinforcing method."],
  "41|blood lin": ["Use reducing method for Full Blood Heat and reinforcing method for Empty Heat with Yin deficiency.", "No moxa."],
  "41|qi lin": ["Use reducing or even method for the Full type; reinforce and use moxa only when clinically suitable for the Empty type."],
};
