import type { FormulaDetail, FormulaIngredient, LungConditionDetail, LungPatternDetail } from "./lungContent";

const h = (chineseName: string, pinyin: string, dose: string): FormulaIngredient => ({ chineseName, pinyin, englishName: "", dose });
const f = (chineseName: string, pinyin: string, actions: string[], ingredients: FormulaIngredient[]): FormulaDetail => ({
  chineseName, pinyin, actions, indications: actions.join("; "), ingredients,
});

const formulas = {
  chaiHuShuGanSan: f("柴胡疏肝散", "Chai Hu Shu Gan San", ["Spreads Liver Qi", "Relieves constraint"], [h("陈皮", "Chen Pi", "6 g"), h("柴胡", "Chai Hu", "6 g"), h("川芎", "Chuan Xiong", "4.5 g"), h("枳壳", "Zhi Ke", "4.5 g"), h("芍药", "Shao Yao", "4.5 g"), h("炙甘草", "Zhi Gan Cao", "1.5 g"), h("香附", "Xiang Fu", "4.5 g")]),
  xueFuZhuYuTang: f("血府逐瘀汤", "Xue Fu Zhu Yu Tang", ["Moves Blood", "Dispels stasis"], [h("桃仁", "Tao Ren", "12 g"), h("红花", "Hong Hua", "9 g"), h("当归", "Dang Gui", "9 g"), h("生地黄", "Sheng Di Huang", "9 g"), h("川芎", "Chuan Xiong", "4.5 g"), h("赤芍", "Chi Shao", "6 g"), h("牛膝", "Niu Xi", "9 g"), h("桔梗", "Jie Geng", "4.5 g"), h("柴胡", "Chai Hu", "3 g"), h("枳壳", "Zhi Ke", "6 g"), h("甘草", "Gan Cao", "3 g")]),
  cangFuDaoTanWan: f("苍附导痰丸", "Cang Fu Dao Tan Wan", ["Dries Dampness", "Transforms Phlegm", "Regulates menstruation"], [h("苍术", "Cang Zhu", "9 g"), h("香附", "Xiang Fu", "9 g"), h("陈皮", "Chen Pi", "6 g"), h("半夏", "Ban Xia", "9 g"), h("茯苓", "Fu Ling", "9 g"), h("胆南星", "Dan Nan Xing", "6 g"), h("枳壳", "Zhi Ke", "6 g"), h("甘草", "Gan Cao", "3 g")]),
  siWuTang: f("四物汤", "Si Wu Tang", ["Nourishes Blood", "Regulates menstruation"], [h("熟地黄", "Shu Di Huang", "12 g"), h("当归", "Dang Gui", "9 g"), h("白芍", "Bai Shao", "9 g"), h("川芎", "Chuan Xiong", "6 g")]),
  baZhenTang: f("八珍汤", "Ba Zhen Tang", ["Tonifies Qi and Blood"], [h("人参", "Ren Shen", "9 g"), h("白术", "Bai Zhu", "9 g"), h("茯苓", "Fu Ling", "9 g"), h("炙甘草", "Zhi Gan Cao", "6 g"), h("熟地黄", "Shu Di Huang", "12 g"), h("当归", "Dang Gui", "9 g"), h("白芍", "Bai Shao", "9 g"), h("川芎", "Chuan Xiong", "6 g")]),
  guiPiTang: f("归脾汤", "Gui Pi Tang", ["Tonifies Heart and Spleen", "Nourishes Blood", "Controls bleeding"], [h("白术", "Bai Zhu", "9 g"), h("茯神", "Fu Shen", "9 g"), h("黄芪", "Huang Qi", "12 g"), h("龙眼肉", "Long Yan Rou", "12 g"), h("酸枣仁", "Suan Zao Ren", "12 g"), h("人参", "Ren Shen", "6 g"), h("木香", "Mu Xiang", "6 g"), h("炙甘草", "Zhi Gan Cao", "3 g"), h("当归", "Dang Gui", "9 g"), h("远志", "Yuan Zhi", "6 g")]),
  zuoGuiWan: f("左归丸", "Zuo Gui Wan", ["Nourishes Kidney Yin and Essence"], [h("熟地黄", "Shu Di Huang", "240 g"), h("山药", "Shan Yao", "120 g"), h("山茱萸", "Shan Zhu Yu", "120 g"), h("枸杞子", "Gou Qi Zi", "120 g"), h("鹿角胶", "Lu Jiao Jiao", "120 g"), h("菟丝子", "Tu Si Zi", "120 g"), h("龟甲胶", "Gui Jia Jiao", "120 g"), h("川牛膝", "Chuan Niu Xi", "90 g")]),
  youGuiWan: f("右归丸", "You Gui Wan", ["Warms Kidney Yang", "Replenishes Essence"], [h("熟地黄", "Shu Di Huang", "240 g"), h("山药", "Shan Yao", "120 g"), h("山茱萸", "Shan Zhu Yu", "90 g"), h("枸杞子", "Gou Qi Zi", "120 g"), h("菟丝子", "Tu Si Zi", "120 g"), h("杜仲", "Du Zhong", "120 g"), h("当归", "Dang Gui", "90 g"), h("鹿角胶", "Lu Jiao Jiao", "120 g"), h("肉桂", "Rou Gui", "60 g"), h("附子", "Fu Zi", "60 g")]),
  wenJingTang: f("温经汤", "Wen Jing Tang", ["Warms uterus", "Moves Blood", "Nourishes Blood"], [h("吴茱萸", "Wu Zhu Yu", "9 g"), h("当归", "Dang Gui", "6 g"), h("川芎", "Chuan Xiong", "6 g"), h("芍药", "Shao Yao", "6 g"), h("人参", "Ren Shen", "6 g"), h("桂枝", "Gui Zhi", "6 g"), h("阿胶", "E Jiao", "6 g"), h("牡丹皮", "Mu Dan Pi", "6 g"), h("生姜", "Sheng Jiang", "6 g"), h("甘草", "Gan Cao", "6 g"), h("半夏", "Ban Xia", "6 g"), h("麦冬", "Mai Dong", "9 g")]),
  shaoFuZhuYuTang: f("少腹逐瘀汤", "Shao Fu Zhu Yu Tang", ["Warms uterus", "Moves Blood", "Stops pain"], [h("小茴香", "Xiao Hui Xiang", "7粒"), h("干姜", "Gan Jiang", "0.6 g"), h("延胡索", "Yan Hu Suo", "3 g"), h("没药", "Mo Yao", "6 g"), h("当归", "Dang Gui", "9 g"), h("川芎", "Chuan Xiong", "6 g"), h("官桂", "Guan Gui", "3 g"), h("赤芍", "Chi Shao", "6 g"), h("蒲黄", "Pu Huang", "9 g"), h("五灵脂", "Wu Ling Zhi", "6 g")]),
  qingJingSan: f("清经散", "Qing Jing San", ["Clears Blood Heat", "Regulates menstruation"], [h("牡丹皮", "Mu Dan Pi", "9 g"), h("地骨皮", "Di Gu Pi", "15 g"), h("白芍", "Bai Shao", "9 g"), h("熟地黄", "Shu Di Huang", "9 g"), h("青蒿", "Qing Hao", "6 g"), h("黄柏", "Huang Bai", "3 g"), h("茯苓", "Fu Ling", "3 g")]),
  liangDiTang: f("两地汤", "Liang Di Tang", ["Nourishes Yin", "Clears empty Heat", "Stops bleeding"], [h("生地黄", "Sheng Di Huang", "30 g"), h("地骨皮", "Di Gu Pi", "9 g"), h("玄参", "Xuan Shen", "30 g"), h("麦冬", "Mai Dong", "15 g"), h("阿胶", "E Jiao", "9 g"), h("白芍", "Bai Shao", "15 g")]),
  guJingWan: f("固经丸", "Gu Jing Wan", ["Nourishes Yin", "Clears Heat", "Stops uterine bleeding"], [h("黄芩", "Huang Qin", "30 g"), h("白芍", "Bai Shao", "30 g"), h("龟板", "Gui Ban", "30 g"), h("黄柏", "Huang Bai", "9 g"), h("椿根皮", "Chun Gen Pi", "22.5 g"), h("香附", "Xiang Fu", "7.5 g")]),
  shouTaiWan: f("寿胎丸", "Shou Tai Wan", ["Tonifies Kidney", "Secures pregnancy"], [h("菟丝子", "Tu Si Zi", "120 g"), h("桑寄生", "Sang Ji Sheng", "60 g"), h("续断", "Xu Duan", "60 g"), h("阿胶", "E Jiao", "60 g")]),
  taiYuanYin: f("胎元饮", "Tai Yuan Yin", ["Tonifies Qi and Blood", "Secures pregnancy"], [h("人参", "Ren Shen", "6 g"), h("当归", "Dang Gui", "6 g"), h("杜仲", "Du Zhong", "6 g"), h("白芍", "Bai Shao", "6 g"), h("熟地黄", "Shu Di Huang", "9 g"), h("白术", "Bai Zhu", "4.5 g"), h("陈皮", "Chen Pi", "3 g"), h("炙甘草", "Zhi Gan Cao", "3 g")]),
  baoYinJian: f("保阴煎", "Bao Yin Jian", ["Clears Heat", "Nourishes Yin", "Stops uterine bleeding"], [h("生地黄", "Sheng Di Huang", "9 g"), h("熟地黄", "Shu Di Huang", "9 g"), h("白芍", "Bai Shao", "6 g"), h("山药", "Shan Yao", "6 g"), h("续断", "Xu Duan", "4.5 g"), h("黄芩", "Huang Qin", "4.5 g"), h("黄柏", "Huang Bai", "4.5 g"), h("生甘草", "Sheng Gan Cao", "3 g")]),
  xiaoYaoSan: f("逍遥散", "Xiao Yao San", ["Spreads Liver Qi", "Strengthens Spleen", "Nourishes Blood"], [h("柴胡", "Chai Hu", "9 g"), h("当归", "Dang Gui", "9 g"), h("白芍", "Bai Shao", "9 g"), h("白术", "Bai Zhu", "9 g"), h("茯苓", "Fu Ling", "9 g"), h("炙甘草", "Zhi Gan Cao", "4.5 g"), h("薄荷", "Bo He", "3 g"), h("生姜", "Sheng Jiang", "3片")]),
  danZhiXiaoYaoSan: f("丹栀逍遥散", "Dan Zhi Xiao Yao San", ["Spreads Liver Qi", "Clears Heat"], [h("柴胡", "Chai Hu", "6 g"), h("当归", "Dang Gui", "6 g"), h("白芍", "Bai Shao", "6 g"), h("白术", "Bai Zhu", "6 g"), h("茯苓", "Fu Ling", "6 g"), h("炙甘草", "Zhi Gan Cao", "3 g"), h("牡丹皮", "Mu Dan Pi", "6 g"), h("栀子", "Zhi Zi", "6 g")]),
  wanDaiTang: f("完带汤", "Wan Dai Tang", ["Tonifies Spleen", "Dries Dampness", "Stops discharge"], [h("白术", "Bai Zhu", "30 g"), h("山药", "Shan Yao", "30 g"), h("人参", "Ren Shen", "6 g"), h("白芍", "Bai Shao", "15 g"), h("车前子", "Che Qian Zi", "9 g"), h("苍术", "Cang Zhu", "9 g"), h("甘草", "Gan Cao", "3 g"), h("陈皮", "Chen Pi", "1.5 g"), h("黑芥穗", "Hei Jie Sui", "1.5 g"), h("柴胡", "Chai Hu", "1.8 g")]),
  yiHuangTang: f("易黄汤", "Yi Huang Tang", ["Clears Damp-Heat", "Stops discharge"], [h("山药", "Shan Yao", "30 g"), h("芡实", "Qian Shi", "30 g"), h("黄柏", "Huang Bai", "6 g"), h("车前子", "Che Qian Zi", "3 g"), h("白果", "Bai Guo", "10枚")]),
  wuWeiXiaoDuYin: f("五味消毒饮", "Wu Wei Xiao Du Yin", ["Clears toxic Heat", "Resolves swelling"], [h("金银花", "Jin Yin Hua", "9 g"), h("野菊花", "Ye Ju Hua", "3.6 g"), h("蒲公英", "Pu Gong Ying", "3.6 g"), h("紫花地丁", "Zi Hua Di Ding", "3.6 g"), h("紫背天葵子", "Zi Bei Tian Kui Zi", "3.6 g")]),
  buZhongYiQiTang: f("补中益气汤", "Bu Zhong Yi Qi Tang", ["Tonifies Qi", "Raises clear Yang"], [h("黄芪", "Huang Qi", "18 g"), h("炙甘草", "Zhi Gan Cao", "9 g"), h("人参", "Ren Shen", "6 g"), h("当归", "Dang Gui", "3 g"), h("陈皮", "Chen Pi", "6 g"), h("升麻", "Sheng Ma", "6 g"), h("柴胡", "Chai Hu", "6 g"), h("白术", "Bai Zhu", "9 g")]),
  shengHuaTang: f("生化汤", "Sheng Hua Tang", ["Nourishes and moves Blood", "Clears lochia", "Stops postpartum pain"], [h("全当归", "Quan Dang Gui", "24 g"), h("川芎", "Chuan Xiong", "9 g"), h("桃仁", "Tao Ren", "6 g"), h("干姜", "Gan Jiang", "2 g"), h("炙甘草", "Zhi Gan Cao", "2 g")]),
  tongRuDan: f("通乳丹", "Tong Ru Dan", ["Tonifies Qi and Blood", "Promotes lactation"], [h("人参", "Ren Shen", "30 g"), h("黄芪", "Huang Qi", "30 g"), h("当归", "Dang Gui", "60 g"), h("麦冬", "Mai Dong", "15 g"), h("木通", "Mu Tong", "9 g"), h("桔梗", "Jie Geng", "9 g"), h("七孔猪蹄", "Qi Kong Zhu Ti", "2个")]),
  xiaRuYongQuanSan: f("下乳涌泉散", "Xia Ru Yong Quan San", ["Moves Liver Qi", "Promotes lactation"], [h("当归", "Dang Gui", "15 g"), h("川芎", "Chuan Xiong", "9 g"), h("天花粉", "Tian Hua Fen", "12 g"), h("白芍", "Bai Shao", "12 g"), h("生地黄", "Sheng Di Huang", "12 g"), h("柴胡", "Chai Hu", "9 g"), h("青皮", "Qing Pi", "6 g"), h("漏芦", "Lou Lu", "9 g"), h("桔梗", "Jie Geng", "6 g"), h("通草", "Tong Cao", "6 g"), h("白芷", "Bai Zhi", "6 g"), h("穿山甲", "Chuan Shan Jia", "6 g"), h("王不留行", "Wang Bu Liu Xing", "9 g"), h("甘草", "Gan Cao", "3 g")]),
  wenDanTang: f("温胆汤", "Wen Dan Tang", ["Transforms Phlegm-Heat", "Calms Shen"], [h("半夏", "Ban Xia", "6 g"), h("竹茹", "Zhu Ru", "6 g"), h("枳实", "Zhi Shi", "6 g"), h("陈皮", "Chen Pi", "9 g"), h("甘草", "Gan Cao", "3 g"), h("茯苓", "Fu Ling", "4.5 g"), h("生姜", "Sheng Jiang", "5片"), h("大枣", "Da Zao", "1枚")]),
  tianMaGouTengYin: f("天麻钩藤饮", "Tian Ma Gou Teng Yin", ["Subdues Liver Yang", "Extinguishes Wind"], [h("天麻", "Tian Ma", "9 g"), h("钩藤", "Gou Teng", "12 g"), h("石决明", "Shi Jue Ming", "18 g"), h("栀子", "Zhi Zi", "9 g"), h("黄芩", "Huang Qin", "9 g"), h("川牛膝", "Chuan Niu Xi", "12 g"), h("杜仲", "Du Zhong", "9 g"), h("益母草", "Yi Mu Cao", "9 g"), h("桑寄生", "Sang Ji Sheng", "9 g"), h("夜交藤", "Ye Jiao Teng", "9 g"), h("茯神", "Fu Shen", "9 g")]),
  huangLianEJiaoTang: f("黄连阿胶汤", "Huang Lian E Jiao Tang", ["Clears Heart Fire", "Nourishes Kidney Yin"], [h("黄连", "Huang Lian", "12 g"), h("黄芩", "Huang Qin", "6 g"), h("芍药", "Shao Yao", "6 g"), h("阿胶", "E Jiao", "9 g"), h("鸡子黄", "Ji Zi Huang", "2枚")]),
  juPiZhuRuTang: f("橘皮竹茹汤", "Ju Pi Zhu Ru Tang", ["Clears Stomach Heat", "Descends rebellious Qi"], [h("橘皮", "Ju Pi", "12 g"), h("竹茹", "Zhu Ru", "12 g"), h("大枣", "Da Zao", "5枚"), h("生姜", "Sheng Jiang", "9 g"), h("甘草", "Gan Cao", "6 g"), h("人参", "Ren Shen", "3 g")]),
  liuJunZiTang: f("六君子汤", "Liu Jun Zi Tang", ["Tonifies Spleen Qi", "Transforms Phlegm"], [h("人参", "Ren Shen", "9 g"), h("白术", "Bai Zhu", "9 g"), h("茯苓", "Fu Ling", "9 g"), h("炙甘草", "Zhi Gan Cao", "6 g"), h("陈皮", "Chen Pi", "3 g"), h("半夏", "Ban Xia", "4.5 g")]),
  baoHeWan: f("保和丸", "Bao He Wan", ["Reduces food stagnation", "Harmonizes Stomach"], [h("山楂", "Shan Zha", "180 g"), h("神曲", "Shen Qu", "60 g"), h("半夏", "Ban Xia", "90 g"), h("茯苓", "Fu Ling", "90 g"), h("陈皮", "Chen Pi", "30 g"), h("连翘", "Lian Qiao", "30 g"), h("莱菔子", "Lai Fu Zi", "30 g")]),
};

type FormulaKey = keyof typeof formulas;
type PatternSpec = [name: string, formula: FormulaKey, section?: string];

function treatment(name: string) {
  const n = name.toLowerCase();
  if (/heat|fire|toxic/.test(n)) return { principle: "Clear Heat, cool Blood, and regulate the uterus.", points: "LR 2, LI 11, SP 10, SP 6, CV 4, CV 6." };
  if (/stasis|trauma/.test(n)) return { principle: "Move Blood, dispel stasis, and regulate the uterus.", points: "SP 10, BL 17, LR 3, SP 6, CV 4, ST 29." };
  if (/qi stagnation|liver qi/.test(n)) return { principle: "Spread Liver Qi, regulate Chong and Ren, and relieve constraint.", points: "LR 3, GB 34, PC 6, SP 6, CV 17, CV 4." };
  if (/phlegm|damp/.test(n)) return { principle: "Transform Damp-Phlegm, strengthen Spleen, and regulate the lower burner.", points: "ST 40, SP 9, ST 36, CV 12, SP 6, CV 4." };
  if (/yang|cold|kidney deficiency/.test(n)) return { principle: "Warm and tonify Kidney Yang, regulate Chong and Ren.", points: "CV 4, GV 4, BL 23, KI 3, SP 6, ST 36. Use moxa." };
  if (/yin|dryness/.test(n)) return { principle: "Nourish Yin and Blood, clear empty Heat, regulate menstruation.", points: "KI 3, KI 6, SP 6, LR 8, CV 4, HT 6." };
  if (/blood deficiency|qi and blood|depletion/.test(n)) return { principle: "Tonify Qi and Blood, nourish Chong and Ren.", points: "ST 36, SP 6, CV 6, BL 17, BL 20, LR 8." };
  if (/spleen|qi deficiency|heart qi/.test(n)) return { principle: "Tonify Qi, strengthen Spleen, and secure the lower burner.", points: "ST 36, BL 20, CV 6, SP 6, GV 20, CV 4." };
  return { principle: "Regulate Qi and Blood, harmonize Chong and Ren.", points: "LR 3, SP 6, ST 36, CV 4, CV 6, BL 17." };
}

function patterns(specs: PatternSpec[]): LungPatternDetail[] {
  return specs.map(([name, formulaKey, section]) => ({ name, section, ...treatment(name), formula: formulas[formulaKey] }));
}

const redFlags = ["Heavy vaginal bleeding", "Severe pelvic or abdominal pain", "Fainting or marked weakness", "Fever or foul discharge", "Any concerning symptom during pregnancy or postpartum"];
const condition = (overview: string, specs: PatternSpec[]): LungConditionDetail => ({ overview, redFlags, patterns: patterns(specs) });

export const gyneContent: Record<number, LungConditionDetail> = {
  76: condition("Abdominal masses in gynecology arise from Qi stagnation, Blood stasis, or Phlegm-Damp accumulation.", [["Stagnation of Qi", "chaiHuShuGanSan"], ["Blood Stasis", "xueFuZhuYuTang"], ["Phlegm-Dampness", "cangFuDaoTanWan"]]),
  77: condition("Amenorrhea is absence of menstruation from deficiency of Essence, Blood, Qi, or obstruction of Chong and Ren.", [["Liver-Kidney Deficiency", "zuoGuiWan"], ["Depletion of Yin and Dryness of Blood", "liangDiTang"], ["Qi and Blood Deficiency", "baZhenTang"], ["Qi Stagnation with Blood Stasis", "xueFuZhuYuTang"], ["Phlegm-Damp Obstruction in Uterus", "cangFuDaoTanWan"]]),
  78: condition("Bleeding during pregnancy requires urgent obstetric assessment before supportive pattern treatment.", [["Kidney Deficiency", "shouTaiWan"], ["Qi and Blood Deficiency", "taiYuanYin"], ["Blood Heat", "baoYinJian"], ["Blood Stasis / Trauma", "xueFuZhuYuTang"]]),
  79: condition("Dysmenorrhea is menstrual pain from Cold, Qi-Blood obstruction, Damp-Heat, or deficiency.", [["Cold-Damp Coagulation", "shaoFuZhuYuTang"], ["Liver Qi Stagnation", "chaiHuShuGanSan"], ["Damp-Heat Descending", "yiHuangTang"], ["Yang Deficiency with Internal Cold", "wenJingTang"], ["Liver-Kidney Deficiency", "zuoGuiWan"], ["Qi and Blood Deficiency", "baZhenTang"]]),
  80: condition("Infertility is differentiated by Kidney, Blood, Cold, Dampness, stasis, Qi constraint, and Heat patterns.", [["Kidney Yang Deficiency", "youGuiWan"], ["Kidney Yin Deficiency", "zuoGuiWan"], ["Blood Deficiency", "siWuTang"], ["Cold in Uterus", "wenJingTang"], ["Dampness in Lower Burner", "cangFuDaoTanWan"], ["Blood Stasis", "xueFuZhuYuTang"], ["Qi Stagnation", "xiaoYaoSan"], ["Blood Heat", "qingJingSan"]]),
  81: condition("Insufficient breastmilk results chiefly from deficient Qi-Blood production or constrained Liver Qi.", [["Qi and Blood Deficiency", "tongRuDan"], ["Liver Qi Stagnation", "xiaRuYongQuanSan"]]),
  82: condition("Intermenstrual bleeding occurs when Kidney, Spleen, Heat, Dampness, or stasis destabilize Chong and Ren.", [["Liver-Kidney Yin Deficiency with Empty Heat", "liangDiTang"], ["Damp-Heat", "yiHuangTang"], ["Blood Stasis", "xueFuZhuYuTang"], ["Spleen-Kidney Yang Deficiency", "youGuiWan"]]),
  83: condition("Irregular menstruation includes early, late, and unpredictable cycles, each with distinct excess and deficiency patterns.", [
    ["Blood Heat", "qingJingSan", "Early Periods"], ["Full Heat", "qingJingSan", "Early Periods"], ["Heat Accumulation", "baoYinJian", "Early Periods"], ["Liver Qi Turning into Fire with Blood Heat", "danZhiXiaoYaoSan", "Early Periods"], ["Empty Heat", "liangDiTang", "Early Periods"], ["Qi Deficiency", "guiPiTang", "Early Periods"], ["Spleen Qi Deficiency", "buZhongYiQiTang", "Early Periods"], ["Kidney Qi Deficiency", "shouTaiWan", "Early Periods"],
    ["Blood Deficiency", "siWuTang", "Late Periods"], ["Excess Cold", "shaoFuZhuYuTang", "Late Periods"], ["Deficiency Cold", "wenJingTang", "Late Periods"], ["Qi Stagnation", "chaiHuShuGanSan", "Late Periods"],
    ["Liver Qi Stagnation", "xiaoYaoSan", "Unpredictable Periods"], ["Kidney Deficiency", "zuoGuiWan", "Unpredictable Periods"],
  ]),
  84: condition("Leukorrhagia is abnormal vaginal discharge from Spleen/Kidney deficiency, Damp-Heat, toxin, or Qi stagnation.", [["Spleen Qi Deficiency", "wanDaiTang"], ["Kidney Yang Deficiency", "youGuiWan"], ["Kidney Yin Deficiency", "zuoGuiWan"], ["Damp-Heat Pouring Downward", "yiHuangTang"], ["Toxic Heat", "wuWeiXiaoDuYin"], ["Liver Qi Stagnation", "xiaoYaoSan"]]),
  85: condition("Persistent postpartum lochia is caused by Qi deficiency, Blood stasis, or Blood Heat.", [["Qi Deficiency", "buZhongYiQiTang"], ["Blood Stasis", "shengHuaTang"], ["Blood Heat", "baoYinJian"]]),
  86: condition("Menstrual breast aching reflects Liver Qi/Blood obstruction, Phlegm, or Liver-Kidney deficiency.", [["Liver Qi Stagnation", "chaiHuShuGanSan"], ["Liver Blood Stasis", "xueFuZhuYuTang"], ["Phlegm with Qi Stagnation", "cangFuDaoTanWan"], ["Liver-Kidney Yin Deficiency", "zuoGuiWan"]]),
  87: condition("Menstrual edema arises from Yang deficiency failing to move water or cyclical Qi stagnation.", [["Spleen-Kidney Yang Deficiency", "youGuiWan"], ["Qi Stagnation", "xiaoYaoSan"]]),
  88: condition("Menstrual headache follows cyclical Blood deficiency, Liver Fire/Yang, or Blood stasis.", [["Blood Deficiency", "siWuTang"], ["Liver Fire Blazing", "danZhiXiaoYaoSan"], ["Liver Yang Rising", "tianMaGouTengYin"], ["Blood Stasis", "xueFuZhuYuTang"]]),
  89: condition("Menstrual hematemesis and epistaxis reflect rebellious Blood driven upward by Fire or Yin deficiency.", [["Stagnant Liver Qi Turning into Fire", "danZhiXiaoYaoSan"], ["Lung-Kidney Yin Deficiency", "liangDiTang"]]),
  90: condition("Menstrual mental disturbance is cyclical Shen disruption from Qi constraint, Phlegm-Fire, deficiency, or Yang collapse.", [["Liver Qi Stagnation", "xiaoYaoSan"], ["Phlegm-Fire Harassing Upward", "wenDanTang"], ["Liver Blood Deficiency", "siWuTang"], ["Liver-Kidney Yin Deficiency", "zuoGuiWan"], ["Spleen-Kidney Yang Deficiency", "youGuiWan"]]),
  91: condition("Menstrual oral ulcers result from cyclical empty Heat, Stomach Fire, or Damp-Heat.", [["Kidney Yin Deficiency with Empty Heat", "liangDiTang"], ["Stomach Fire or Stomach Damp-Heat", "qingJingSan"], ["Stomach Damp-Heat with Spleen Deficiency", "yiHuangTang"]]),
  92: condition("Metrorrhagia and metrostaxis are heavy or irregular uterine bleeding caused by Heat, stasis, Dampness, or failure to secure Blood.", [["Blood Heat", "qingJingSan"], ["Liver Qi Stagnation Turning into Heat", "danZhiXiaoYaoSan"], ["Blood Empty Heat", "liangDiTang"], ["Blood Stasis", "xueFuZhuYuTang"], ["Damp-Heat in Uterus", "yiHuangTang"], ["Spleen Not Holding Blood", "guiPiTang"], ["Kidney Yang Deficiency", "youGuiWan"], ["Kidney Yin Deficiency", "guJingWan"]]),
  93: condition("Habitual miscarriage requires obstetric evaluation; TCM patterns center on Kidney, Qi-Blood, Heat, and stasis.", [["Kidney Yang Deficiency", "youGuiWan"], ["Kidney Yin Deficiency", "zuoGuiWan"], ["Blood Heat", "baoYinJian"], ["Spleen Qi Deficiency", "shouTaiWan"], ["Blood Deficiency", "taiYuanYin"], ["Blood Stasis", "xueFuZhuYuTang"]]),
  94: condition("Morning sickness is rebellious Stomach Qi during pregnancy from deficiency, Heat, Liver overacting, or Phlegm.", [["Stomach Qi Deficiency with Empty Cold", "liuJunZiTang"], ["Stomach Yin Deficiency", "liangDiTang"], ["Stagnant Liver Qi Invading Stomach", "xiaoYaoSan"], ["Stomach Heat", "juPiZhuRuTang"], ["Accumulation of Phlegm", "wenDanTang"], ["Heart Qi Deficiency", "guiPiTang"], ["Heart Fire", "huangLianEJiaoTang"]]),
  95: condition("Perimenopausal syndrome reflects declining Kidney Essence with Yin/Yang imbalance and secondary Liver, Heart, Phlegm, or stasis patterns.", [["Kidney Yin Deficiency", "zuoGuiWan"], ["Kidney Yang Deficiency", "youGuiWan"], ["Kidney Yin and Yang Deficiency", "youGuiWan"], ["Kidney-Liver Yin Deficiency with Liver Yang Rising", "tianMaGouTengYin"], ["Kidney-Heart Disharmony", "huangLianEJiaoTang"], ["Phlegm Accumulation with Qi Stagnation", "wenDanTang"], ["Blood Stasis", "xueFuZhuYuTang"]]),
  96: condition("Postpartum abdominal pain is caused by Blood deficiency, retained stasis, or food stagnation.", [["Blood Deficiency", "siWuTang"], ["Blood Stasis", "shengHuaTang"], ["Food Retention", "baoHeWan"]]),
  97: condition("Postpartum convulsion is an emergency pattern involving severe Blood-Yin depletion or toxic invasion.", [["Blood and Yin Deficiency with Empty Wind", "tianMaGouTengYin"], ["Exterior Invasion of Toxin", "wuWeiXiaoDuYin"]]),
  98: condition("Postpartum dizziness may reflect Blood depletion with Qi collapse or Blood stasis blocking clear Yang.", [["Blood Depletion with Qi Desertion", "baZhenTang"], ["Blood Stasis with Qi Blockage", "shengHuaTang"]]),
  99: condition("Postpartum fever may arise from infection, exterior Wind, deficiency, stasis, breast inflammation, or food retention.", [["Invasion of External Toxins", "wuWeiXiaoDuYin"], ["Invasion of External Wind", "xiaoYaoSan"], ["Blood Deficiency", "siWuTang"], ["Blood Stasis", "shengHuaTang"], ["Steaming Breast", "wuWeiXiaoDuYin"], ["Food Retention", "baoHeWan"]]),
  100: condition("Postpartum urinary retention follows Qi deficiency, impaired Lung-Spleen water movement, Kidney deficiency, or Bladder injury.", [["Spleen Qi Deficiency", "buZhongYiQiTang"], ["Lung-Spleen Qi Deficiency", "buZhongYiQiTang"], ["Kidney Qi Deficiency", "youGuiWan"], ["Injury to Bladder", "xueFuZhuYuTang"]]),
  101: condition("Uterine prolapse is sinking of pelvic support from Spleen Qi or Kidney deficiency.", [["Spleen Qi Deficiency", "buZhongYiQiTang"], ["Kidney Deficiency", "youGuiWan"]]),
};
