export const gyneLectureTechniques: Record<string, string[]> = {
  "100|injury to bladder": ["Moxa is included in the course protocol only when clinically suitable."],
  "100|kidney qi deficiency": ["Moxa is included in the course protocol only when clinically suitable."],
  "100|lung-spleen qi deficiency": ["Mixed reinforcing and even methods; follow the course protocol point by point."],
  "100|spleen qi deficiency": ["Moxa is included in the course protocol only when clinically suitable."],
  "101|kidney deficiency": ["Moxa is included in the course protocol only when clinically suitable."],
  "101|spleen qi deficiency": ["Moxa is included in the course protocol only when clinically suitable."],
  "76|blood stasis": ["Reducing method.","Moxa is included in the course protocol only when clinically suitable."],
  "76|phlegm-dampness": ["Even method.","Moxa is included in the course protocol only when clinically suitable."],
  "76|stagnation of qi": ["Reducing method.","Moxa is included in the course protocol only when clinically suitable."],
  "77|depletion of yin and dryness of blood": ["Reinforcing method."],
  "77|liver-kidney deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "77|phlegm-damp obstruction in uterus": ["Even method.","Moxa is included in the course protocol only when clinically suitable."],
  "77|qi and blood deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "77|qi stagnation with blood stasis": ["Reducing method."],
  "78|blood heat": ["Reducing or even method as specified by the course protocol.","No moxa."],
  "78|blood stasis / trauma": ["Mixed reinforcing and even methods; follow the course protocol point by point."],
  "78|kidney deficiency": ["Reinforcing method.","Moxa is conditional; use only for the source-specified indication and when clinically suitable."],
  "78|qi and blood deficiency": ["Reinforcing method.","Moxa is conditional; use only for the source-specified indication and when clinically suitable."],
  "79|cold-damp coagulation": ["Reducing method."],
  "79|damp-heat descending": ["Reducing method."],
  "79|liver qi stagnation": ["Reducing method."],
  "79|liver-kidney deficiency": ["Reinforcing method."],
  "79|qi and blood deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "79|yang deficiency with internal cold": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "80|blood deficiency": ["Reinforcing method.","Moxa is conditional; use only for the source-specified indication and when clinically suitable."],
  "80|blood heat": ["Reducing or even method as specified by the course protocol.","No moxa."],
  "80|blood stasis": ["Reducing or even method as specified by the course protocol."],
  "80|cold in uterus": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "80|dampness in lower burner": ["Mixed reinforcing and even methods; follow the course protocol point by point.","No moxa."],
  "80|kidney yang deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "80|kidney yin deficiency": ["Reinforcing method.","No moxa."],
  "80|qi stagnation": ["Reducing or even method as specified by the course protocol."],
  "81|liver qi stagnation": ["Reducing method."],
  "81|qi and blood deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "82|blood stasis": ["Reducing or even method as specified by the course protocol."],
  "82|damp-heat": ["Reducing or even method as specified by the course protocol.","Moxa is included in the course protocol only when clinically suitable."],
  "82|liver-kidney yin deficiency with empty heat": ["Reducing or even method as specified by the course protocol.","No moxa."],
  "82|spleen-kidney yang deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "83|blood deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "83|blood heat": ["Reducing method."],
  "83|deficiency cold": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "83|early periods: blood heat, full heat, heat accumulation, stagnant liver qi turning into fire with blood heat, empty heat, qi deficiency, spleen qi deficiency, kidney qi deficiency. late periods: blood deficiency, cold excess/deficiency, qi stagnation. unpredictable periods: liver qi stagnation, kidney deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "83|empty heat": ["Reinforcing method."],
  "83|excess cold": ["Moxa is included in the course protocol only when clinically suitable."],
  "83|full heat": ["Reducing method."],
  "83|heat accumulation": ["Reducing method."],
  "83|kidney deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "83|kidney qi deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "83|liver qi turning into fire with blood heat": ["Reducing method."],
  "83|qi deficiency": ["Reinforcing method."],
  "83|qi stagnation": ["Reducing method."],
  "83|spleen qi deficiency": ["Reinforcing method."],
  "84|damp-heat pouring downward": ["Reducing method."],
  "84|kidney yang deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "84|kidney yin deficiency": ["Even method."],
  "84|liver qi stagnation": ["Mixed reinforcing, reducing, and even methods; follow the course protocol point by point."],
  "84|spleen qi deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "84|toxic heat": ["Reducing or even method as specified by the course protocol."],
  "85|blood heat": ["Even method.","No moxa."],
  "85|blood stasis": ["Even method.","Moxa is conditional; use only for the source-specified indication and when clinically suitable."],
  "85|qi deficiency": ["Reinforcing method.","Moxa is conditional; use only for the source-specified indication and when clinically suitable."],
  "86|liver blood stasis": ["Reducing or even method as specified by the course protocol."],
  "86|liver qi stagnation": ["Reducing or even method as specified by the course protocol."],
  "86|liver-kidney yin deficiency": ["Reducing or even method as specified by the course protocol.","No moxa."],
  "86|phlegm with qi stagnation": ["Reducing or even method as specified by the course protocol."],
  "87|qi stagnation": ["Reducing or even method as specified by the course protocol."],
  "87|spleen-kidney yang deficiency": ["Moxa is conditional; use only for the source-specified indication and when clinically suitable."],
  "88|liver fire blazing": ["Reducing or even method as specified by the course protocol.","No moxa."],
  "89|stagnant liver qi turning into fire": ["Reducing or even method as specified by the course protocol."],
  "90|liver blood deficiency": ["Moxa is included in the course protocol only when clinically suitable."],
  "90|liver qi stagnation": ["Reducing or even method as specified by the course protocol."],
  "90|liver-kidney yin deficiency": ["Mixed reinforcing and even methods; follow the course protocol point by point."],
  "90|phlegm-fire harassing upward": ["Reducing or even method as specified by the course protocol."],
  "90|spleen-kidney yang deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "91|stomach damp-heat with spleen deficiency": ["Reducing or even method as specified by the course protocol."],
  "91|stomach fire or stomach damp-heat": ["Reducing or even method as specified by the course protocol."],
  "92|blood heat": ["Reducing method.","No moxa."],
  "92|blood stasis": ["Reducing method."],
  "92|damp-heat in uterus": ["Reducing method.","No moxa."],
  "92|kidney yang deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "92|kidney yin deficiency": ["Mixed reinforcing and even methods; follow the course protocol point by point.","No moxa."],
  "92|liver qi stagnation turning into heat": ["Reducing or even method as specified by the course protocol."],
  "92|spleen not holding blood": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "93|blood deficiency": ["Reinforcing method."],
  "93|blood heat": ["Reducing or even method as specified by the course protocol."],
  "93|blood stasis": ["Even method.","Moxa is included in the course protocol only when clinically suitable."],
  "93|kidney yang deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "93|kidney yin deficiency": ["No moxa."],
  "93|spleen qi deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "94|accumulation of phlegm": ["Even method."],
  "94|heart fire": ["Reducing or even method as specified by the course protocol."],
  "94|heart qi deficiency": ["Reinforcing method.","Moxa is conditional; use only for the source-specified indication and when clinically suitable."],
  "94|stagnant liver qi invading stomach": ["Even method."],
  "94|stomach qi deficiency with empty cold": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "94|stomach yin deficiency": ["Mixed reinforcing and even methods; follow the course protocol point by point.","No moxa."],
  "95|blood stasis": ["Reducing or even method as specified by the course protocol.","Moxa is conditional; use only for the source-specified indication and when clinically suitable."],
  "95|kidney yang deficiency": ["Reinforcing method.","Moxa is included in the course protocol only when clinically suitable."],
  "95|kidney yin and yang deficiency": ["Reinforcing method.","Moxa is conditional; use only when Yang deficiency predominates and clinically suitable."],
  "95|kidney-heart disharmony": ["Reduce or use even method on HT 6, HT 8, and PC 7; reinforce the remaining points."],
  "95|kidney-liver yin deficiency with liver yang rising": ["Reinforce KI 3, LR 8, and CV 4; reduce the remaining points.","No moxa."],
  "95|phlegm accumulation with qi stagnation": ["Reducing or even method as specified by the course protocol."],
  "96|blood deficiency": ["Reinforcing method.","Moxa is conditional; use only for the source-specified indication and when clinically suitable."],
  "96|blood stasis": ["Mixed reinforcing and even methods; follow the course protocol point by point.","Moxa is conditional; use only for the source-specified indication and when clinically suitable."],
  "96|food retention": ["Reducing or even method as specified by the course protocol."],
  "97|exterior invasion of toxin": ["Reducing method.","No moxa."],
  "98|blood depletion with qi desertion": ["Moxa is included in the course protocol only when clinically suitable."],
  "98|blood stasis with qi blockage": ["Moxa is included in the course protocol only when clinically suitable."],
  "99|blood stasis": ["Reducing or even method as specified by the course protocol."],
  "99|food retention": ["Reducing or even method as specified by the course protocol.","No moxa."],
  "99|invasion of external toxins": ["No moxa."],
  "99|steaming breast": ["Reducing or even method as specified by the course protocol."],
};
