import type { FormulaDetail, LungConditionDetail } from "./lungContent";

const heartIngredients = {
  xueFuZhuYuTang: [
    { chineseName: "桃仁", pinyin: "Tao Ren", englishName: "Peach Kernel", dose: "12 g" },
    { chineseName: "红花", pinyin: "Hong Hua", englishName: "Safflower", dose: "9 g" },
    { chineseName: "当归", pinyin: "Dang Gui", englishName: "Chinese Angelica", dose: "9 g" },
    { chineseName: "生地黄", pinyin: "Sheng Di Huang", englishName: "Rehmannia Root", dose: "9 g" },
    { chineseName: "川芎", pinyin: "Chuan Xiong", englishName: "Sichuan Lovage", dose: "4.5 g" },
    { chineseName: "赤芍", pinyin: "Chi Shao", englishName: "Red Peony Root", dose: "6 g" },
    { chineseName: "牛膝", pinyin: "Niu Xi", englishName: "Achyranthes Root", dose: "9 g" },
    { chineseName: "桔梗", pinyin: "Jie Geng", englishName: "Platycodon", dose: "4.5 g" },
    { chineseName: "柴胡", pinyin: "Chai Hu", englishName: "Bupleurum", dose: "3 g" },
    { chineseName: "枳壳", pinyin: "Zhi Ke", englishName: "Bitter Orange", dose: "6 g" },
    { chineseName: "甘草", pinyin: "Gan Cao", englishName: "Licorice Root", dose: "3 g" },
  ],
  guaLouXieBaiBanXiaTang: [
    { chineseName: "瓜蒌实", pinyin: "Gua Lou Shi", englishName: "Trichosanthes Fruit", dose: "12 g" },
    { chineseName: "薤白", pinyin: "Xie Bai", englishName: "Chinese Chive Bulb", dose: "9 g" },
    { chineseName: "半夏", pinyin: "Ban Xia", englishName: "Pinellia", dose: "9 g" },
    { chineseName: "白酒", pinyin: "Bai Jiu", englishName: "Rice Wine", dose: "适量" },
  ],
  zhiShiXieBaiGuiZhiTang: [
    { chineseName: "枳实", pinyin: "Zhi Shi", englishName: "Immature Bitter Orange", dose: "12 g" },
    { chineseName: "厚朴", pinyin: "Hou Po", englishName: "Magnolia Bark", dose: "12 g" },
    { chineseName: "薤白", pinyin: "Xie Bai", englishName: "Chinese Chive Bulb", dose: "9 g" },
    { chineseName: "桂枝", pinyin: "Gui Zhi", englishName: "Cinnamon Twig", dose: "6 g" },
    { chineseName: "瓜蒌实", pinyin: "Gua Lou Shi", englishName: "Trichosanthes Fruit", dose: "12 g" },
  ],
  tianWangBuXinDan: [
    { chineseName: "生地黄", pinyin: "Sheng Di Huang", englishName: "Rehmannia Root", dose: "120 g" },
    { chineseName: "人参", pinyin: "Ren Shen", englishName: "Ginseng", dose: "15 g" },
    { chineseName: "丹参", pinyin: "Dan Shen", englishName: "Salvia Root", dose: "15 g" },
    { chineseName: "玄参", pinyin: "Xuan Shen", englishName: "Scrophularia Root", dose: "15 g" },
    { chineseName: "茯苓", pinyin: "Fu Ling", englishName: "Poria", dose: "15 g" },
    { chineseName: "五味子", pinyin: "Wu Wei Zi", englishName: "Schisandra Fruit", dose: "15 g" },
    { chineseName: "远志", pinyin: "Yuan Zhi", englishName: "Polygala Root", dose: "15 g" },
    { chineseName: "桔梗", pinyin: "Jie Geng", englishName: "Platycodon", dose: "15 g" },
    { chineseName: "当归", pinyin: "Dang Gui", englishName: "Chinese Angelica", dose: "15 g" },
    { chineseName: "天冬", pinyin: "Tian Dong", englishName: "Asparagus Root", dose: "15 g" },
    { chineseName: "麦冬", pinyin: "Mai Dong", englishName: "Ophiopogon Root", dose: "15 g" },
    { chineseName: "柏子仁", pinyin: "Bai Zi Ren", englishName: "Biota Seed", dose: "15 g" },
    { chineseName: "酸枣仁", pinyin: "Suan Zao Ren", englishName: "Sour Jujube Seed", dose: "15 g" },
    { chineseName: "朱砂", pinyin: "Zhu Sha", englishName: "Cinnabar", dose: "15 g" },
  ],
  guiPiTang: [
    { chineseName: "白术", pinyin: "Bai Zhu", englishName: "Atractylodes", dose: "9 g" },
    { chineseName: "茯神", pinyin: "Fu Shen", englishName: "Poria Spirit", dose: "9 g" },
    { chineseName: "黄芪", pinyin: "Huang Qi", englishName: "Astragalus", dose: "12 g" },
    { chineseName: "龙眼肉", pinyin: "Long Yan Rou", englishName: "Longan Aril", dose: "12 g" },
    { chineseName: "酸枣仁", pinyin: "Suan Zao Ren", englishName: "Sour Jujube Seed", dose: "12 g" },
    { chineseName: "人参", pinyin: "Ren Shen", englishName: "Ginseng", dose: "6 g" },
    { chineseName: "木香", pinyin: "Mu Xiang", englishName: "Aucklandia", dose: "6 g" },
    { chineseName: "炙甘草", pinyin: "Zhi Gan Cao", englishName: "Honey-fried Licorice", dose: "3 g" },
    { chineseName: "当归", pinyin: "Dang Gui", englishName: "Chinese Angelica", dose: "9 g" },
    { chineseName: "远志", pinyin: "Yuan Zhi", englishName: "Polygala Root", dose: "6 g" },
    { chineseName: "生姜", pinyin: "Sheng Jiang", englishName: "Fresh Ginger", dose: "3片" },
    { chineseName: "大枣", pinyin: "Da Zao", englishName: "Jujube", dose: "3枚" },
  ],
  anShenDingZhiWan: [
    { chineseName: "人参", pinyin: "Ren Shen", englishName: "Ginseng", dose: "30 g" },
    { chineseName: "茯苓", pinyin: "Fu Ling", englishName: "Poria", dose: "30 g" },
    { chineseName: "茯神", pinyin: "Fu Shen", englishName: "Poria Spirit", dose: "30 g" },
    { chineseName: "石菖蒲", pinyin: "Shi Chang Pu", englishName: "Acorus", dose: "15 g" },
    { chineseName: "远志", pinyin: "Yuan Zhi", englishName: "Polygala Root", dose: "15 g" },
    { chineseName: "龙齿", pinyin: "Long Chi", englishName: "Dragon Tooth", dose: "30 g" },
  ],
  huangLianEJiaoTang: [
    { chineseName: "黄连", pinyin: "Huang Lian", englishName: "Coptis", dose: "12 g" },
    { chineseName: "黄芩", pinyin: "Huang Qin", englishName: "Scutellaria", dose: "6 g" },
    { chineseName: "芍药", pinyin: "Shao Yao", englishName: "Peony Root", dose: "6 g" },
    { chineseName: "阿胶", pinyin: "E Jiao", englishName: "Donkey-hide Gelatin", dose: "9 g" },
    { chineseName: "鸡子黄", pinyin: "Ji Zi Huang", englishName: "Egg Yolk", dose: "2枚" },
  ],
  wenDanTang: [
    { chineseName: "半夏", pinyin: "Ban Xia", englishName: "Pinellia", dose: "6 g" },
    { chineseName: "竹茹", pinyin: "Zhu Ru", englishName: "Bamboo Shavings", dose: "6 g" },
    { chineseName: "枳实", pinyin: "Zhi Shi", englishName: "Immature Bitter Orange", dose: "6 g" },
    { chineseName: "陈皮", pinyin: "Chen Pi", englishName: "Tangerine Peel", dose: "9 g" },
    { chineseName: "甘草", pinyin: "Gan Cao", englishName: "Licorice Root", dose: "3 g" },
    { chineseName: "茯苓", pinyin: "Fu Ling", englishName: "Poria", dose: "4.5 g" },
    { chineseName: "生姜", pinyin: "Sheng Jiang", englishName: "Fresh Ginger", dose: "5片" },
    { chineseName: "大枣", pinyin: "Da Zao", englishName: "Jujube", dose: "1枚" },
  ],
  longDanXieGanTang: [
    { chineseName: "龙胆草", pinyin: "Long Dan Cao", englishName: "Gentiana Root", dose: "6 g" },
    { chineseName: "黄芩", pinyin: "Huang Qin", englishName: "Scutellaria", dose: "9 g" },
    { chineseName: "栀子", pinyin: "Zhi Zi", englishName: "Gardenia Fruit", dose: "9 g" },
    { chineseName: "泽泻", pinyin: "Ze Xie", englishName: "Alisma", dose: "12 g" },
    { chineseName: "木通", pinyin: "Mu Tong", englishName: "Akebia Stem", dose: "9 g" },
    { chineseName: "车前子", pinyin: "Che Qian Zi", englishName: "Plantago Seed", dose: "9 g" },
    { chineseName: "当归", pinyin: "Dang Gui", englishName: "Chinese Angelica", dose: "3 g" },
    { chineseName: "生地黄", pinyin: "Sheng Di Huang", englishName: "Rehmannia Root", dose: "9 g" },
    { chineseName: "柴胡", pinyin: "Chai Hu", englishName: "Bupleurum", dose: "6 g" },
    { chineseName: "生甘草", pinyin: "Sheng Gan Cao", englishName: "Raw Licorice", dose: "6 g" },
  ],
  daoChiSan: [
    { chineseName: "生地黄", pinyin: "Sheng Di Huang", englishName: "Rehmannia Root", dose: "6 g" },
    { chineseName: "木通", pinyin: "Mu Tong", englishName: "Akebia Stem", dose: "6 g" },
    { chineseName: "生甘草梢", pinyin: "Sheng Gan Cao Shao", englishName: "Raw Licorice Tip", dose: "6 g" },
    { chineseName: "竹叶", pinyin: "Zhu Ye", englishName: "Bamboo Leaf", dose: "6 g" },
  ],
  banXiaHouPoTang: [
    { chineseName: "半夏", pinyin: "Ban Xia", englishName: "Pinellia", dose: "12 g" },
    { chineseName: "厚朴", pinyin: "Hou Po", englishName: "Magnolia Bark", dose: "9 g" },
    { chineseName: "茯苓", pinyin: "Fu Ling", englishName: "Poria", dose: "12 g" },
    { chineseName: "生姜", pinyin: "Sheng Jiang", englishName: "Fresh Ginger", dose: "15 g" },
    { chineseName: "苏叶", pinyin: "Su Ye", englishName: "Perilla Leaf", dose: "6 g" },
  ],
  chaiHuShuGanSan: [
    { chineseName: "陈皮", pinyin: "Chen Pi", englishName: "Tangerine Peel", dose: "6 g" },
    { chineseName: "柴胡", pinyin: "Chai Hu", englishName: "Bupleurum", dose: "6 g" },
    { chineseName: "川芎", pinyin: "Chuan Xiong", englishName: "Sichuan Lovage", dose: "4.5 g" },
    { chineseName: "枳壳", pinyin: "Zhi Ke", englishName: "Bitter Orange", dose: "4.5 g" },
    { chineseName: "芍药", pinyin: "Shao Yao", englishName: "Peony Root", dose: "4.5 g" },
    { chineseName: "炙甘草", pinyin: "Zhi Gan Cao", englishName: "Honey-fried Licorice", dose: "1.5 g" },
    { chineseName: "香附", pinyin: "Xiang Fu", englishName: "Cyperus", dose: "4.5 g" },
  ],
  danZhiXiaoYaoSan: [
    { chineseName: "柴胡", pinyin: "Chai Hu", englishName: "Bupleurum", dose: "6 g" },
    { chineseName: "当归", pinyin: "Dang Gui", englishName: "Chinese Angelica", dose: "6 g" },
    { chineseName: "白芍", pinyin: "Bai Shao", englishName: "White Peony Root", dose: "6 g" },
    { chineseName: "白术", pinyin: "Bai Zhu", englishName: "Atractylodes", dose: "6 g" },
    { chineseName: "茯苓", pinyin: "Fu Ling", englishName: "Poria", dose: "6 g" },
    { chineseName: "炙甘草", pinyin: "Zhi Gan Cao", englishName: "Honey-fried Licorice", dose: "3 g" },
    { chineseName: "薄荷", pinyin: "Bo He", englishName: "Mint", dose: "3 g" },
    { chineseName: "生姜", pinyin: "Sheng Jiang", englishName: "Fresh Ginger", dose: "3片" },
    { chineseName: "牡丹皮", pinyin: "Mu Dan Pi", englishName: "Moutan Bark", dose: "6 g" },
    { chineseName: "栀子", pinyin: "Zhi Zi", englishName: "Gardenia Fruit", dose: "6 g" },
  ],
  ganMaiDaZaoTang: [
    { chineseName: "甘草", pinyin: "Gan Cao", englishName: "Licorice Root", dose: "9 g" },
    { chineseName: "小麦", pinyin: "Xiao Mai", englishName: "Wheat", dose: "15 g" },
    { chineseName: "大枣", pinyin: "Da Zao", englishName: "Jujube", dose: "10枚" },
  ],
  dingXianWan: [
    { chineseName: "天麻", pinyin: "Tian Ma", englishName: "Gastrodia", dose: "30 g" },
    { chineseName: "川贝母", pinyin: "Chuan Bei Mu", englishName: "Fritillaria", dose: "30 g" },
    { chineseName: "半夏", pinyin: "Ban Xia", englishName: "Pinellia", dose: "30 g" },
    { chineseName: "茯苓", pinyin: "Fu Ling", englishName: "Poria", dose: "30 g" },
    { chineseName: "茯神", pinyin: "Fu Shen", englishName: "Poria Spirit", dose: "30 g" },
    { chineseName: "胆南星", pinyin: "Dan Nan Xing", englishName: "Arisaema with Bile", dose: "30 g" },
    { chineseName: "石菖蒲", pinyin: "Shi Chang Pu", englishName: "Acorus", dose: "30 g" },
    { chineseName: "远志", pinyin: "Yuan Zhi", englishName: "Polygala Root", dose: "30 g" },
    { chineseName: "全蝎", pinyin: "Quan Xie", englishName: "Scorpion", dose: "15 g" },
    { chineseName: "僵蚕", pinyin: "Jiang Can", englishName: "Bombyx Batryticatus", dose: "15 g" },
    { chineseName: "琥珀", pinyin: "Hu Po", englishName: "Amber", dose: "15 g" },
    { chineseName: "朱砂", pinyin: "Zhu Sha", englishName: "Cinnabar", dose: "15 g" },
    { chineseName: "陈皮", pinyin: "Chen Pi", englishName: "Tangerine Peel", dose: "30 g" },
    { chineseName: "麦冬", pinyin: "Mai Dong", englishName: "Ophiopogon Root", dose: "30 g" },
    { chineseName: "丹参", pinyin: "Dan Shen", englishName: "Salvia Root", dose: "30 g" },
  ],
  longDanXieGanTangHeDingXianWan: [
    ...[] as NonNullable<FormulaDetail["ingredients"]>,
  ],
  zuoGuiWan: [
    { chineseName: "熟地黄", pinyin: "Shu Di Huang", englishName: "Prepared Rehmannia", dose: "240 g" },
    { chineseName: "山药", pinyin: "Shan Yao", englishName: "Chinese Yam", dose: "120 g" },
    { chineseName: "山茱萸", pinyin: "Shan Zhu Yu", englishName: "Cornus Fruit", dose: "120 g" },
    { chineseName: "枸杞子", pinyin: "Gou Qi Zi", englishName: "Lycium Fruit", dose: "120 g" },
    { chineseName: "鹿角胶", pinyin: "Lu Jiao Jiao", englishName: "Deer Antler Gelatin", dose: "120 g" },
    { chineseName: "菟丝子", pinyin: "Tu Si Zi", englishName: "Cuscuta Seed", dose: "120 g" },
    { chineseName: "龟甲胶", pinyin: "Gui Jia Jiao", englishName: "Tortoise Shell Gelatin", dose: "120 g" },
    { chineseName: "川牛膝", pinyin: "Chuan Niu Xi", englishName: "Cyathula Root", dose: "90 g" },
  ],
  liuJunZiTang: [
    { chineseName: "人参", pinyin: "Ren Shen", englishName: "Ginseng", dose: "9 g" },
    { chineseName: "白术", pinyin: "Bai Zhu", englishName: "Atractylodes", dose: "9 g" },
    { chineseName: "茯苓", pinyin: "Fu Ling", englishName: "Poria", dose: "9 g" },
    { chineseName: "炙甘草", pinyin: "Zhi Gan Cao", englishName: "Honey-fried Licorice", dose: "6 g" },
    { chineseName: "陈皮", pinyin: "Chen Pi", englishName: "Tangerine Peel", dose: "3 g" },
    { chineseName: "半夏", pinyin: "Ban Xia", englishName: "Pinellia", dose: "4.5 g" },
    { chineseName: "生姜", pinyin: "Sheng Jiang", englishName: "Fresh Ginger", dose: "3片" },
    { chineseName: "大枣", pinyin: "Da Zao", englishName: "Jujube", dose: "2枚" },
  ],
  suHeXiangWan: [
    { chineseName: "苏合香", pinyin: "Su He Xiang", englishName: "Styrax", dose: "30 g" },
    { chineseName: "安息香", pinyin: "An Xi Xiang", englishName: "Benzoin", dose: "30 g" },
    { chineseName: "冰片", pinyin: "Bing Pian", englishName: "Borneol", dose: "30 g" },
    { chineseName: "麝香", pinyin: "She Xiang", englishName: "Musk", dose: "30 g" },
    { chineseName: "木香", pinyin: "Mu Xiang", englishName: "Aucklandia", dose: "60 g" },
    { chineseName: "沉香", pinyin: "Chen Xiang", englishName: "Aquilaria", dose: "60 g" },
    { chineseName: "丁香", pinyin: "Ding Xiang", englishName: "Clove", dose: "60 g" },
    { chineseName: "香附", pinyin: "Xiang Fu", englishName: "Cyperus", dose: "60 g" },
    { chineseName: "白术", pinyin: "Bai Zhu", englishName: "Atractylodes", dose: "60 g" },
    { chineseName: "诃子", pinyin: "He Zi", englishName: "Chebula Fruit", dose: "60 g" },
    { chineseName: "朱砂", pinyin: "Zhu Sha", englishName: "Cinnabar", dose: "60 g" },
    { chineseName: "荜茇", pinyin: "Bi Bo", englishName: "Long Pepper", dose: "60 g" },
    { chineseName: "乳香", pinyin: "Ru Xiang", englishName: "Frankincense", dose: "30 g" },
  ],
  ziXueDan: [
    { chineseName: "石膏", pinyin: "Shi Gao", englishName: "Gypsum", dose: "144 g" },
    { chineseName: "寒水石", pinyin: "Han Shui Shi", englishName: "Calcitum", dose: "144 g" },
    { chineseName: "滑石", pinyin: "Hua Shi", englishName: "Talcum", dose: "144 g" },
    { chineseName: "磁石", pinyin: "Ci Shi", englishName: "Magnetite", dose: "144 g" },
    { chineseName: "羚羊角", pinyin: "Ling Yang Jiao", englishName: "Antelope Horn", dose: "15 g" },
    { chineseName: "木香", pinyin: "Mu Xiang", englishName: "Aucklandia", dose: "15 g" },
    { chineseName: "沉香", pinyin: "Chen Xiang", englishName: "Aquilaria", dose: "15 g" },
    { chineseName: "玄参", pinyin: "Xuan Shen", englishName: "Scrophularia Root", dose: "48 g" },
    { chineseName: "升麻", pinyin: "Sheng Ma", englishName: "Cimicifuga", dose: "48 g" },
    { chineseName: "甘草", pinyin: "Gan Cao", englishName: "Licorice Root", dose: "24 g" },
    { chineseName: "丁香", pinyin: "Ding Xiang", englishName: "Clove", dose: "3 g" },
    { chineseName: "朴硝", pinyin: "Po Xiao", englishName: "Mirabilite", dose: "480 g" },
    { chineseName: "硝石", pinyin: "Xiao Shi", englishName: "Niter", dose: "96 g" },
    { chineseName: "麝香", pinyin: "She Xiang", englishName: "Musk", dose: "3 g" },
    { chineseName: "朱砂", pinyin: "Zhu Sha", englishName: "Cinnabar", dose: "9 g" },
    { chineseName: "黄金", pinyin: "Huang Jin", englishName: "Gold", dose: "100张" },
  ],
  siNiTang: [
    { chineseName: "附子", pinyin: "Fu Zi", englishName: "Aconite", dose: "15 g" },
    { chineseName: "干姜", pinyin: "Gan Jiang", englishName: "Dried Ginger", dose: "9 g" },
    { chineseName: "炙甘草", pinyin: "Zhi Gan Cao", englishName: "Honey-fried Licorice", dose: "6 g" },
  ],
  shengMaiSan: [
    { chineseName: "人参", pinyin: "Ren Shen", englishName: "Ginseng", dose: "9 g" },
    { chineseName: "麦冬", pinyin: "Mai Dong", englishName: "Ophiopogon Root", dose: "9 g" },
    { chineseName: "五味子", pinyin: "Wu Wei Zi", englishName: "Schisandra Fruit", dose: "6 g" },
  ],
  mengShiGunTanWan: [
    { chineseName: "礞石", pinyin: "Meng Shi", englishName: "Lapis Micae", dose: "30 g" },
    { chineseName: "大黄", pinyin: "Da Huang", englishName: "Rhubarb", dose: "240 g" },
    { chineseName: "黄芩", pinyin: "Huang Qin", englishName: "Scutellaria", dose: "240 g" },
    { chineseName: "沉香", pinyin: "Chen Xiang", englishName: "Aquilaria", dose: "15 g" },
  ],
  shunQiDaoTanTang: [
    { chineseName: "半夏", pinyin: "Ban Xia", englishName: "Pinellia", dose: "6 g" },
    { chineseName: "南星", pinyin: "Nan Xing", englishName: "Arisaema", dose: "3 g" },
    { chineseName: "橘红", pinyin: "Ju Hong", englishName: "Red Tangerine Peel", dose: "3 g" },
    { chineseName: "枳实", pinyin: "Zhi Shi", englishName: "Immature Bitter Orange", dose: "3 g" },
    { chineseName: "赤茯苓", pinyin: "Chi Fu Ling", englishName: "Red Poria", dose: "3 g" },
    { chineseName: "甘草", pinyin: "Gan Cao", englishName: "Licorice Root", dose: "1.5 g" },
    { chineseName: "生姜", pinyin: "Sheng Jiang", englishName: "Fresh Ginger", dose: "5片" },
  ],
  diTanTang: [
    { chineseName: "半夏", pinyin: "Ban Xia", englishName: "Pinellia", dose: "6 g" },
    { chineseName: "胆南星", pinyin: "Dan Nan Xing", englishName: "Arisaema with Bile", dose: "3 g" },
    { chineseName: "橘红", pinyin: "Ju Hong", englishName: "Red Tangerine Peel", dose: "4.5 g" },
    { chineseName: "枳实", pinyin: "Zhi Shi", englishName: "Immature Bitter Orange", dose: "4.5 g" },
    { chineseName: "茯苓", pinyin: "Fu Ling", englishName: "Poria", dose: "4.5 g" },
    { chineseName: "人参", pinyin: "Ren Shen", englishName: "Ginseng", dose: "3 g" },
    { chineseName: "石菖蒲", pinyin: "Shi Chang Pu", englishName: "Acorus", dose: "3 g" },
    { chineseName: "竹茹", pinyin: "Zhu Ru", englishName: "Bamboo Shavings", dose: "3 g" },
    { chineseName: "甘草", pinyin: "Gan Cao", englishName: "Licorice Root", dose: "1.5 g" },
    { chineseName: "生姜", pinyin: "Sheng Jiang", englishName: "Fresh Ginger", dose: "5片" },
  ],
  zhenGanXiFengTang: [
    { chineseName: "怀牛膝", pinyin: "Huai Niu Xi", englishName: "Achyranthes Root", dose: "30 g" },
    { chineseName: "代赭石", pinyin: "Dai Zhe Shi", englishName: "Haematite", dose: "30 g" },
    { chineseName: "龙骨", pinyin: "Long Gu", englishName: "Dragon Bone", dose: "15 g" },
    { chineseName: "牡蛎", pinyin: "Mu Li", englishName: "Oyster Shell", dose: "15 g" },
    { chineseName: "龟板", pinyin: "Gui Ban", englishName: "Tortoise Shell", dose: "15 g" },
    { chineseName: "玄参", pinyin: "Xuan Shen", englishName: "Scrophularia Root", dose: "15 g" },
    { chineseName: "天冬", pinyin: "Tian Dong", englishName: "Asparagus Root", dose: "15 g" },
    { chineseName: "川楝子", pinyin: "Chuan Lian Zi", englishName: "Melia Fruit", dose: "6 g" },
    { chineseName: "生麦芽", pinyin: "Sheng Mai Ya", englishName: "Raw Barley Sprout", dose: "6 g" },
    { chineseName: "茵陈", pinyin: "Yin Chen", englishName: "Artemisia", dose: "6 g" },
    { chineseName: "甘草", pinyin: "Gan Cao", englishName: "Licorice Root", dose: "4.5 g" },
  ],
  buYangHuanWuTang: [
    { chineseName: "黄芪", pinyin: "Huang Qi", englishName: "Astragalus", dose: "120 g" },
    { chineseName: "当归尾", pinyin: "Dang Gui Wei", englishName: "Chinese Angelica Tail", dose: "6 g" },
    { chineseName: "赤芍", pinyin: "Chi Shao", englishName: "Red Peony Root", dose: "4.5 g" },
    { chineseName: "地龙", pinyin: "Di Long", englishName: "Earthworm", dose: "3 g" },
    { chineseName: "川芎", pinyin: "Chuan Xiong", englishName: "Sichuan Lovage", dose: "3 g" },
    { chineseName: "红花", pinyin: "Hong Hua", englishName: "Safflower", dose: "3 g" },
    { chineseName: "桃仁", pinyin: "Tao Ren", englishName: "Peach Kernel", dose: "3 g" },
  ],
} satisfies Record<string, FormulaDetail["ingredients"]>;

heartIngredients.longDanXieGanTangHeDingXianWan = [
  ...heartIngredients.longDanXieGanTang,
  ...heartIngredients.dingXianWan,
];

const formulas = {
  xueFuZhuYuTang: {
    chineseName: "血府逐瘀汤",
    pinyin: "Xue Fu Zhu Yu Tang",
    englishName: "Drive Out Stasis in the Mansion of Blood Decoction",
    actions: ["Moves Blood", "Unblocks chest Yang", "Regulates Qi and stops pain"],
    indications: "Chest oppression or stabbing chest pain with fixed location, dark lips, purple tongue, and choppy pulse.",
    ingredients: heartIngredients.xueFuZhuYuTang,
  },
  guaLouXieBaiBanXiaTang: {
    chineseName: "瓜蒌薤白半夏汤",
    pinyin: "Gua Lou Xie Bai Ban Xia Tang",
    englishName: "Trichosanthes, Chinese Chive, and Pinellia Decoction",
    actions: ["Opens chest Yang", "Transforms Phlegm", "Descends rebellious Qi"],
    indications: "Chest Bi with turbid Phlegm, chest oppression, heavy body, nausea, sputum, and slippery pulse.",
    ingredients: heartIngredients.guaLouXieBaiBanXiaTang,
  },
  zhiShiXieBaiGuiZhiTang: {
    chineseName: "枳实薤白桂枝汤",
    pinyin: "Zhi Shi Xie Bai Gui Zhi Tang",
    actions: ["Warms and opens chest Yang", "Moves Qi", "Dispels Cold accumulation"],
    indications: "Cold stagnation chest Bi with severe chest pain, cold sensation, aversion to cold, and tight pulse.",
    ingredients: heartIngredients.zhiShiXieBaiGuiZhiTang,
  },
  tianWangBuXinDan: {
    chineseName: "天王补心丹",
    pinyin: "Tian Wang Bu Xin Dan",
    englishName: "Emperor of Heaven's Special Pill to Tonify the Heart",
    actions: ["Nourishes Heart Yin and Blood", "Clears empty Heat", "Calms Shen"],
    indications: "Insomnia, palpitations, anxiety, dry mouth, night sweating, red tongue, and thin rapid pulse.",
    ingredients: heartIngredients.tianWangBuXinDan,
  },
  guiPiTang: {
    chineseName: "归脾汤",
    pinyin: "Gui Pi Tang",
    englishName: "Restore the Spleen Decoction",
    actions: ["Tonifies Qi and Blood", "Strengthens Spleen", "Nourishes Heart and calms Shen"],
    indications: "Insomnia, palpitations, poor memory, fatigue, poor appetite, loose stool, and pale tongue.",
    ingredients: heartIngredients.guiPiTang,
  },
  anShenDingZhiWan: {
    chineseName: "安神定志丸",
    pinyin: "An Shen Ding Zhi Wan",
    englishName: "Calm the Spirit and Settle the Will Pill",
    actions: ["Tonifies Heart and Gallbladder Qi", "Calms Shen", "Settles fright"],
    indications: "Palpitations, insomnia, timidity, easy fright, anxiety, and weak pulse.",
    ingredients: heartIngredients.anShenDingZhiWan,
  },
  huangLianEJiaoTang: {
    chineseName: "黄连阿胶汤",
    pinyin: "Huang Lian E Jiao Tang",
    actions: ["Clears Heart Fire", "Nourishes Kidney Yin", "Harmonizes Heart and Kidney"],
    indications: "Insomnia with irritability, vexing Heat, dry throat, red tongue, and rapid pulse.",
    ingredients: heartIngredients.huangLianEJiaoTang,
  },
  wenDanTang: {
    chineseName: "温胆汤",
    pinyin: "Wen Dan Tang",
    englishName: "Warm the Gallbladder Decoction",
    actions: ["Clears Phlegm-Heat", "Harmonizes Stomach/Gallbladder", "Calms Shen"],
    indications: "Insomnia, palpitations, anxiety, nausea, bitter taste, dizziness, and greasy yellow coat.",
    ingredients: heartIngredients.wenDanTang,
  },
  longDanXieGanTang: {
    chineseName: "龙胆泻肝汤",
    pinyin: "Long Dan Xie Gan Tang",
    englishName: "Gentiana Decoction to Drain the Liver",
    actions: ["Drains Liver/Gallbladder Fire", "Clears Damp-Heat", "Calms agitation"],
    indications: "Irritability, insomnia, headache, bitter taste, red eyes, red tongue, and wiry rapid pulse.",
    ingredients: heartIngredients.longDanXieGanTang,
  },
  daoChiSan: {
    chineseName: "导赤散",
    pinyin: "Dao Chi San",
    englishName: "Guide Out the Red Powder",
    actions: ["Clears Heart Fire", "Promotes urination", "Relieves irritability"],
    indications: "Heart Fire with insomnia, mouth/tongue ulcers, thirst, dark urine, and red tongue tip.",
    ingredients: heartIngredients.daoChiSan,
  },
  banXiaHouPoTang: {
    chineseName: "半夏厚朴汤",
    pinyin: "Ban Xia Hou Po Tang",
    actions: ["Moves Qi", "Resolves Phlegm", "Relieves constraint in throat/chest"],
    indications: "Depression with plum-pit Qi, chest oppression, sighing, nausea, and wiry slippery pulse.",
    ingredients: heartIngredients.banXiaHouPoTang,
  },
  chaiHuShuGanSan: {
    chineseName: "柴胡疏肝散",
    pinyin: "Chai Hu Shu Gan San",
    actions: ["Spreads Liver Qi", "Moves constraint", "Stops pain"],
    indications: "Depression with emotional constraint, sighing, hypochondriac distention, and wiry pulse.",
    ingredients: heartIngredients.chaiHuShuGanSan,
  },
  danZhiXiaoYaoSan: {
    chineseName: "丹栀逍遥散",
    pinyin: "Dan Zhi Xiao Yao San",
    actions: ["Spreads Liver Qi", "Clears constrained Heat", "Nourishes Blood"],
    indications: "Depression with irritability, heat sensations, bitter taste, red eyes, and wiry rapid pulse.",
    ingredients: heartIngredients.danZhiXiaoYaoSan,
  },
  ganMaiDaZaoTang: {
    chineseName: "甘麦大枣汤",
    pinyin: "Gan Mai Da Zao Tang",
    actions: ["Nourishes Heart", "Calms Shen", "Harmonizes middle burner"],
    indications: "Restlessness, sadness, crying spells, insomnia, and emotional sensitivity from Heart Yin/Blood deficiency.",
    ingredients: heartIngredients.ganMaiDaZaoTang,
  },
  dingXianWan: {
    chineseName: "定痫丸",
    pinyin: "Ding Xian Wan",
    actions: ["Extinguishes Wind", "Transforms Phlegm", "Opens orifices and calms seizures"],
    indications: "Epilepsy with sudden collapse, convulsions, frothy sputum, rattling in throat, and post-ictal confusion.",
    ingredients: heartIngredients.dingXianWan,
  },
  longDanXieGanTangHeDingXianWan: {
    chineseName: "龙胆泻肝汤合定痫丸",
    pinyin: "Long Dan Xie Gan Tang He Ding Xian Wan",
    actions: ["Clears Liver Fire", "Transforms Phlegm", "Extinguishes Wind"],
    indications: "Epilepsy with Phlegm-Fire, violent convulsions, red face, irritability, constipation, and yellow greasy coat.",
    ingredients: heartIngredients.longDanXieGanTangHeDingXianWan,
  },
  zuoGuiWan: {
    chineseName: "左归丸",
    pinyin: "Zuo Gui Wan",
    englishName: "Restore the Left Kidney Pill",
    actions: ["Nourishes Kidney Yin", "Enriches Essence", "Subdues empty Heat"],
    indications: "Deficiency with dizziness, tinnitus, weak low back/knees, night sweating, and red tongue.",
    ingredients: heartIngredients.zuoGuiWan,
  },
  liuJunZiTang: {
    chineseName: "六君子汤",
    pinyin: "Liu Jun Zi Tang",
    englishName: "Six Gentlemen Decoction",
    actions: ["Tonifies Spleen Qi", "Transforms Phlegm", "Supports source Qi"],
    indications: "Phlegm with Spleen Qi deficiency, fatigue, poor appetite, loose stool, and weak pulse.",
    ingredients: heartIngredients.liuJunZiTang,
  },
  suHeXiangWan: {
    chineseName: "苏合香丸",
    pinyin: "Su He Xiang Wan",
    actions: ["Warms and opens orifices", "Moves Qi", "Revives consciousness"],
    indications: "Closed collapse from Cold/Phlegm with sudden loss of consciousness, clenched jaw, and cold limbs.",
    ingredients: heartIngredients.suHeXiangWan,
  },
  ziXueDan: {
    chineseName: "紫雪丹",
    pinyin: "Zi Xue Dan",
    actions: ["Clears Heat", "Opens orifices", "Extinguishes Wind"],
    indications: "Heat entering pericardium with high fever, delirium, convulsion, and closed orifices.",
    ingredients: heartIngredients.ziXueDan,
  },
  siNiTang: {
    chineseName: "四逆汤",
    pinyin: "Si Ni Tang",
    actions: ["Restores devastated Yang", "Warms interior", "Rescues collapse"],
    indications: "Yang collapse with cold limbs, faint pulse, profuse sweating, and loss of consciousness.",
    ingredients: heartIngredients.siNiTang,
  },
  shengMaiSan: {
    chineseName: "生脉散",
    pinyin: "Sheng Mai San",
    actions: ["Augments Qi", "Nourishes Yin", "Prevents collapse"],
    indications: "Qi-Yin collapse or deficient syncope with sweating, shortness of breath, dry mouth, and weak pulse.",
    ingredients: heartIngredients.shengMaiSan,
  },
  mengShiGunTanWan: {
    chineseName: "礞石滚痰丸",
    pinyin: "Meng Shi Gun Tan Wan",
    actions: ["Drives out Phlegm-Fire", "Clears constraint", "Calms mania"],
    indications: "Mania with agitation, shouting, violence, insomnia, constipation, thick yellow coat, and slippery rapid pulse.",
    ingredients: heartIngredients.mengShiGunTanWan,
  },
  shunQiDaoTanTang: {
    chineseName: "顺气导痰汤",
    pinyin: "Shun Qi Dao Tan Tang",
    actions: ["Moves Qi", "Transforms Phlegm", "Opens constraint"],
    indications: "Depressive psychosis with dull affect, muttering, chest oppression, phlegm, and greasy coat.",
    ingredients: heartIngredients.shunQiDaoTanTang,
  },
  diTanTang: {
    chineseName: "涤痰汤",
    pinyin: "Di Tan Tang",
    actions: ["Scours Phlegm", "Opens orifices", "Calms Shen"],
    indications: "Mental confusion, mania or withdrawal with Phlegm obstruction, clouded spirit, and greasy coat.",
    ingredients: heartIngredients.diTanTang,
  },
  zhenGanXiFengTang: {
    chineseName: "镇肝熄风汤",
    pinyin: "Zhen Gan Xi Feng Tang",
    actions: ["Subdues Liver Yang", "Extinguishes Wind", "Nourishes Yin"],
    indications: "Wind stroke tendency with dizziness, headache, numbness, tremor, and wiry forceful pulse.",
    ingredients: heartIngredients.zhenGanXiFengTang,
  },
  buYangHuanWuTang: {
    chineseName: "补阳还五汤",
    pinyin: "Bu Yang Huan Wu Tang",
    actions: ["Tonifies Qi", "Moves Blood", "Unblocks channels"],
    indications: "Post-stroke hemiplegia, facial droop, speech difficulty, weak limbs, and Qi deficiency with Blood stasis.",
    ingredients: heartIngredients.buYangHuanWuTang,
  },
} satisfies Record<string, FormulaDetail>;

export const heartContent: Record<number, LungConditionDetail> = {
  5: {
    overview: "Chest Impediment (Xiong Bi) covers obstruction of Heart/chest Yang by Qi stagnation, Blood stasis, Phlegm, Cold, or deficiency. It often overlaps clinically with angina-like chest pain.",
    redFlags: ["Acute or crushing chest pain", "Pain radiating to arm, jaw, or back", "Shortness of breath, sweating, nausea, fainting", "New chest pain with cardiac risk factors"],
    tcmNotes: ["Differentiate excess obstruction from underlying deficiency.", "Chest pain red flags require urgent biomedical evaluation before routine acupuncture care."],
    patterns: [
      { name: "Stagnation of Qi in the Chest", principle: "Regulate Qi, open the chest, relieve pain.", points: "PC 6, CV 17, BL 14, BL 15, LR 3, SP 4.", formula: formulas.chaiHuShuGanSan },
      { name: "Heart Blood Stasis", principle: "Move Blood, transform stasis, open the chest, stop pain.", points: "PC 6, PC 4, BL 14, BL 15, BL 17, SP 10, CV 17.", formula: formulas.xueFuZhuYuTang },
      { name: "Turbid Phlegm Stagnating in the Chest", principle: "Transform Phlegm, open chest Yang, regulate Qi.", points: "PC 6, ST 40, CV 17, CV 12, BL 20, SP 9.", formula: formulas.guaLouXieBaiBanXiaTang },
      { name: "Cold Stagnation in the Chest", principle: "Warm Yang, scatter Cold, open the chest, stop pain.", points: "PC 6, CV 17, CV 6, GV 4, BL 15, BL 23. Use moxa.", formula: formulas.zhiShiXieBaiGuiZhiTang },
      { name: "Heart-Kidney Yin Deficiency", principle: "Nourish Heart and Kidney Yin, clear empty Heat, calm Shen.", points: "HT 7, KI 3, KI 6, SP 6, BL 15, BL 23.", formula: formulas.tianWangBuXinDan },
      { name: "Qi and Yin Deficiency", principle: "Tonify Qi, nourish Yin, support Heart Qi, calm Shen.", points: "PC 6, HT 7, CV 6, ST 36, SP 6, BL 15.", formula: formulas.shengMaiSan },
      { name: "Spleen-Kidney Yang Qi Deficiency", principle: "Warm Yang, tonify Spleen and Kidney, support Heart Yang.", points: "CV 4, CV 6, GV 4, BL 20, BL 23, ST 36. Use moxa.", formula: formulas.siNiTang },
    ],
  },
  10: {
    overview: "Convulsive Syndromes (Jing Zheng) involve spasms, rigidity, tremors, or convulsions due to Wind, Heat, Phlegm, toxin, or deficiency of Yin and Blood.",
    redFlags: ["First seizure", "Convulsion lasting more than 5 minutes", "Repeated seizures without recovery", "Fever with stiff neck", "Pregnancy, head trauma, or altered consciousness"],
    patterns: [
      { name: "Obstruction of Channels and Collaterals by Evils", principle: "Expel pathogen, unblock channels, extinguish Wind, stop spasm.", points: "GV 14, GB 20, LI 4, LR 3, ST 40, SP 6.", formula: formulas.dingXianWan },
      { name: "Liver Wind Stirring from Exuberant Heat", principle: "Clear Heat, extinguish Wind, open orifices, stop convulsions.", points: "GV 20, GV 26, GV 14, LI 11, LR 2, LR 3, PC 8, 12 Jing-well points.", formula: formulas.ziXueDan },
      { name: "Depletion of Yin and Blood", principle: "Nourish Yin and Blood, soften Liver, extinguish Wind.", points: "LR 3, SP 6, KI 3, BL 18, BL 23, HT 7, GB 39.", formula: formulas.zuoGuiWan },
    ],
  },
  12: {
    overview: "Depression (Yu Zheng) is emotional constraint with impaired free coursing of Qi. Long-term constraint may transform into Fire, Phlegm, Blood stasis, or deficiency.",
    tcmNotes: ["Assess safety whenever depression includes hopelessness, self-harm thoughts, or severe functional impairment."],
    redFlags: ["Suicidal ideation or self-harm", "Psychosis", "Severe inability to eat, sleep, or function"],
    patterns: [
      { name: "Liver Qi Stagnation", principle: "Soothe Liver, regulate Qi, resolve constraint.", points: "LR 3, PC 6, CV 17, SP 4, GB 34, Yintang.", formula: formulas.chaiHuShuGanSan },
      { name: "Static Qi Transforming into Fire", principle: "Soothe Liver, clear constrained Fire, calm Shen.", points: "LR 2, LR 3, GB 34, HT 7, PC 6, GV 24.", formula: formulas.danZhiXiaoYaoSan },
      { name: "Static Qi and Phlegm Obstruction", principle: "Move Qi, transform Phlegm, open constraint, calm Shen.", points: "PC 6, CV 17, ST 40, CV 22, LR 3, Yintang.", formula: formulas.banXiaHouPoTang },
      { name: "Yin and Blood Deficiency", principle: "Nourish Yin and Blood, calm Shen, soften Liver.", points: "HT 7, SP 6, BL 15, BL 17, BL 20, KI 3, LR 3.", formula: formulas.ganMaiDaZaoTang },
    ],
  },
  20: {
    overview: "Epilepsy (Xian Zheng) is recurrent sudden collapse, loss of consciousness, convulsion, or abnormal sensory/motor episodes, often involving Wind, Phlegm, Fire, and deficiency.",
    redFlags: ["New seizure", "Status epilepticus", "Seizure after head injury", "Pregnancy", "Fever, stiff neck, or persistent confusion"],
    patterns: [
      { name: "Wind-Phlegm Obstruction", principle: "Extinguish Wind, transform Phlegm, open orifices, calm Shen.", points: "GV 20, GV 26, PC 6, ST 40, LR 3, Yintang, HT 7.", formula: formulas.dingXianWan },
      { name: "Internal Profusion of Phlegm-Fire", principle: "Clear Fire, transform Phlegm, extinguish Wind, open orifices.", points: "GV 14, GV 26, PC 8, PC 7, ST 40, LR 2, LI 11, 12 Jing-well points.", formula: formulas.longDanXieGanTangHeDingXianWan },
      { name: "Liver-Kidney Yin Deficiency", principle: "Nourish Liver and Kidney Yin, extinguish Wind, calm Shen.", points: "KI 3, SP 6, LR 3, BL 18, BL 23, HT 7, GB 39.", formula: formulas.zuoGuiWan },
      { name: "Spleen-Stomach Qi Deficiency", principle: "Tonify Spleen and Stomach Qi, transform Phlegm, calm Shen.", points: "ST 36, CV 12, BL 20, BL 21, SP 6, ST 40, HT 7.", formula: formulas.liuJunZiTang },
    ],
  },
  21: {
    overview: "Fainting (Jue Zheng) is sudden loss of consciousness due to reversal or collapse of Qi, Blood, Phlegm, food, Heat, or deficiency.",
    redFlags: ["Chest pain, palpitations, or shortness of breath before fainting", "Syncope during exertion", "Neurologic deficit", "Pregnancy", "Repeated unexplained fainting"],
    patterns: [
      { name: "Excess Qi Syncope", principle: "Move Qi, open orifices, restore consciousness.", points: "GV 26, PC 6, LR 3, LI 4, CV 17.", formula: formulas.suHeXiangWan },
      { name: "Deficient Qi Syncope", principle: "Tonify Qi, rescue collapse, restore consciousness.", points: "GV 20, CV 6, ST 36, PC 6, KI 1. Use moxa if cold.", formula: formulas.shengMaiSan },
      { name: "Excess Blood Syncope", principle: "Move Blood, open orifices, regulate Qi.", points: "GV 26, PC 6, BL 17, SP 10, LR 3.", formula: formulas.xueFuZhuYuTang },
      { name: "Deficient Blood Syncope", principle: "Tonify Qi and Blood, calm Shen, restore consciousness.", points: "GV 20, ST 36, SP 6, BL 17, BL 20, HT 7.", formula: formulas.guiPiTang },
      { name: "Phlegm Syncope", principle: "Transform Phlegm, open orifices, descend turbid Qi.", points: "GV 26, PC 6, ST 40, CV 12, CV 22.", formula: formulas.diTanTang },
      { name: "Food Syncope", principle: "Harmonize Stomach, reduce food stagnation, regulate Qi.", points: "CV 12, ST 36, ST 40, SP 4, PC 6.", formula: formulas.banXiaHouPoTang },
      { name: "Summer-Heat Syncope", principle: "Clear Summer-Heat, open orifices, restore consciousness.", points: "GV 26, PC 9, LI 11, GV 14, KI 1, 12 Jing-well points.", formula: formulas.ziXueDan },
    ],
  },
  28: {
    overview: "Insomnia (Bu Mei) includes difficulty falling asleep, frequent waking, dream-disturbed sleep, or inability to return to sleep due to disturbance of Shen.",
    patterns: [
      { name: "Liver Fire Blazing", principle: "Drain Liver Fire, calm Shen, settle Hun.", points: "LR 2, LR 3, GB 20, HT 7, PC 6, GV 24.", formula: formulas.longDanXieGanTang },
      { name: "Heart Fire Blazing", principle: "Clear Heart Fire, calm Shen, promote sleep.", points: "HT 8, HT 7, PC 7, KI 6, SP 6, Yintang.", formula: formulas.daoChiSan },
      { name: "Phlegm-Fire Harassing the Mind", principle: "Clear Phlegm-Fire, harmonize middle, calm Shen.", points: "ST 40, PC 7, PC 6, CV 12, HT 7, Yintang.", formula: formulas.wenDanTang },
      { name: "Residual Heat in the Diaphragm", principle: "Clear residual Heat, harmonize Stomach, calm Shen.", points: "PC 6, CV 12, ST 44, LI 11, HT 7.", formula: formulas.wenDanTang },
      { name: "Heart-Spleen Deficiency", principle: "Tonify Heart and Spleen, nourish Blood, calm Shen.", points: "HT 7, BL 15, BL 20, ST 36, SP 6, GV 20.", formula: formulas.guiPiTang },
      { name: "Heart Yin Deficiency", principle: "Nourish Heart Yin, clear empty Heat, calm Shen.", points: "HT 7, HT 6, KI 6, SP 6, BL 15, Yintang.", formula: formulas.tianWangBuXinDan },
      { name: "Heart-Kidney Disharmony", principle: "Nourish Kidney Yin, clear Heart Fire, harmonize Heart and Kidney.", points: "HT 7, KI 3, KI 6, SP 6, CV 4, Yintang.", formula: formulas.huangLianEJiaoTang },
      { name: "Heart-Gallbladder Deficiency", principle: "Tonify Heart and Gallbladder Qi, calm Shen, settle fright.", points: "HT 7, PC 6, GB 13, GB 20, BL 15, BL 19.", formula: formulas.anShenDingZhiWan },
      { name: "Liver Yin Deficiency", principle: "Nourish Liver Yin, soften Liver, calm Shen.", points: "LR 3, KI 3, SP 6, BL 18, HT 7, Yintang.", formula: formulas.zuoGuiWan },
    ],
  },
  35: {
    overview: "Mania / Manic-Depressive Disorder (Dian Kuang) includes withdrawal, dullness, muttering, agitation, shouting, violence, or disturbed perception from Phlegm, Fire, Qi constraint, and deficiency.",
    redFlags: ["Risk of harm to self or others", "Psychosis", "Severe agitation, no sleep, or inability to care for self"],
    patterns: [
      { name: "Depressive Psychotic Pattern: Binding Depression of Qi and Phlegm", principle: "Move Qi, transform Phlegm, open constraint, calm Shen.", points: "PC 6, ST 40, CV 17, CV 12, HT 7, Yintang.", formula: formulas.shunQiDaoTanTang },
      { name: "Depressive Psychotic Pattern: Heart-Spleen Deficiency", principle: "Tonify Heart and Spleen, nourish Blood, calm Shen.", points: "HT 7, BL 15, BL 20, ST 36, SP 6, GV 20.", formula: formulas.guiPiTang },
      { name: "Manic Psychotic Pattern: Phlegm-Fire Harassing Interior", principle: "Clear Fire, transform Phlegm, open orifices, calm Shen.", points: "GV 26, PC 8, PC 7, ST 40, LI 11, LR 2, HT 8.", formula: formulas.mengShiGunTanWan },
      { name: "Manic Psychotic Pattern: Exuberant Fire with Injury to Yin", principle: "Clear Fire, nourish Yin, calm Shen.", points: "HT 7, HT 8, KI 3, KI 6, SP 6, LR 2, PC 7.", formula: formulas.tianWangBuXinDan },
    ],
  },
  36: {
    overview: "Palpitation (Xin Ji) includes subjective abnormal heartbeat, fright palpitations, or persistent palpitations due to deficiency, Fire, Phlegm-Fluid, Water, or Blood stasis disturbing the Heart.",
    redFlags: ["Chest pain", "Fainting", "Severe shortness of breath", "New irregular heartbeat", "Palpitations with dizziness or neurologic symptoms"],
    patterns: [
      { name: "Heart-Gallbladder Qi Deficiency Disturbing the Mind", principle: "Tonify Heart and Gallbladder Qi, calm Shen, settle fright.", points: "HT 7, PC 6, BL 15, GB 13, ST 36, GV 20.", formula: formulas.anShenDingZhiWan },
      { name: "Qi and Heart Blood Insufficiency", principle: "Tonify Qi, nourish Heart Blood, calm Shen.", points: "HT 7, BL 15, BL 17, ST 36, SP 6, CV 6.", formula: formulas.guiPiTang },
      { name: "Heart Fire Hyperactivity from Heart-Kidney Disharmony", principle: "Clear Heart Fire, nourish Kidney Yin, calm Shen.", points: "HT 8, HT 7, KI 3, KI 6, SP 6, PC 7.", formula: formulas.huangLianEJiaoTang },
      { name: "Heart Yang Deficiency", principle: "Warm and tonify Heart Yang, calm palpitations.", points: "CV 17, CV 6, BL 15, BL 23, GV 4, PC 6. Use moxa.", formula: formulas.siNiTang },
      { name: "Heart Oppressed by Water and Phlegm-Fluid", principle: "Warm Yang, transform fluids, resolve Phlegm, calm Heart.", points: "PC 6, ST 40, CV 12, CV 9, BL 20, BL 23, CV 6.", formula: formulas.wenDanTang },
      { name: "Heart Obstructed by Blood Stasis", principle: "Move Blood, unblock Heart vessels, calm palpitations.", points: "PC 6, PC 4, BL 14, BL 15, BL 17, SP 10.", formula: formulas.xueFuZhuYuTang },
    ],
  },
  47: {
    overview: "Wind Stroke (Zhong Feng) includes sudden collapse, hemiplegia, facial deviation, speech difficulty, or sequelae after stroke. Emergency signs require immediate medical care.",
    redFlags: ["Face drooping, arm weakness, speech difficulty", "Sudden severe headache", "Sudden vision loss, confusion, or trouble walking", "Any suspected acute stroke"],
    tcmNotes: ["Acute stroke is emergency care first. Acupuncture reference content is mainly for stabilized or rehabilitative care unless explicitly trained for emergency protocols."],
    patterns: [
      { name: "Attack of Channels and Collaterals", principle: "Unblock channels, move Qi and Blood, extinguish Wind.", points: "GV 20, GB 20, LI 4, LI 11, ST 36, ST 40, LR 3, GB 34.", formula: formulas.buYangHuanWuTang },
      { name: "Attack of Internal Organs: Tense Type", principle: "Clear Heat, extinguish Wind, open orifices, transform Phlegm.", points: "GV 26, PC 6, PC 8, LR 2, ST 40, LI 11, 12 Jing-well points.", formula: formulas.ziXueDan },
      { name: "Attack of Internal Organs: Flaccid Type", principle: "Rescue Yang, restore consciousness, secure collapse.", points: "CV 4, CV 6, GV 20, ST 36, KI 1. Use moxa.", formula: formulas.siNiTang },
      { name: "Sequelae: Wind-Phlegm", principle: "Extinguish Wind, transform Phlegm, unblock channels.", points: "GB 20, GV 20, ST 40, LI 11, GB 34, LR 3.", formula: formulas.diTanTang },
      { name: "Damp-Phlegm", principle: "Resolve Damp-Phlegm, strengthen Spleen, unblock channels.", points: "ST 40, SP 9, ST 36, BL 20, GB 34, LI 11.", formula: formulas.liuJunZiTang },
      { name: "Qi and Blood Stagnation", principle: "Tonify Qi, move Blood, unblock channels.", points: "ST 36, SP 6, BL 17, LI 11, GB 34, LR 3.", formula: formulas.buYangHuanWuTang },
      { name: "Yin Deficiency with Empty Heat", principle: "Nourish Yin, clear empty Heat, extinguish Wind.", points: "KI 3, SP 6, LR 3, BL 18, BL 23, GB 39.", formula: formulas.zhenGanXiFengTang },
    ],
  },
};
