import type { FormulaDetail, LungConditionDetail } from "./lungContent";

const formulas = {
  xueFuZhuYuTang: {
    chineseName: "血府逐瘀汤",
    pinyin: "Xue Fu Zhu Yu Tang",
    englishName: "Drive Out Stasis in the Mansion of Blood Decoction",
    actions: ["Moves Blood", "Unblocks chest Yang", "Regulates Qi and stops pain"],
    indications: "Chest oppression or stabbing chest pain with fixed location, dark lips, purple tongue, and choppy pulse.",
  },
  guaLouXieBaiBanXiaTang: {
    chineseName: "瓜蒌薤白半夏汤",
    pinyin: "Gua Lou Xie Bai Ban Xia Tang",
    englishName: "Trichosanthes, Chinese Chive, and Pinellia Decoction",
    actions: ["Opens chest Yang", "Transforms Phlegm", "Descends rebellious Qi"],
    indications: "Chest Bi with turbid Phlegm, chest oppression, heavy body, nausea, sputum, and slippery pulse.",
  },
  zhiShiXieBaiGuiZhiTang: {
    chineseName: "枳实薤白桂枝汤",
    pinyin: "Zhi Shi Xie Bai Gui Zhi Tang",
    actions: ["Warms and opens chest Yang", "Moves Qi", "Dispels Cold accumulation"],
    indications: "Cold stagnation chest Bi with severe chest pain, cold sensation, aversion to cold, and tight pulse.",
  },
  tianWangBuXinDan: {
    chineseName: "天王补心丹",
    pinyin: "Tian Wang Bu Xin Dan",
    englishName: "Emperor of Heaven's Special Pill to Tonify the Heart",
    actions: ["Nourishes Heart Yin and Blood", "Clears empty Heat", "Calms Shen"],
    indications: "Insomnia, palpitations, anxiety, dry mouth, night sweating, red tongue, and thin rapid pulse.",
  },
  guiPiTang: {
    chineseName: "归脾汤",
    pinyin: "Gui Pi Tang",
    englishName: "Restore the Spleen Decoction",
    actions: ["Tonifies Qi and Blood", "Strengthens Spleen", "Nourishes Heart and calms Shen"],
    indications: "Insomnia, palpitations, poor memory, fatigue, poor appetite, loose stool, and pale tongue.",
  },
  anShenDingZhiWan: {
    chineseName: "安神定志丸",
    pinyin: "An Shen Ding Zhi Wan",
    englishName: "Calm the Spirit and Settle the Will Pill",
    actions: ["Tonifies Heart and Gallbladder Qi", "Calms Shen", "Settles fright"],
    indications: "Palpitations, insomnia, timidity, easy fright, anxiety, and weak pulse.",
  },
  huangLianEJiaoTang: {
    chineseName: "黄连阿胶汤",
    pinyin: "Huang Lian E Jiao Tang",
    actions: ["Clears Heart Fire", "Nourishes Kidney Yin", "Harmonizes Heart and Kidney"],
    indications: "Insomnia with irritability, vexing Heat, dry throat, red tongue, and rapid pulse.",
  },
  wenDanTang: {
    chineseName: "温胆汤",
    pinyin: "Wen Dan Tang",
    englishName: "Warm the Gallbladder Decoction",
    actions: ["Clears Phlegm-Heat", "Harmonizes Stomach/Gallbladder", "Calms Shen"],
    indications: "Insomnia, palpitations, anxiety, nausea, bitter taste, dizziness, and greasy yellow coat.",
  },
  longDanXieGanTang: {
    chineseName: "龙胆泻肝汤",
    pinyin: "Long Dan Xie Gan Tang",
    englishName: "Gentiana Decoction to Drain the Liver",
    actions: ["Drains Liver/Gallbladder Fire", "Clears Damp-Heat", "Calms agitation"],
    indications: "Irritability, insomnia, headache, bitter taste, red eyes, red tongue, and wiry rapid pulse.",
  },
  daoChiSan: {
    chineseName: "导赤散",
    pinyin: "Dao Chi San",
    englishName: "Guide Out the Red Powder",
    actions: ["Clears Heart Fire", "Promotes urination", "Relieves irritability"],
    indications: "Heart Fire with insomnia, mouth/tongue ulcers, thirst, dark urine, and red tongue tip.",
  },
  banXiaHouPoTang: {
    chineseName: "半夏厚朴汤",
    pinyin: "Ban Xia Hou Po Tang",
    actions: ["Moves Qi", "Resolves Phlegm", "Relieves constraint in throat/chest"],
    indications: "Depression with plum-pit Qi, chest oppression, sighing, nausea, and wiry slippery pulse.",
  },
  chaiHuShuGanSan: {
    chineseName: "柴胡疏肝散",
    pinyin: "Chai Hu Shu Gan San",
    actions: ["Spreads Liver Qi", "Moves constraint", "Stops pain"],
    indications: "Depression with emotional constraint, sighing, hypochondriac distention, and wiry pulse.",
  },
  danZhiXiaoYaoSan: {
    chineseName: "丹栀逍遥散",
    pinyin: "Dan Zhi Xiao Yao San",
    actions: ["Spreads Liver Qi", "Clears constrained Heat", "Nourishes Blood"],
    indications: "Depression with irritability, heat sensations, bitter taste, red eyes, and wiry rapid pulse.",
  },
  ganMaiDaZaoTang: {
    chineseName: "甘麦大枣汤",
    pinyin: "Gan Mai Da Zao Tang",
    actions: ["Nourishes Heart", "Calms Shen", "Harmonizes middle burner"],
    indications: "Restlessness, sadness, crying spells, insomnia, and emotional sensitivity from Heart Yin/Blood deficiency.",
  },
  dingXianWan: {
    chineseName: "定痫丸",
    pinyin: "Ding Xian Wan",
    actions: ["Extinguishes Wind", "Transforms Phlegm", "Opens orifices and calms seizures"],
    indications: "Epilepsy with sudden collapse, convulsions, frothy sputum, rattling in throat, and post-ictal confusion.",
  },
  longDanXieGanTangHeDingXianWan: {
    chineseName: "龙胆泻肝汤合定痫丸",
    pinyin: "Long Dan Xie Gan Tang He Ding Xian Wan",
    actions: ["Clears Liver Fire", "Transforms Phlegm", "Extinguishes Wind"],
    indications: "Epilepsy with Phlegm-Fire, violent convulsions, red face, irritability, constipation, and yellow greasy coat.",
  },
  zuoGuiWan: {
    chineseName: "左归丸",
    pinyin: "Zuo Gui Wan",
    englishName: "Restore the Left Kidney Pill",
    actions: ["Nourishes Kidney Yin", "Enriches Essence", "Subdues empty Heat"],
    indications: "Deficiency with dizziness, tinnitus, weak low back/knees, night sweating, and red tongue.",
  },
  liuJunZiTang: {
    chineseName: "六君子汤",
    pinyin: "Liu Jun Zi Tang",
    englishName: "Six Gentlemen Decoction",
    actions: ["Tonifies Spleen Qi", "Transforms Phlegm", "Supports source Qi"],
    indications: "Phlegm with Spleen Qi deficiency, fatigue, poor appetite, loose stool, and weak pulse.",
  },
  suHeXiangWan: {
    chineseName: "苏合香丸",
    pinyin: "Su He Xiang Wan",
    actions: ["Warms and opens orifices", "Moves Qi", "Revives consciousness"],
    indications: "Closed collapse from Cold/Phlegm with sudden loss of consciousness, clenched jaw, and cold limbs.",
  },
  ziXueDan: {
    chineseName: "紫雪丹",
    pinyin: "Zi Xue Dan",
    actions: ["Clears Heat", "Opens orifices", "Extinguishes Wind"],
    indications: "Heat entering pericardium with high fever, delirium, convulsion, and closed orifices.",
  },
  siNiTang: {
    chineseName: "四逆汤",
    pinyin: "Si Ni Tang",
    actions: ["Restores devastated Yang", "Warms interior", "Rescues collapse"],
    indications: "Yang collapse with cold limbs, faint pulse, profuse sweating, and loss of consciousness.",
  },
  shengMaiSan: {
    chineseName: "生脉散",
    pinyin: "Sheng Mai San",
    actions: ["Augments Qi", "Nourishes Yin", "Prevents collapse"],
    indications: "Qi-Yin collapse or deficient syncope with sweating, shortness of breath, dry mouth, and weak pulse.",
  },
  mengShiGunTanWan: {
    chineseName: "礞石滚痰丸",
    pinyin: "Meng Shi Gun Tan Wan",
    actions: ["Drives out Phlegm-Fire", "Clears constraint", "Calms mania"],
    indications: "Mania with agitation, shouting, violence, insomnia, constipation, thick yellow coat, and slippery rapid pulse.",
  },
  shunQiDaoTanTang: {
    chineseName: "顺气导痰汤",
    pinyin: "Shun Qi Dao Tan Tang",
    actions: ["Moves Qi", "Transforms Phlegm", "Opens constraint"],
    indications: "Depressive psychosis with dull affect, muttering, chest oppression, phlegm, and greasy coat.",
  },
  diTanTang: {
    chineseName: "涤痰汤",
    pinyin: "Di Tan Tang",
    actions: ["Scours Phlegm", "Opens orifices", "Calms Shen"],
    indications: "Mental confusion, mania or withdrawal with Phlegm obstruction, clouded spirit, and greasy coat.",
  },
  zhenGanXiFengTang: {
    chineseName: "镇肝熄风汤",
    pinyin: "Zhen Gan Xi Feng Tang",
    actions: ["Subdues Liver Yang", "Extinguishes Wind", "Nourishes Yin"],
    indications: "Wind stroke tendency with dizziness, headache, numbness, tremor, and wiry forceful pulse.",
  },
  buYangHuanWuTang: {
    chineseName: "补阳还五汤",
    pinyin: "Bu Yang Huan Wu Tang",
    actions: ["Tonifies Qi", "Moves Blood", "Unblocks channels"],
    indications: "Post-stroke hemiplegia, facial droop, speech difficulty, weak limbs, and Qi deficiency with Blood stasis.",
  },
} satisfies Record<string, FormulaDetail>;

export const heartContent: Record<number, LungConditionDetail> = {
  5: {
    overview: "Chest Impediment (Xiong Bi) covers obstruction of Heart/chest Yang by Qi stagnation, Blood stasis, Phlegm, Cold, or deficiency. It often overlaps clinically with angina-like chest pain.",
    redFlags: ["Acute or crushing chest pain", "Pain radiating to arm, jaw, or back", "Shortness of breath, sweating, nausea, fainting", "New chest pain with cardiac risk factors"],
    tcmNotes: ["Differentiate excess obstruction from underlying deficiency.", "Chest pain red flags require urgent biomedical evaluation before routine acupuncture care."],
    patterns: [
      { name: "Stagnation of Qi in the Chest", principle: "Regulate Qi, open the chest, relieve pain.", points: "PC 6, CV 17, BL 14, BL 15, LR 3, SP 4.", formula: formulas.chaiHuShuGanSan },
      { name: "Heart Blood Stasis", principle: "Move Blood, transform stasis, open the chest, stop pain.", points: "PC 6, PC 4, BL 14, BL 15, BL 17, SP 10, CV 17.", formula: formulas.xueFuZhuYuTang },
      { name: "Turbid Phlegm Stagnating in the Chest", principle: "Transform Phlegm, open chest Yang, regulate Qi.", points: "PC 6, ST 40, CV 17, CV 12, BL 20, SP 9.", formula: formulas.guaLouXieBaiBanXiaTang },
      { name: "Cold Stagnation in the Chest", principle: "Warm Yang, scatter Cold, open the chest, stop pain.", points: "PC 6, CV 17, CV 6, GV 4, BL 15, BL 23. Use moxa.", formula: formulas.zhiShiXieBaiGuiZhiTang },
      { name: "Heart-Kidney Yin Deficiency", principle: "Nourish Heart and Kidney Yin, clear empty Heat, calm Shen.", points: "HT 7, KI 3, KI 6, SP 6, BL 15, BL 23.", formula: formulas.tianWangBuXinDan },
      { name: "Qi and Yin Deficiency", principle: "Tonify Qi, nourish Yin, support Heart Qi, calm Shen.", points: "PC 6, HT 7, CV 6, ST 36, SP 6, BL 15.", formula: formulas.shengMaiSan },
      { name: "Spleen-Kidney Yang Qi Deficiency", principle: "Warm Yang, tonify Spleen and Kidney, support Heart Yang.", points: "CV 4, CV 6, GV 4, BL 20, BL 23, ST 36. Use moxa.", formula: formulas.siNiTang },
    ],
  },
  10: {
    overview: "Convulsive Syndromes (Jing Zheng) involve spasms, rigidity, tremors, or convulsions due to Wind, Heat, Phlegm, toxin, or deficiency of Yin and Blood.",
    redFlags: ["First seizure", "Convulsion lasting more than 5 minutes", "Repeated seizures without recovery", "Fever with stiff neck", "Pregnancy, head trauma, or altered consciousness"],
    patterns: [
      { name: "Obstruction of Channels and Collaterals by Evils", principle: "Expel pathogen, unblock channels, extinguish Wind, stop spasm.", points: "GV 14, GB 20, LI 4, LR 3, ST 40, SP 6.", formula: formulas.dingXianWan },
      { name: "Liver Wind Stirring from Exuberant Heat", principle: "Clear Heat, extinguish Wind, open orifices, stop convulsions.", points: "GV 20, GV 26, GV 14, LI 11, LR 2, LR 3, PC 8, 12 Jing-well points.", formula: formulas.ziXueDan },
      { name: "Depletion of Yin and Blood", principle: "Nourish Yin and Blood, soften Liver, extinguish Wind.", points: "LR 3, SP 6, KI 3, BL 18, BL 23, HT 7, GB 39.", formula: formulas.zuoGuiWan },
    ],
  },
  12: {
    overview: "Depression (Yu Zheng) is emotional constraint with impaired free coursing of Qi. Long-term constraint may transform into Fire, Phlegm, Blood stasis, or deficiency.",
    tcmNotes: ["Assess safety whenever depression includes hopelessness, self-harm thoughts, or severe functional impairment."],
    redFlags: ["Suicidal ideation or self-harm", "Psychosis", "Severe inability to eat, sleep, or function"],
    patterns: [
      { name: "Liver Qi Stagnation", principle: "Soothe Liver, regulate Qi, resolve constraint.", points: "LR 3, PC 6, CV 17, SP 4, GB 34, Yintang.", formula: formulas.chaiHuShuGanSan },
      { name: "Static Qi Transforming into Fire", principle: "Soothe Liver, clear constrained Fire, calm Shen.", points: "LR 2, LR 3, GB 34, HT 7, PC 6, GV 24.", formula: formulas.danZhiXiaoYaoSan },
      { name: "Static Qi and Phlegm Obstruction", principle: "Move Qi, transform Phlegm, open constraint, calm Shen.", points: "PC 6, CV 17, ST 40, CV 22, LR 3, Yintang.", formula: formulas.banXiaHouPoTang },
      { name: "Yin and Blood Deficiency", principle: "Nourish Yin and Blood, calm Shen, soften Liver.", points: "HT 7, SP 6, BL 15, BL 17, BL 20, KI 3, LR 3.", formula: formulas.ganMaiDaZaoTang },
    ],
  },
  20: {
    overview: "Epilepsy (Xian Zheng) is recurrent sudden collapse, loss of consciousness, convulsion, or abnormal sensory/motor episodes, often involving Wind, Phlegm, Fire, and deficiency.",
    redFlags: ["New seizure", "Status epilepticus", "Seizure after head injury", "Pregnancy", "Fever, stiff neck, or persistent confusion"],
    patterns: [
      { name: "Wind-Phlegm Obstruction", principle: "Extinguish Wind, transform Phlegm, open orifices, calm Shen.", points: "GV 20, GV 26, PC 6, ST 40, LR 3, Yintang, HT 7.", formula: formulas.dingXianWan },
      { name: "Internal Profusion of Phlegm-Fire", principle: "Clear Fire, transform Phlegm, extinguish Wind, open orifices.", points: "GV 14, GV 26, PC 8, PC 7, ST 40, LR 2, LI 11, 12 Jing-well points.", formula: formulas.longDanXieGanTangHeDingXianWan },
      { name: "Liver-Kidney Yin Deficiency", principle: "Nourish Liver and Kidney Yin, extinguish Wind, calm Shen.", points: "KI 3, SP 6, LR 3, BL 18, BL 23, HT 7, GB 39.", formula: formulas.zuoGuiWan },
      { name: "Spleen-Stomach Qi Deficiency", principle: "Tonify Spleen and Stomach Qi, transform Phlegm, calm Shen.", points: "ST 36, CV 12, BL 20, BL 21, SP 6, ST 40, HT 7.", formula: formulas.liuJunZiTang },
    ],
  },
  21: {
    overview: "Fainting (Jue Zheng) is sudden loss of consciousness due to reversal or collapse of Qi, Blood, Phlegm, food, Heat, or deficiency.",
    redFlags: ["Chest pain, palpitations, or shortness of breath before fainting", "Syncope during exertion", "Neurologic deficit", "Pregnancy", "Repeated unexplained fainting"],
    patterns: [
      { name: "Excess Qi Syncope", principle: "Move Qi, open orifices, restore consciousness.", points: "GV 26, PC 6, LR 3, LI 4, CV 17.", formula: formulas.suHeXiangWan },
      { name: "Deficient Qi Syncope", principle: "Tonify Qi, rescue collapse, restore consciousness.", points: "GV 20, CV 6, ST 36, PC 6, KI 1. Use moxa if cold.", formula: formulas.shengMaiSan },
      { name: "Excess Blood Syncope", principle: "Move Blood, open orifices, regulate Qi.", points: "GV 26, PC 6, BL 17, SP 10, LR 3.", formula: formulas.xueFuZhuYuTang },
      { name: "Deficient Blood Syncope", principle: "Tonify Qi and Blood, calm Shen, restore consciousness.", points: "GV 20, ST 36, SP 6, BL 17, BL 20, HT 7.", formula: formulas.guiPiTang },
      { name: "Phlegm Syncope", principle: "Transform Phlegm, open orifices, descend turbid Qi.", points: "GV 26, PC 6, ST 40, CV 12, CV 22.", formula: formulas.diTanTang },
      { name: "Food Syncope", principle: "Harmonize Stomach, reduce food stagnation, regulate Qi.", points: "CV 12, ST 36, ST 40, SP 4, PC 6.", formula: formulas.banXiaHouPoTang },
      { name: "Summer-Heat Syncope", principle: "Clear Summer-Heat, open orifices, restore consciousness.", points: "GV 26, PC 9, LI 11, GV 14, KI 1, 12 Jing-well points.", formula: formulas.ziXueDan },
    ],
  },
  28: {
    overview: "Insomnia (Bu Mei) includes difficulty falling asleep, frequent waking, dream-disturbed sleep, or inability to return to sleep due to disturbance of Shen.",
    patterns: [
      { name: "Liver Fire Blazing", principle: "Drain Liver Fire, calm Shen, settle Hun.", points: "LR 2, LR 3, GB 20, HT 7, PC 6, GV 24.", formula: formulas.longDanXieGanTang },
      { name: "Heart Fire Blazing", principle: "Clear Heart Fire, calm Shen, promote sleep.", points: "HT 8, HT 7, PC 7, KI 6, SP 6, Yintang.", formula: formulas.daoChiSan },
      { name: "Phlegm-Fire Harassing the Mind", principle: "Clear Phlegm-Fire, harmonize middle, calm Shen.", points: "ST 40, PC 7, PC 6, CV 12, HT 7, Yintang.", formula: formulas.wenDanTang },
      { name: "Residual Heat in the Diaphragm", principle: "Clear residual Heat, harmonize Stomach, calm Shen.", points: "PC 6, CV 12, ST 44, LI 11, HT 7.", formula: formulas.wenDanTang },
      { name: "Heart-Spleen Deficiency", principle: "Tonify Heart and Spleen, nourish Blood, calm Shen.", points: "HT 7, BL 15, BL 20, ST 36, SP 6, GV 20.", formula: formulas.guiPiTang },
      { name: "Heart Yin Deficiency", principle: "Nourish Heart Yin, clear empty Heat, calm Shen.", points: "HT 7, HT 6, KI 6, SP 6, BL 15, Yintang.", formula: formulas.tianWangBuXinDan },
      { name: "Heart-Kidney Disharmony", principle: "Nourish Kidney Yin, clear Heart Fire, harmonize Heart and Kidney.", points: "HT 7, KI 3, KI 6, SP 6, CV 4, Yintang.", formula: formulas.huangLianEJiaoTang },
      { name: "Heart-Gallbladder Deficiency", principle: "Tonify Heart and Gallbladder Qi, calm Shen, settle fright.", points: "HT 7, PC 6, GB 13, GB 20, BL 15, BL 19.", formula: formulas.anShenDingZhiWan },
      { name: "Liver Yin Deficiency", principle: "Nourish Liver Yin, soften Liver, calm Shen.", points: "LR 3, KI 3, SP 6, BL 18, HT 7, Yintang.", formula: formulas.zuoGuiWan },
    ],
  },
  35: {
    overview: "Mania / Manic-Depressive Disorder (Dian Kuang) includes withdrawal, dullness, muttering, agitation, shouting, violence, or disturbed perception from Phlegm, Fire, Qi constraint, and deficiency.",
    redFlags: ["Risk of harm to self or others", "Psychosis", "Severe agitation, no sleep, or inability to care for self"],
    patterns: [
      { name: "Depressive Psychotic Pattern: Binding Depression of Qi and Phlegm", principle: "Move Qi, transform Phlegm, open constraint, calm Shen.", points: "PC 6, ST 40, CV 17, CV 12, HT 7, Yintang.", formula: formulas.shunQiDaoTanTang },
      { name: "Depressive Psychotic Pattern: Heart-Spleen Deficiency", principle: "Tonify Heart and Spleen, nourish Blood, calm Shen.", points: "HT 7, BL 15, BL 20, ST 36, SP 6, GV 20.", formula: formulas.guiPiTang },
      { name: "Manic Psychotic Pattern: Phlegm-Fire Harassing Interior", principle: "Clear Fire, transform Phlegm, open orifices, calm Shen.", points: "GV 26, PC 8, PC 7, ST 40, LI 11, LR 2, HT 8.", formula: formulas.mengShiGunTanWan },
      { name: "Manic Psychotic Pattern: Exuberant Fire with Injury to Yin", principle: "Clear Fire, nourish Yin, calm Shen.", points: "HT 7, HT 8, KI 3, KI 6, SP 6, LR 2, PC 7.", formula: formulas.tianWangBuXinDan },
    ],
  },
  36: {
    overview: "Palpitation (Xin Ji) includes subjective abnormal heartbeat, fright palpitations, or persistent palpitations due to deficiency, Fire, Phlegm-Fluid, Water, or Blood stasis disturbing the Heart.",
    redFlags: ["Chest pain", "Fainting", "Severe shortness of breath", "New irregular heartbeat", "Palpitations with dizziness or neurologic symptoms"],
    patterns: [
      { name: "Heart-Gallbladder Qi Deficiency Disturbing the Mind", principle: "Tonify Heart and Gallbladder Qi, calm Shen, settle fright.", points: "HT 7, PC 6, BL 15, GB 13, ST 36, GV 20.", formula: formulas.anShenDingZhiWan },
      { name: "Qi and Heart Blood Insufficiency", principle: "Tonify Qi, nourish Heart Blood, calm Shen.", points: "HT 7, BL 15, BL 17, ST 36, SP 6, CV 6.", formula: formulas.guiPiTang },
      { name: "Heart Fire Hyperactivity from Heart-Kidney Disharmony", principle: "Clear Heart Fire, nourish Kidney Yin, calm Shen.", points: "HT 8, HT 7, KI 3, KI 6, SP 6, PC 7.", formula: formulas.huangLianEJiaoTang },
      { name: "Heart Yang Deficiency", principle: "Warm and tonify Heart Yang, calm palpitations.", points: "CV 17, CV 6, BL 15, BL 23, GV 4, PC 6. Use moxa.", formula: formulas.siNiTang },
      { name: "Heart Oppressed by Water and Phlegm-Fluid", principle: "Warm Yang, transform fluids, resolve Phlegm, calm Heart.", points: "PC 6, ST 40, CV 12, CV 9, BL 20, BL 23, CV 6.", formula: formulas.wenDanTang },
      { name: "Heart Obstructed by Blood Stasis", principle: "Move Blood, unblock Heart vessels, calm palpitations.", points: "PC 6, PC 4, BL 14, BL 15, BL 17, SP 10.", formula: formulas.xueFuZhuYuTang },
    ],
  },
  47: {
    overview: "Wind Stroke (Zhong Feng) includes sudden collapse, hemiplegia, facial deviation, speech difficulty, or sequelae after stroke. Emergency signs require immediate medical care.",
    redFlags: ["Face drooping, arm weakness, speech difficulty", "Sudden severe headache", "Sudden vision loss, confusion, or trouble walking", "Any suspected acute stroke"],
    tcmNotes: ["Acute stroke is emergency care first. Acupuncture reference content is mainly for stabilized or rehabilitative care unless explicitly trained for emergency protocols."],
    patterns: [
      { name: "Attack of Channels and Collaterals", principle: "Unblock channels, move Qi and Blood, extinguish Wind.", points: "GV 20, GB 20, LI 4, LI 11, ST 36, ST 40, LR 3, GB 34.", formula: formulas.buYangHuanWuTang },
      { name: "Attack of Internal Organs: Tense Type", principle: "Clear Heat, extinguish Wind, open orifices, transform Phlegm.", points: "GV 26, PC 6, PC 8, LR 2, ST 40, LI 11, 12 Jing-well points.", formula: formulas.ziXueDan },
      { name: "Attack of Internal Organs: Flaccid Type", principle: "Rescue Yang, restore consciousness, secure collapse.", points: "CV 4, CV 6, GV 20, ST 36, KI 1. Use moxa.", formula: formulas.siNiTang },
      { name: "Sequelae: Wind-Phlegm", principle: "Extinguish Wind, transform Phlegm, unblock channels.", points: "GB 20, GV 20, ST 40, LI 11, GB 34, LR 3.", formula: formulas.diTanTang },
      { name: "Damp-Phlegm", principle: "Resolve Damp-Phlegm, strengthen Spleen, unblock channels.", points: "ST 40, SP 9, ST 36, BL 20, GB 34, LI 11.", formula: formulas.liuJunZiTang },
      { name: "Qi and Blood Stagnation", principle: "Tonify Qi, move Blood, unblock channels.", points: "ST 36, SP 6, BL 17, LI 11, GB 34, LR 3.", formula: formulas.buYangHuanWuTang },
      { name: "Yin Deficiency with Empty Heat", principle: "Nourish Yin, clear empty Heat, extinguish Wind.", points: "KI 3, SP 6, LR 3, BL 18, BL 23, GB 39.", formula: formulas.zhenGanXiFengTang },
    ],
  },
};
