import type { FormulaDetail, FormulaIngredient, LungConditionDetail } from "./lungContent";

const herb = (chineseName: string, pinyin: string, dose: string): FormulaIngredient => ({
  chineseName,
  pinyin,
  englishName: "",
  dose,
});

const ingredients = {
  yueBiJiaZhuTang: [
    herb("麻黄", "Ma Huang", "12 g"), herb("石膏", "Shi Gao", "24 g"),
    herb("生姜", "Sheng Jiang", "9 g"), herb("大枣", "Da Zao", "4枚"),
    herb("甘草", "Gan Cao", "6 g"), herb("白术", "Bai Zhu", "12 g"),
  ],
  maHuangLianQiaoChiXiaoDouTang: [
    herb("麻黄", "Ma Huang", "6 g"), herb("连翘", "Lian Qiao", "6 g"),
    herb("杏仁", "Xing Ren", "12 g"), herb("赤小豆", "Chi Xiao Dou", "30 g"),
    herb("大枣", "Da Zao", "12枚"), herb("生梓白皮", "Sheng Zi Bai Pi", "30 g"),
    herb("生姜", "Sheng Jiang", "6 g"), herb("甘草", "Gan Cao", "6 g"),
  ],
  weiLingTang: [
    herb("苍术", "Cang Zhu", "12 g"), herb("厚朴", "Hou Po", "9 g"),
    herb("陈皮", "Chen Pi", "6 g"), herb("炙甘草", "Zhi Gan Cao", "3 g"),
    herb("猪苓", "Zhu Ling", "9 g"), herb("泽泻", "Ze Xie", "15 g"),
    herb("白术", "Bai Zhu", "9 g"), herb("茯苓", "Fu Ling", "9 g"),
    herb("桂枝", "Gui Zhi", "6 g"), herb("生姜", "Sheng Jiang", "2片"),
    herb("大枣", "Da Zao", "2枚"),
  ],
  shuZaoYinZi: [
    herb("商陆", "Shang Lu", "6 g"), herb("泽泻", "Ze Xie", "9 g"),
    herb("赤小豆", "Chi Xiao Dou", "12 g"), herb("椒目", "Jiao Mu", "6 g"),
    herb("木通", "Mu Tong", "6 g"), herb("秦艽", "Qin Jiao", "9 g"),
    herb("槟榔", "Bing Lang", "9 g"), herb("茯苓皮", "Fu Ling Pi", "15 g"),
    herb("大腹皮", "Da Fu Pi", "9 g"), herb("羌活", "Qiang Huo", "9 g"),
    herb("生姜皮", "Sheng Jiang Pi", "6 g"),
  ],
  shiPiYin: [
    herb("厚朴", "Hou Po", "6 g"), herb("白术", "Bai Zhu", "6 g"),
    herb("木瓜", "Mu Gua", "6 g"), herb("木香", "Mu Xiang", "3 g"),
    herb("草果", "Cao Guo", "3 g"), herb("大腹皮", "Da Fu Pi", "6 g"),
    herb("附子", "Fu Zi", "6 g"), herb("茯苓", "Fu Ling", "9 g"),
    herb("干姜", "Gan Jiang", "6 g"), herb("炙甘草", "Zhi Gan Cao", "3 g"),
    herb("生姜", "Sheng Jiang", "5片"), herb("大枣", "Da Zao", "1枚"),
  ],
  zhenWuTang: [
    herb("茯苓", "Fu Ling", "9 g"), herb("芍药", "Shao Yao", "9 g"),
    herb("生姜", "Sheng Jiang", "9 g"), herb("白术", "Bai Zhu", "6 g"),
    herb("附子", "Fu Zi", "9 g"),
  ],
  youGuiWan: [
    herb("熟地黄", "Shu Di Huang", "240 g"), herb("山药", "Shan Yao", "120 g"),
    herb("山茱萸", "Shan Zhu Yu", "90 g"), herb("枸杞子", "Gou Qi Zi", "120 g"),
    herb("菟丝子", "Tu Si Zi", "120 g"), herb("杜仲", "Du Zhong", "120 g"),
    herb("当归", "Dang Gui", "90 g"), herb("鹿角胶", "Lu Jiao Jiao", "120 g"),
    herb("肉桂", "Rou Gui", "60 g"), herb("附子", "Fu Zi", "60 g"),
  ],
  daBuYuanJian: [
    herb("人参", "Ren Shen", "6 g"), herb("山药", "Shan Yao", "6 g"),
    herb("熟地黄", "Shu Di Huang", "18 g"), herb("杜仲", "Du Zhong", "6 g"),
    herb("当归", "Dang Gui", "9 g"), herb("山茱萸", "Shan Zhu Yu", "3 g"),
    herb("枸杞子", "Gou Qi Zi", "9 g"), herb("炙甘草", "Zhi Gan Cao", "3 g"),
  ],
  longDanXieGanTang: [
    herb("龙胆草", "Long Dan Cao", "6 g"), herb("黄芩", "Huang Qin", "9 g"),
    herb("栀子", "Zhi Zi", "9 g"), herb("泽泻", "Ze Xie", "12 g"),
    herb("木通", "Mu Tong", "9 g"), herb("车前子", "Che Qian Zi", "9 g"),
    herb("当归", "Dang Gui", "3 g"), herb("生地黄", "Sheng Di Huang", "9 g"),
    herb("柴胡", "Chai Hu", "6 g"), herb("生甘草", "Sheng Gan Cao", "6 g"),
  ],
  baZhengSan: [
    herb("车前子", "Che Qian Zi", "9 g"), herb("瞿麦", "Qu Mai", "9 g"),
    herb("萹蓄", "Bian Xu", "9 g"), herb("滑石", "Hua Shi", "9 g"),
    herb("山栀子仁", "Shan Zhi Zi Ren", "9 g"), herb("炙甘草", "Zhi Gan Cao", "9 g"),
    herb("木通", "Mu Tong", "9 g"), herb("大黄", "Da Huang", "9 g"),
    herb("灯心草", "Deng Xin Cao", "适量"),
  ],
  qingFeiYin: [
    herb("茯苓", "Fu Ling", "9 g"), herb("黄芩", "Huang Qin", "9 g"),
    herb("桑白皮", "Sang Bai Pi", "9 g"), herb("麦冬", "Mai Dong", "9 g"),
    herb("车前子", "Che Qian Zi", "9 g"), herb("栀子", "Zhi Zi", "6 g"),
    herb("木通", "Mu Tong", "6 g"),
  ],
  chenXiangSan: [
    herb("沉香", "Chen Xiang", "3 g"), herb("石韦", "Shi Wei", "9 g"),
    herb("滑石", "Hua Shi", "12 g"), herb("当归", "Dang Gui", "9 g"),
    herb("橘皮", "Ju Pi", "6 g"), herb("白芍", "Bai Shao", "9 g"),
    herb("王不留行", "Wang Bu Liu Xing", "9 g"), herb("甘草", "Gan Cao", "3 g"),
  ],
  jiShengShenQiWan: [
    herb("熟地黄", "Shu Di Huang", "24 g"), herb("山药", "Shan Yao", "12 g"),
    herb("山茱萸", "Shan Zhu Yu", "12 g"), herb("牡丹皮", "Mu Dan Pi", "9 g"),
    herb("茯苓", "Fu Ling", "9 g"), herb("泽泻", "Ze Xie", "9 g"),
    herb("附子", "Fu Zi", "6 g"), herb("桂枝", "Gui Zhi", "6 g"),
    herb("牛膝", "Niu Xi", "9 g"), herb("车前子", "Che Qian Zi", "9 g"),
  ],
  buZhongYiQiTang: [
    herb("黄芪", "Huang Qi", "18 g"), herb("炙甘草", "Zhi Gan Cao", "9 g"),
    herb("人参", "Ren Shen", "6 g"), herb("当归", "Dang Gui", "3 g"),
    herb("陈皮", "Chen Pi", "6 g"), herb("升麻", "Sheng Ma", "6 g"),
    herb("柴胡", "Chai Hu", "6 g"), herb("白术", "Bai Zhu", "9 g"),
  ],
  daiDiDangWan: [
    herb("大黄", "Da Huang", "12 g"), herb("当归尾", "Dang Gui Wei", "9 g"),
    herb("生地黄", "Sheng Di Huang", "12 g"), herb("穿山甲", "Chuan Shan Jia", "6 g"),
    herb("桃仁", "Tao Ren", "9 g"), herb("肉桂", "Rou Gui", "3 g"),
  ],
  ganJiangLingZhuTang: [
    herb("甘草", "Gan Cao", "6 g"), herb("白术", "Bai Zhu", "6 g"),
    herb("干姜", "Gan Jiang", "12 g"), herb("茯苓", "Fu Ling", "12 g"),
  ],
  shenTongZhuYuTang: [
    herb("秦艽", "Qin Jiao", "3 g"), herb("川芎", "Chuan Xiong", "6 g"),
    herb("桃仁", "Tao Ren", "9 g"), herb("红花", "Hong Hua", "9 g"),
    herb("甘草", "Gan Cao", "6 g"), herb("羌活", "Qiang Huo", "3 g"),
    herb("没药", "Mo Yao", "6 g"), herb("当归", "Dang Gui", "9 g"),
    herb("五灵脂", "Wu Ling Zhi", "6 g"), herb("香附", "Xiang Fu", "3 g"),
    herb("牛膝", "Niu Xi", "9 g"), herb("地龙", "Di Long", "6 g"),
  ],
  huangLianQingXinYin: [
    herb("黄连", "Huang Lian", "6 g"), herb("生地黄", "Sheng Di Huang", "12 g"),
    herb("当归", "Dang Gui", "9 g"), herb("甘草", "Gan Cao", "3 g"),
    herb("茯神", "Fu Shen", "9 g"), herb("酸枣仁", "Suan Zao Ren", "9 g"),
    herb("远志", "Yuan Zhi", "6 g"), herb("人参", "Ren Shen", "6 g"),
  ],
  biXieFenQingYin: [
    herb("益智仁", "Yi Zhi Ren", "9 g"), herb("萆薢", "Bi Xie", "12 g"),
    herb("石菖蒲", "Shi Chang Pu", "6 g"), herb("乌药", "Wu Yao", "9 g"),
  ],
  guiPiTang: [
    herb("白术", "Bai Zhu", "9 g"), herb("茯神", "Fu Shen", "9 g"),
    herb("黄芪", "Huang Qi", "12 g"), herb("龙眼肉", "Long Yan Rou", "12 g"),
    herb("酸枣仁", "Suan Zao Ren", "12 g"), herb("人参", "Ren Shen", "6 g"),
    herb("木香", "Mu Xiang", "6 g"), herb("炙甘草", "Zhi Gan Cao", "3 g"),
    herb("当归", "Dang Gui", "9 g"), herb("远志", "Yuan Zhi", "6 g"),
    herb("生姜", "Sheng Jiang", "3片"), herb("大枣", "Da Zao", "3枚"),
  ],
  jinSuoGuJingWan: [
    herb("沙苑蒺藜", "Sha Yuan Ji Li", "60 g"), herb("芡实", "Qian Shi", "60 g"),
    herb("莲须", "Lian Xu", "60 g"), herb("龙骨", "Long Gu", "30 g"),
    herb("牡蛎", "Mu Li", "30 g"), herb("莲子", "Lian Zi", "适量"),
  ],
  shiWeiSan: [
    herb("石韦", "Shi Wei", "12 g"), herb("冬葵子", "Dong Kui Zi", "9 g"),
    herb("瞿麦", "Qu Mai", "9 g"), herb("滑石", "Hua Shi", "12 g"),
    herb("车前子", "Che Qian Zi", "9 g"),
  ],
  xiaoJiYinZi: [
    herb("生地黄", "Sheng Di Huang", "12 g"), herb("小蓟", "Xiao Ji", "15 g"),
    herb("滑石", "Hua Shi", "12 g"), herb("木通", "Mu Tong", "6 g"),
    herb("蒲黄", "Pu Huang", "9 g"), herb("藕节", "Ou Jie", "9 g"),
    herb("淡竹叶", "Dan Zhu Ye", "6 g"), herb("当归", "Dang Gui", "9 g"),
    herb("栀子", "Zhi Zi", "9 g"), herb("炙甘草", "Zhi Gan Cao", "6 g"),
  ],
  wuBiShanYaoWan: [
    herb("山药", "Shan Yao", "30 g"), herb("茯苓", "Fu Ling", "15 g"),
    herb("泽泻", "Ze Xie", "9 g"), herb("熟地黄", "Shu Di Huang", "15 g"),
    herb("山茱萸", "Shan Zhu Yu", "12 g"), herb("巴戟天", "Ba Ji Tian", "9 g"),
    herb("菟丝子", "Tu Si Zi", "12 g"), herb("牛膝", "Niu Xi", "9 g"),
  ],
  yinQiaoSan: [
    herb("金银花", "Jin Yin Hua", "30 g"), herb("连翘", "Lian Qiao", "30 g"),
    herb("桔梗", "Jie Geng", "18 g"), herb("牛蒡子", "Niu Bang Zi", "18 g"),
    herb("薄荷", "Bo He", "18 g"), herb("淡豆豉", "Dan Dou Chi", "15 g"),
    herb("淡竹叶", "Dan Zhu Ye", "12 g"), herb("荆芥", "Jing Jie", "12 g"),
    herb("芦根", "Lu Gen", "18 g"), herb("甘草", "Gan Cao", "15 g"),
  ],
  huangLianWenDanTang: [
    herb("黄连", "Huang Lian", "6 g"), herb("半夏", "Ban Xia", "6 g"),
    herb("竹茹", "Zhu Ru", "6 g"), herb("枳实", "Zhi Shi", "6 g"),
    herb("陈皮", "Chen Pi", "9 g"), herb("茯苓", "Fu Ling", "4.5 g"),
    herb("甘草", "Gan Cao", "3 g"), herb("生姜", "Sheng Jiang", "5片"),
    herb("大枣", "Da Zao", "1枚"),
  ],
  zuoGuiWan: [
    herb("熟地黄", "Shu Di Huang", "240 g"), herb("山药", "Shan Yao", "120 g"),
    herb("山茱萸", "Shan Zhu Yu", "120 g"), herb("枸杞子", "Gou Qi Zi", "120 g"),
    herb("鹿角胶", "Lu Jiao Jiao", "120 g"), herb("菟丝子", "Tu Si Zi", "120 g"),
    herb("龟甲胶", "Gui Jia Jiao", "120 g"), herb("川牛膝", "Chuan Niu Xi", "90 g"),
  ],
} satisfies Record<string, FormulaIngredient[]>;

const formula = (
  chineseName: string,
  pinyin: string,
  actions: string[],
  indications: string,
  formulaIngredients: FormulaIngredient[],
): FormulaDetail => ({ chineseName, pinyin, actions, indications, ingredients: formulaIngredients });

const formulas = {
  yueBiJiaZhuTang: formula("越婢加术汤", "Yue Bi Jia Zhu Tang", ["Releases exterior", "Clears Heat", "Promotes urination"], "Acute upper-body edema with fever, thirst, scant urine, and floating forceful pulse.", ingredients.yueBiJiaZhuTang),
  maHuangLianQiaoChiXiaoDouTang: formula("麻黄连翘赤小豆汤", "Ma Huang Lian Qiao Chi Xiao Dou Tang", ["Releases exterior", "Clears toxin", "Reduces edema"], "Edema with skin sores, redness, fever, and toxic Heat signs.", ingredients.maHuangLianQiaoChiXiaoDouTang),
  weiLingTang: formula("胃苓汤", "Wei Ling Tang", ["Transforms Dampness", "Strengthens Spleen", "Moves water"], "Generalized edema with heaviness, poor appetite, abdominal fullness, and greasy coat.", ingredients.weiLingTang),
  shuZaoYinZi: formula("疏凿饮子", "Shu Zao Yin Zi", ["Clears Damp-Heat", "Moves water", "Reduces swelling"], "Firm generalized edema, thirst, scant dark urine, and yellow greasy coat.", ingredients.shuZaoYinZi),
  shiPiYin: formula("实脾饮", "Shi Pi Yin", ["Warms Spleen Yang", "Moves water", "Reduces edema"], "Chronic edema with cold limbs, abdominal fullness, poor appetite, and loose stool.", ingredients.shiPiYin),
  zhenWuTang: formula("真武汤", "Zhen Wu Tang", ["Warms Kidney Yang", "Promotes urination", "Transforms fluids"], "Edema with cold limbs, weak back, dizziness, scant urine, and deep weak pulse.", ingredients.zhenWuTang),
  youGuiWan: formula("右归丸", "You Gui Wan", ["Warms Kidney Yang", "Replenishes Essence"], "Cold lower back and knees, low libido, fatigue, and deep weak pulse.", ingredients.youGuiWan),
  daBuYuanJian: formula("大补元煎", "Da Bu Yuan Jian", ["Tonifies Kidney Qi and Essence", "Nourishes Blood"], "Impotence with marked deficiency, fatigue, dizziness, and weak pulse.", ingredients.daBuYuanJian),
  longDanXieGanTang: formula("龙胆泻肝汤", "Long Dan Xie Gan Tang", ["Clears Liver Damp-Heat", "Drains Fire"], "Genital heaviness, itching, painful urination, irritability, and yellow greasy coat.", ingredients.longDanXieGanTang),
  baZhengSan: formula("八正散", "Ba Zheng San", ["Clears Bladder Damp-Heat", "Promotes urination"], "Urinary retention or painful scant urine with urgency, burning, and dark urine.", ingredients.baZhengSan),
  qingFeiYin: formula("清肺饮", "Qing Fei Yin", ["Clears Lung Heat", "Restores water pathways"], "Urinary retention after respiratory Heat with thirst, cough, and dry mouth.", ingredients.qingFeiYin),
  chenXiangSan: formula("沉香散", "Chen Xiang San", ["Moves Liver Qi", "Opens urination", "Relieves pain"], "Urinary retention worsened by emotion with lower abdominal distention.", ingredients.chenXiangSan),
  jiShengShenQiWan: formula("济生肾气丸", "Ji Sheng Shen Qi Wan", ["Warms Kidney Yang", "Moves water", "Promotes urination"], "Chronic retention with weak stream, cold limbs, edema, and weak back.", ingredients.jiShengShenQiWan),
  buZhongYiQiTang: formula("补中益气汤", "Bu Zhong Yi Qi Tang", ["Tonifies Spleen Qi", "Raises clear Yang"], "Difficulty urinating with fatigue, prolapse tendency, poor appetite, and weak pulse.", ingredients.buZhongYiQiTang),
  daiDiDangWan: formula("代抵当丸", "Dai Di Dang Wan", ["Moves Blood", "Breaks stasis", "Opens urination"], "Urinary blockage after trauma or surgery with fixed lower abdominal pain and purple tongue.", ingredients.daiDiDangWan),
  ganJiangLingZhuTang: formula("甘姜苓术汤", "Gan Jiang Ling Zhu Tang", ["Warms middle", "Dispels Cold-Damp", "Relieves back pain"], "Heavy cold low-back pain worse in damp weather and relieved by warmth.", ingredients.ganJiangLingZhuTang),
  shenTongZhuYuTang: formula("身痛逐瘀汤", "Shen Tong Zhu Yu Tang", ["Moves Qi and Blood", "Unblocks channels", "Stops pain"], "Fixed stabbing back pain after trauma or with purple tongue and choppy pulse.", ingredients.shenTongZhuYuTang),
  huangLianQingXinYin: formula("黄连清心饮", "Huang Lian Qing Xin Yin", ["Clears Heart Fire", "Nourishes Yin", "Calms spirit"], "Dream-disturbed emission with irritability, insomnia, thirst, and red tongue.", ingredients.huangLianQingXinYin),
  biXieFenQingYin: formula("萆薢分清饮", "Bi Xie Fen Qing Yin", ["Separates clear from turbid", "Transforms Dampness"], "Emission or cloudy urine with genital heaviness and greasy coat.", ingredients.biXieFenQingYin),
  guiPiTang: formula("归脾汤", "Gui Pi Tang", ["Tonifies Heart and Spleen", "Nourishes Blood", "Secures Essence"], "Emission with palpitations, poor memory, fatigue, poor appetite, and pale tongue.", ingredients.guiPiTang),
  jinSuoGuJingWan: formula("金锁固精丸", "Jin Suo Gu Jing Wan", ["Secures Kidney Essence", "Stops emission"], "Frequent emission with weak back, tinnitus, fatigue, and weak pulse.", ingredients.jinSuoGuJingWan),
  shiWeiSan: formula("石韦散", "Shi Wei San", ["Clears Heat", "Promotes urination", "Expels stones"], "Stone stranguria with colicky flank pain, gravel, and painful urination.", ingredients.shiWeiSan),
  xiaoJiYinZi: formula("小蓟饮子", "Xiao Ji Yin Zi", ["Cools Blood", "Stops bleeding", "Clears urinary Heat"], "Bloody painful urination with bright red blood and burning.", ingredients.xiaoJiYinZi),
  wuBiShanYaoWan: formula("无比山药丸", "Wu Bi Shan Yao Wan", ["Tonifies Spleen and Kidney", "Secures urination"], "Fatigue stranguria with recurrent symptoms, weak back, and deficiency pulse.", ingredients.wuBiShanYaoWan),
  yinQiaoSan: formula("银翘散", "Yin Qiao San", ["Releases Wind-Heat", "Clears Heat toxin"], "Acute tinnitus after Wind-Heat with fever, sore throat, and floating rapid pulse.", ingredients.yinQiaoSan),
  huangLianWenDanTang: formula("黄连温胆汤", "Huang Lian Wen Dan Tang", ["Clears Phlegm-Fire", "Harmonizes middle", "Opens the ears"], "Loud tinnitus with dizziness, nausea, bitter taste, and yellow greasy coat.", ingredients.huangLianWenDanTang),
  zuoGuiWan: formula("左归丸", "Zuo Gui Wan", ["Nourishes Kidney Essence and Yin", "Fills marrow"], "Chronic low tinnitus or deafness with weak back, dizziness, and deficiency signs.", ingredients.zuoGuiWan),
} satisfies Record<string, FormulaDetail>;

export const kidneyContent: Record<number, LungConditionDetail> = {
  18: {
    overview: "Edema (Shui Zhong) is fluid accumulation caused by dysfunction of Lung dispersing, Spleen transforming, Kidney warming, or Damp-Heat obstructing water pathways.",
    redFlags: ["Sudden swelling with shortness of breath", "Chest pain", "Very low urine output", "One-sided painful leg swelling", "Swelling during pregnancy"],
    patterns: [
      { name: "Yang Edema: Wind-Water Invading Wei Qi", principle: "Release exterior, diffuse Lung Qi, promote urination.", points: "LU 7, LI 4, BL 13, CV 9, SP 9, BL 22.", formula: formulas.yueBiJiaZhuTang },
      { name: "Yang Edema: Fire Poison", principle: "Clear Heat toxin, cool Blood, promote urination.", points: "LI 11, GV 14, SP 10, CV 9, SP 9, BL 22.", formula: formulas.maHuangLianQiaoChiXiaoDouTang },
      { name: "Yang Edema: Dampness", principle: "Transform Dampness, strengthen Spleen, move water.", points: "SP 9, ST 36, BL 20, CV 9, CV 12, BL 22.", formula: formulas.weiLingTang },
      { name: "Yang Edema: Damp-Heat", principle: "Clear Damp-Heat, open water passages, reduce swelling.", points: "SP 9, LI 11, GB 34, CV 9, BL 22, ST 28.", formula: formulas.shuZaoYinZi },
      { name: "Yin Edema: Spleen Yang Deficiency", principle: "Warm Spleen Yang, transform fluids, promote urination.", points: "BL 20, ST 36, CV 12, CV 9, SP 9, GV 4. Use moxa.", formula: formulas.shiPiYin },
      { name: "Yin Edema: Kidney Yang Deficiency", principle: "Warm Kidney Yang, transform Qi, move water.", points: "BL 23, CV 4, GV 4, KI 7, CV 9, BL 22. Use moxa.", formula: formulas.zhenWuTang },
    ],
  },
  27: {
    overview: "Impotence (Yang Wei) is inability to achieve or sustain erection from Kidney deficiency, Mingmen Fire debility, or Damp-Heat obstructing the lower burner.",
    redFlags: ["Sudden onset after injury", "Painful erection lasting over four hours", "Genital numbness", "New neurologic symptoms", "Medication-related sudden change"],
    patterns: [
      { name: "Debilitation of Mingmen Fire", principle: "Warm Mingmen, tonify Kidney Yang, strengthen function.", points: "CV 4, GV 4, BL 23, KI 3, KI 7, ST 36. Use moxa.", formula: formulas.youGuiWan },
      { name: "Kidney Deficiency", principle: "Tonify Kidney Qi and Essence, strengthen low back.", points: "CV 4, BL 23, KI 3, SP 6, GB 39, ST 36.", formula: formulas.daBuYuanJian },
      { name: "Damp-Heat Pouring Downward", principle: "Clear lower-burner Damp-Heat, course Liver Qi.", points: "LR 2, GB 34, SP 9, CV 3, LR 3, ST 28.", formula: formulas.longDanXieGanTang },
    ],
  },
  30: {
    overview: "Ischuria (Long Bi) is difficult or absent urination due to Heat, Qi obstruction, deficiency, or Blood stasis blocking Bladder transformation.",
    redFlags: ["Unable to urinate with painful bladder fullness", "Fever or chills", "Blood in urine", "New leg weakness or saddle numbness", "Recent pelvic trauma"],
    patterns: [
      { name: "Heat or Damp-Heat Accumulation in Bladder", principle: "Clear Bladder Damp-Heat, open urination.", points: "CV 3, BL 28, SP 9, ST 28, BL 22, LI 11.", formula: formulas.baZhengSan },
      { name: "Lung Heat Congestion", principle: "Clear Lung Heat, restore descending and water pathways.", points: "LU 5, LU 7, BL 13, CV 3, BL 22, KI 7.", formula: formulas.qingFeiYin },
      { name: "Liver Qi Stagnation", principle: "Spread Liver Qi, regulate lower burner, open urination.", points: "LR 3, GB 34, PC 6, CV 3, CV 6, BL 28.", formula: formulas.chenXiangSan },
      { name: "Decline of Mingmen Fire / Kidney Qi or Yang Insufficiency", principle: "Warm Kidney Yang, transform Bladder Qi, promote urination.", points: "CV 4, GV 4, BL 23, KI 7, CV 3, BL 28. Use moxa.", formula: formulas.jiShengShenQiWan },
      { name: "Spleen Qi Deficiency", principle: "Tonify Spleen Qi, raise clear Yang, support urination.", points: "ST 36, BL 20, CV 6, GV 20, SP 6, CV 3.", formula: formulas.buZhongYiQiTang },
      { name: "Meridian Qi Damage / Blood Stasis / Traumatic Injury", principle: "Move Blood, unblock lower burner, restore urination.", points: "SP 10, BL 17, CV 3, CV 6, ST 28, LR 3.", formula: formulas.daiDiDangWan },
    ],
  },
  32: {
    overview: "Lumbago (Yao Tong) is low-back pain from Cold-Damp obstruction, Qi-Blood stagnation, or Kidney deficiency failing to nourish the lumbar region.",
    redFlags: ["New bowel or bladder dysfunction", "Saddle numbness", "Progressive leg weakness", "Fever or unexplained weight loss", "Major trauma"],
    patterns: [
      { name: "Cold-Damp Invasion", principle: "Warm channels, dispel Cold-Damp, stop pain.", points: "BL 23, BL 25, GV 3, GV 4, BL 40, SP 9. Use moxa.", formula: formulas.ganJiangLingZhuTang },
      { name: "Qi and Blood Stagnation", principle: "Move Qi and Blood, unblock collaterals, stop fixed pain.", points: "BL 17, SP 10, BL 23, BL 25, BL 40, Ashi points.", formula: formulas.shenTongZhuYuTang },
      { name: "Kidney Deficiency", principle: "Tonify Kidney, strengthen lumbar region, nourish Essence.", points: "BL 23, KI 3, GV 4, CV 4, GB 39, BL 40.", formula: formulas.youGuiWan },
    ],
  },
  39: {
    overview: "Seminal Emission (Yi Jing) includes nocturnal or spontaneous emission caused by Fire, Damp-Heat, Heart-Spleen deficiency, or Kidney failure to secure Essence.",
    patterns: [
      { name: "Heart Fire Hyperactivity with Kidney Yin Deficiency", principle: "Clear Heart Fire, nourish Kidney Yin, calm Shen.", points: "HT 8, HT 7, KI 3, KI 6, SP 6, CV 4.", formula: formulas.huangLianQingXinYin },
      { name: "Downward Flow of Damp-Heat", principle: "Clear lower-burner Damp-Heat, separate clear from turbid.", points: "CV 3, SP 9, LR 2, GB 34, ST 28, KI 10.", formula: formulas.biXieFenQingYin },
      { name: "Heart-Spleen Deficiency", principle: "Tonify Heart and Spleen, nourish Blood, secure Essence.", points: "HT 7, BL 15, BL 20, ST 36, SP 6, CV 6.", formula: formulas.guiPiTang },
      { name: "Kidney Deficiency", principle: "Tonify Kidney, secure Essence, stop emission.", points: "CV 4, BL 23, KI 3, KI 6, SP 6, GV 4.", formula: formulas.jinSuoGuJingWan },
    ],
  },
  41: {
    overview: "Stranguria (Lin Zheng) is frequent, urgent, difficult, or painful urination classified by Heat, stone, Blood, Qi, turbidity, or deficiency.",
    redFlags: ["Fever with flank pain", "Unable to urinate", "Visible blood or clots", "Severe colicky pain", "Pregnancy with urinary symptoms"],
    patterns: [
      { name: "Heat Lin", principle: "Clear Bladder Heat, promote urination, relieve pain.", points: "CV 3, BL 28, SP 9, ST 28, LI 11, KI 10.", formula: formulas.baZhengSan },
      { name: "Stone Lin", principle: "Clear Heat, promote urination, expel stones.", points: "CV 3, BL 28, SP 9, KI 3, BL 23, ST 28.", formula: formulas.shiWeiSan },
      { name: "Blood Lin", principle: "Cool Blood, stop bleeding, clear urinary Heat.", points: "CV 3, BL 28, SP 10, BL 17, KI 10, SP 9.", formula: formulas.xiaoJiYinZi },
      { name: "Qi Lin", principle: "Regulate Qi, open lower burner, promote urination.", points: "LR 3, PC 6, CV 3, CV 6, BL 28, ST 28.", formula: formulas.chenXiangSan },
      { name: "Sticky / Cloudy Lin", principle: "Transform Dampness, separate clear from turbid.", points: "CV 3, SP 9, ST 28, BL 28, BL 20, KI 10.", formula: formulas.biXieFenQingYin },
      { name: "Fatigue Lin", principle: "Tonify Spleen and Kidney, secure lower burner.", points: "ST 36, BL 20, BL 23, CV 4, SP 6, KI 3.", formula: formulas.wuBiShanYaoWan },
    ],
  },
  42: {
    overview: "Tinnitus and Deafness (Er Ming Er Long) arise from Liver-Gallbladder Fire, Wind-Heat, Phlegm-Fire, Kidney Essence deficiency, or weak Spleen-Stomach Qi.",
    redFlags: ["Sudden hearing loss", "One-sided tinnitus with neurologic symptoms", "Severe vertigo", "Ear discharge with fever", "Pulsatile tinnitus"],
    patterns: [
      { name: "Liver-Gallbladder Fire Rising", principle: "Drain Liver-Gallbladder Fire, open the ears.", points: "TE 17, SI 19, GB 2, TE 5, GB 41, LR 2.", formula: formulas.longDanXieGanTang },
      { name: "Wind-Heat Invasion", principle: "Disperse Wind-Heat, clear the Shaoyang channels.", points: "TE 17, SI 19, GB 2, TE 5, LI 4, GB 20.", formula: formulas.yinQiaoSan },
      { name: "Phlegm-Fire Flaring Upward", principle: "Clear Phlegm-Fire, harmonize middle, open the ears.", points: "ST 40, PC 6, CV 12, TE 17, GB 2, LR 2.", formula: formulas.huangLianWenDanTang },
      { name: "Kidney Essence Deficiency", principle: "Tonify Kidney Essence, nourish marrow, benefit hearing.", points: "KI 3, BL 23, GV 4, GB 39, TE 17, SI 19.", formula: formulas.zuoGuiWan },
      { name: "Spleen-Stomach Qi Deficiency", principle: "Tonify middle Qi, raise clear Yang, benefit the ears.", points: "ST 36, BL 20, CV 6, GV 20, TE 17, SI 19.", formula: formulas.buZhongYiQiTang },
    ],
  },
};
