import type { FormulaDetail, FormulaIngredient, LungConditionDetail } from "./lungContent";

const herb = (chineseName: string, pinyin: string, dose: string): FormulaIngredient => ({
  chineseName,
  pinyin,
  englishName: "",
  dose,
});

const ingredients = {
  haiZaoYuHuTang: [
    herb("海藻", "Hai Zao", "3 g"), herb("昆布", "Kun Bu", "3 g"),
    herb("海带", "Hai Dai", "3 g"), herb("青皮", "Qing Pi", "3 g"),
    herb("陈皮", "Chen Pi", "3 g"), herb("半夏", "Ban Xia", "3 g"),
    herb("贝母", "Bei Mu", "3 g"), herb("连翘", "Lian Qiao", "3 g"),
    herb("当归", "Dang Gui", "3 g"), herb("川芎", "Chuan Xiong", "3 g"),
    herb("独活", "Du Huo", "3 g"), herb("甘草", "Gan Cao", "3 g"),
  ],
  liuJunZiTang: [
    herb("人参", "Ren Shen", "9 g"), herb("白术", "Bai Zhu", "9 g"),
    herb("茯苓", "Fu Ling", "9 g"), herb("炙甘草", "Zhi Gan Cao", "6 g"),
    herb("陈皮", "Chen Pi", "3 g"), herb("半夏", "Ban Xia", "4.5 g"),
    herb("生姜", "Sheng Jiang", "3片"), herb("大枣", "Da Zao", "2枚"),
  ],
  zhiZiQingGanTang: [
    herb("栀子", "Zhi Zi", "6 g"), herb("牡丹皮", "Mu Dan Pi", "6 g"),
    herb("柴胡", "Chai Hu", "6 g"), herb("当归", "Dang Gui", "6 g"),
    herb("白芍", "Bai Shao", "6 g"), herb("川芎", "Chuan Xiong", "4.5 g"),
    herb("茯苓", "Fu Ling", "6 g"), herb("牛蒡子", "Niu Bang Zi", "6 g"),
    herb("甘草", "Gan Cao", "3 g"),
  ],
  taoHongSiWuTang: [
    herb("桃仁", "Tao Ren", "9 g"), herb("红花", "Hong Hua", "6 g"),
    herb("熟地黄", "Shu Di Huang", "12 g"), herb("当归", "Dang Gui", "9 g"),
    herb("白芍", "Bai Shao", "9 g"), herb("川芎", "Chuan Xiong", "6 g"),
  ],
  yiGuanJian: [
    herb("北沙参", "Bei Sha Shen", "9 g"), herb("麦冬", "Mai Dong", "9 g"),
    herb("当归身", "Dang Gui Shen", "9 g"), herb("生地黄", "Sheng Di Huang", "18 g"),
    herb("枸杞子", "Gou Qi Zi", "12 g"), herb("川楝子", "Chuan Lian Zi", "4.5 g"),
  ],
  chuanXiongChaTiaoSan: [
    herb("川芎", "Chuan Xiong", "12 g"), herb("荆芥", "Jing Jie", "12 g"),
    herb("白芷", "Bai Zhi", "6 g"), herb("羌活", "Qiang Huo", "6 g"),
    herb("甘草", "Gan Cao", "6 g"), herb("细辛", "Xi Xin", "3 g"),
    herb("防风", "Fang Feng", "4.5 g"), herb("薄荷", "Bo He", "24 g"),
  ],
  xiongZhiShiGaoTang: [
    herb("川芎", "Chuan Xiong", "9 g"), herb("白芷", "Bai Zhi", "9 g"),
    herb("石膏", "Shi Gao", "15 g"), herb("菊花", "Ju Hua", "9 g"),
    herb("藁本", "Gao Ben", "6 g"), herb("羌活", "Qiang Huo", "6 g"),
  ],
  qiangHuoShengShiTang: [
    herb("羌活", "Qiang Huo", "6 g"), herb("独活", "Du Huo", "6 g"),
    herb("藁本", "Gao Ben", "3 g"), herb("防风", "Fang Feng", "3 g"),
    herb("炙甘草", "Zhi Gan Cao", "3 g"), herb("蔓荆子", "Man Jing Zi", "2 g"),
    herb("川芎", "Chuan Xiong", "3 g"),
  ],
  tianMaGouTengYin: [
    herb("天麻", "Tian Ma", "9 g"), herb("钩藤", "Gou Teng", "12 g"),
    herb("石决明", "Shi Jue Ming", "18 g"), herb("栀子", "Zhi Zi", "9 g"),
    herb("黄芩", "Huang Qin", "9 g"), herb("川牛膝", "Chuan Niu Xi", "12 g"),
    herb("杜仲", "Du Zhong", "9 g"), herb("益母草", "Yi Mu Cao", "9 g"),
    herb("桑寄生", "Sang Ji Sheng", "9 g"), herb("夜交藤", "Ye Jiao Teng", "9 g"),
    herb("茯神", "Fu Shen", "9 g"),
  ],
  longDanXieGanTang: [
    herb("龙胆草", "Long Dan Cao", "6 g"), herb("黄芩", "Huang Qin", "9 g"),
    herb("栀子", "Zhi Zi", "9 g"), herb("泽泻", "Ze Xie", "12 g"),
    herb("木通", "Mu Tong", "9 g"), herb("车前子", "Che Qian Zi", "9 g"),
    herb("当归", "Dang Gui", "3 g"), herb("生地黄", "Sheng Di Huang", "9 g"),
    herb("柴胡", "Chai Hu", "6 g"), herb("生甘草", "Sheng Gan Cao", "6 g"),
  ],
  zhenGanXiFengTang: [
    herb("怀牛膝", "Huai Niu Xi", "30 g"), herb("代赭石", "Dai Zhe Shi", "30 g"),
    herb("龙骨", "Long Gu", "15 g"), herb("牡蛎", "Mu Li", "15 g"),
    herb("龟板", "Gui Ban", "15 g"), herb("玄参", "Xuan Shen", "15 g"),
    herb("天冬", "Tian Dong", "15 g"), herb("川楝子", "Chuan Lian Zi", "6 g"),
    herb("生麦芽", "Sheng Mai Ya", "6 g"), herb("茵陈", "Yin Chen", "6 g"),
    herb("甘草", "Gan Cao", "4.5 g"),
  ],
  chaiHuShuGanSan: [
    herb("陈皮", "Chen Pi", "6 g"), herb("柴胡", "Chai Hu", "6 g"),
    herb("川芎", "Chuan Xiong", "4.5 g"), herb("枳壳", "Zhi Ke", "4.5 g"),
    herb("芍药", "Shao Yao", "4.5 g"), herb("炙甘草", "Zhi Gan Cao", "1.5 g"),
    herb("香附", "Xiang Fu", "4.5 g"),
  ],
  wuZhuYuTang: [
    herb("吴茱萸", "Wu Zhu Yu", "9 g"), herb("人参", "Ren Shen", "9 g"),
    herb("生姜", "Sheng Jiang", "18 g"), herb("大枣", "Da Zao", "4枚"),
  ],
  pingWeiSan: [
    herb("苍术", "Cang Zhu", "12 g"), herb("厚朴", "Hou Po", "9 g"),
    herb("陈皮", "Chen Pi", "6 g"), herb("炙甘草", "Zhi Gan Cao", "3 g"),
    herb("生姜", "Sheng Jiang", "2片"), herb("大枣", "Da Zao", "2枚"),
  ],
  banXiaBaiZhuTianMaTang: [
    herb("半夏", "Ban Xia", "9 g"), herb("天麻", "Tian Ma", "6 g"),
    herb("茯苓", "Fu Ling", "9 g"), herb("橘红", "Ju Hong", "6 g"),
    herb("白术", "Bai Zhu", "9 g"), herb("甘草", "Gan Cao", "3 g"),
    herb("生姜", "Sheng Jiang", "2片"), herb("大枣", "Da Zao", "2枚"),
  ],
  baoHeWan: [
    herb("山楂", "Shan Zha", "180 g"), herb("神曲", "Shen Qu", "60 g"),
    herb("半夏", "Ban Xia", "90 g"), herb("茯苓", "Fu Ling", "90 g"),
    herb("陈皮", "Chen Pi", "30 g"), herb("连翘", "Lian Qiao", "30 g"),
    herb("莱菔子", "Lai Fu Zi", "30 g"),
  ],
  tongQiaoHuoXueTang: [
    herb("赤芍", "Chi Shao", "3 g"), herb("川芎", "Chuan Xiong", "3 g"),
    herb("桃仁", "Tao Ren", "9 g"), herb("红花", "Hong Hua", "9 g"),
    herb("老葱", "Lao Cong", "3根"), herb("鲜姜", "Xian Jiang", "9 g"),
    herb("红枣", "Hong Zao", "7枚"), herb("麝香", "She Xiang", "0.15 g"),
  ],
  baiHuTang: [
    herb("石膏", "Shi Gao", "50 g"), herb("知母", "Zhi Mu", "18 g"),
    herb("炙甘草", "Zhi Gan Cao", "6 g"), herb("粳米", "Jing Mi", "9 g"),
  ],
  buZhongYiQiTang: [
    herb("黄芪", "Huang Qi", "18 g"), herb("炙甘草", "Zhi Gan Cao", "9 g"),
    herb("人参", "Ren Shen", "6 g"), herb("当归", "Dang Gui", "3 g"),
    herb("陈皮", "Chen Pi", "6 g"), herb("升麻", "Sheng Ma", "6 g"),
    herb("柴胡", "Chai Hu", "6 g"), herb("白术", "Bai Zhu", "9 g"),
  ],
  siWuTang: [
    herb("熟地黄", "Shu Di Huang", "12 g"), herb("当归", "Dang Gui", "9 g"),
    herb("白芍", "Bai Shao", "9 g"), herb("川芎", "Chuan Xiong", "6 g"),
  ],
  zuoGuiWan: [
    herb("熟地黄", "Shu Di Huang", "240 g"), herb("山药", "Shan Yao", "120 g"),
    herb("山茱萸", "Shan Zhu Yu", "120 g"), herb("枸杞子", "Gou Qi Zi", "120 g"),
    herb("鹿角胶", "Lu Jiao Jiao", "120 g"), herb("菟丝子", "Tu Si Zi", "120 g"),
    herb("龟甲胶", "Gui Jia Jiao", "120 g"), herb("川牛膝", "Chuan Niu Xi", "90 g"),
  ],
  fuYuanHuoXueTang: [
    herb("柴胡", "Chai Hu", "15 g"), herb("瓜蒌根", "Gua Lou Gen", "9 g"),
    herb("当归", "Dang Gui", "9 g"), herb("红花", "Hong Hua", "6 g"),
    herb("甘草", "Gan Cao", "6 g"), herb("穿山甲", "Chuan Shan Jia", "6 g"),
    herb("大黄", "Da Huang", "18 g"), herb("桃仁", "Tao Ren", "15 g"),
  ],
  yinChenHaoTang: [
    herb("茵陈", "Yin Chen", "18 g"), herb("栀子", "Zhi Zi", "9 g"),
    herb("大黄", "Da Huang", "6 g"),
  ],
  ganLuXiaoDuDan: [
    herb("滑石", "Hua Shi", "15 g"), herb("茵陈", "Yin Chen", "11 g"),
    herb("黄芩", "Huang Qin", "9 g"), herb("石菖蒲", "Shi Chang Pu", "6 g"),
    herb("川贝母", "Chuan Bei Mu", "6 g"), herb("木通", "Mu Tong", "6 g"),
    herb("藿香", "Huo Xiang", "4 g"), herb("射干", "She Gan", "4 g"),
    herb("连翘", "Lian Qiao", "4 g"), herb("薄荷", "Bo He", "4 g"),
    herb("白豆蔻", "Bai Dou Kou", "4 g"),
  ],
  qingWenBaiDuYin: [
    herb("石膏", "Shi Gao", "30 g"), herb("生地黄", "Sheng Di Huang", "15 g"),
    herb("犀角", "Xi Jiao", "3 g"), herb("黄连", "Huang Lian", "6 g"),
    herb("栀子", "Zhi Zi", "9 g"), herb("桔梗", "Jie Geng", "6 g"),
    herb("黄芩", "Huang Qin", "9 g"), herb("知母", "Zhi Mu", "9 g"),
    herb("赤芍", "Chi Shao", "9 g"), herb("玄参", "Xuan Shen", "9 g"),
    herb("连翘", "Lian Qiao", "9 g"), herb("牡丹皮", "Mu Dan Pi", "9 g"),
    herb("竹叶", "Zhu Ye", "6 g"), herb("甘草", "Gan Cao", "6 g"),
  ],
  yinChenZhuFuTang: [
    herb("茵陈", "Yin Chen", "6 g"), herb("白术", "Bai Zhu", "9 g"),
    herb("附子", "Fu Zi", "9 g"), herb("干姜", "Gan Jiang", "9 g"),
    herb("炙甘草", "Zhi Gan Cao", "6 g"), herb("肉桂", "Rou Gui", "3 g"),
  ],
  xiaoChaiHuTang: [
    herb("柴胡", "Chai Hu", "24 g"), herb("黄芩", "Huang Qin", "9 g"),
    herb("人参", "Ren Shen", "9 g"), herb("半夏", "Ban Xia", "9 g"),
    herb("炙甘草", "Zhi Gan Cao", "9 g"), herb("生姜", "Sheng Jiang", "9 g"),
    herb("大枣", "Da Zao", "4枚"),
  ],
  baiHuJiaGuiZhiTang: [
    herb("知母", "Zhi Mu", "18 g"), herb("石膏", "Shi Gao", "48 g"),
    herb("炙甘草", "Zhi Gan Cao", "6 g"), herb("粳米", "Jing Mi", "9 g"),
    herb("桂枝", "Gui Zhi", "9 g"),
  ],
  chaiHuGuiZhiGanJiangTang: [
    herb("柴胡", "Chai Hu", "24 g"), herb("桂枝", "Gui Zhi", "9 g"),
    herb("干姜", "Gan Jiang", "6 g"), herb("瓜蒌根", "Gua Lou Gen", "12 g"),
    herb("黄芩", "Huang Qin", "9 g"), herb("牡蛎", "Mu Li", "6 g"),
    herb("炙甘草", "Zhi Gan Cao", "6 g"),
  ],
  heRenYin: [
    herb("何首乌", "He Shou Wu", "9 g"), herb("人参", "Ren Shen", "9 g"),
    herb("当归", "Dang Gui", "9 g"), herb("陈皮", "Chen Pi", "6 g"),
    herb("煨生姜", "Wei Sheng Jiang", "3片"),
  ],
  qingZhangTang: [
    herb("青蒿", "Qing Hao", "9 g"), herb("黄芩", "Huang Qin", "9 g"),
    herb("知母", "Zhi Mu", "9 g"), herb("柴胡", "Chai Hu", "9 g"),
    herb("常山", "Chang Shan", "6 g"), herb("半夏", "Ban Xia", "9 g"),
    herb("陈皮", "Chen Pi", "6 g"), herb("茯苓", "Fu Ling", "9 g"),
  ],
  guiPiTang: [
    herb("白术", "Bai Zhu", "9 g"), herb("茯神", "Fu Shen", "9 g"),
    herb("黄芪", "Huang Qi", "12 g"), herb("龙眼肉", "Long Yan Rou", "12 g"),
    herb("酸枣仁", "Suan Zao Ren", "12 g"), herb("人参", "Ren Shen", "6 g"),
    herb("木香", "Mu Xiang", "6 g"), herb("炙甘草", "Zhi Gan Cao", "3 g"),
    herb("当归", "Dang Gui", "9 g"), herb("远志", "Yuan Zhi", "6 g"),
    herb("生姜", "Sheng Jiang", "3片"), herb("大枣", "Da Zao", "3枚"),
  ],
} satisfies Record<string, FormulaIngredient[]>;

const formula = (
  chineseName: string,
  pinyin: string,
  actions: string[],
  indications: string,
  formulaIngredients: FormulaIngredient[],
): FormulaDetail => ({ chineseName, pinyin, actions, indications, ingredients: formulaIngredients });

const formulas = {
  haiZaoYuHuTang: formula("海藻玉壶汤", "Hai Zao Yu Hu Tang", ["Moves Qi", "Transforms Phlegm", "Softens neck masses"], "Goitre with soft swelling, chest constraint, sighing, and a wiry slippery pulse.", ingredients.haiZaoYuHuTang),
  liuJunZiTang: formula("六君子汤", "Liu Jun Zi Tang", ["Tonifies Spleen Qi", "Transforms Phlegm", "Harmonizes middle burner"], "Goitre or dizziness with fatigue, poor appetite, loose stool, and abundant Phlegm.", ingredients.liuJunZiTang),
  zhiZiQingGanTang: formula("栀子清肝汤", "Zhi Zi Qing Gan Tang", ["Clears Liver Fire", "Resolves Phlegm-Heat", "Softens swelling"], "Firm painful goitre with irritability, heat, thirst, and a wiry rapid pulse.", ingredients.zhiZiQingGanTang),
  taoHongSiWuTang: formula("桃红四物汤", "Tao Hong Si Wu Tang", ["Nourishes and moves Blood", "Dispels stasis", "Softens masses"], "Long-standing firm goitre with dark complexion, purple tongue, and Blood stasis.", ingredients.taoHongSiWuTang),
  yiGuanJian: formula("一贯煎", "Yi Guan Jian", ["Nourishes Liver Yin", "Moves constrained Qi", "Generates fluids"], "Yin deficiency with dry throat, irritability, thin body, and a red dry tongue.", ingredients.yiGuanJian),
  chuanXiongChaTiaoSan: formula("川芎茶调散", "Chuan Xiong Cha Tiao San", ["Disperses Wind-Cold", "Relieves headache"], "Acute headache with aversion to cold, nasal obstruction, and floating pulse.", ingredients.chuanXiongChaTiaoSan),
  xiongZhiShiGaoTang: formula("芎芷石膏汤", "Xiong Zhi Shi Gao Tang", ["Disperses Wind-Heat", "Clears Heat", "Relieves headache"], "Headache with fever, thirst, red eyes, and a floating rapid pulse.", ingredients.xiongZhiShiGaoTang),
  qiangHuoShengShiTang: formula("羌活胜湿汤", "Qiang Huo Sheng Shi Tang", ["Expels Wind-Damp", "Relieves pain"], "Heavy headache with body aches, aversion to cold, and a soggy pulse.", ingredients.qiangHuoShengShiTang),
  tianMaGouTengYin: formula("天麻钩藤饮", "Tian Ma Gou Teng Yin", ["Calms Liver Yang", "Extinguishes Wind", "Clears Heat"], "Headache or vertigo with tinnitus, irritability, insomnia, and wiry pulse.", ingredients.tianMaGouTengYin),
  longDanXieGanTang: formula("龙胆泻肝汤", "Long Dan Xie Gan Tang", ["Drains Liver Fire", "Clears Damp-Heat"], "Severe temporal headache or hypochondrial pain with bitter taste, red eyes, and wiry rapid pulse.", ingredients.longDanXieGanTang),
  zhenGanXiFengTang: formula("镇肝熄风汤", "Zhen Gan Xi Feng Tang", ["Subdues Liver Yang", "Extinguishes Wind", "Nourishes Yin"], "Headache, vertigo, tremor, or numbness with forceful wiry pulse.", ingredients.zhenGanXiFengTang),
  chaiHuShuGanSan: formula("柴胡疏肝散", "Chai Hu Shu Gan San", ["Spreads Liver Qi", "Moves constraint", "Stops pain"], "Distending headache or hypochondrial pain worsened by emotion and relieved by sighing.", ingredients.chaiHuShuGanSan),
  wuZhuYuTang: formula("吴茱萸汤", "Wu Zhu Yu Tang", ["Warms Liver and Stomach", "Descends rebellious Qi", "Stops pain"], "Vertex headache with cold limbs, nausea, vomiting, and a deep slow pulse.", ingredients.wuZhuYuTang),
  pingWeiSan: formula("平胃散", "Ping Wei San", ["Dries Dampness", "Moves Qi", "Harmonizes Stomach"], "Heavy headache with body heaviness, epigastric fullness, and thick greasy coat.", ingredients.pingWeiSan),
  banXiaBaiZhuTianMaTang: formula("半夏白术天麻汤", "Ban Xia Bai Zhu Tian Ma Tang", ["Transforms Phlegm", "Extinguishes Wind", "Stops dizziness"], "Headache or vertigo with nausea, chest oppression, and greasy coat.", ingredients.banXiaBaiZhuTianMaTang),
  baoHeWan: formula("保和丸", "Bao He Wan", ["Reduces food stagnation", "Harmonizes Stomach"], "Headache with epigastric fullness, foul belching, nausea, and thick coat.", ingredients.baoHeWan),
  tongQiaoHuoXueTang: formula("通窍活血汤", "Tong Qiao Huo Xue Tang", ["Moves Blood", "Opens orifices", "Stops fixed pain"], "Chronic fixed stabbing headache, often after trauma, with a purple tongue.", ingredients.tongQiaoHuoXueTang),
  baiHuTang: formula("白虎汤", "Bai Hu Tang", ["Clears blazing Stomach Heat", "Generates fluids"], "Frontal headache with high fever, intense thirst, sweating, and surging pulse.", ingredients.baiHuTang),
  buZhongYiQiTang: formula("补中益气汤", "Bu Zhong Yi Qi Tang", ["Tonifies Qi", "Raises clear Yang"], "Dull headache worse with fatigue, shortness of breath, and weak pulse.", ingredients.buZhongYiQiTang),
  siWuTang: formula("四物汤", "Si Wu Tang", ["Nourishes Blood", "Regulates circulation"], "Dull headache with dizziness, pale complexion, palpitations, and fine pulse.", ingredients.siWuTang),
  zuoGuiWan: formula("左归丸", "Zuo Gui Wan", ["Nourishes Kidney Essence and Yin", "Fills marrow"], "Chronic empty headache or vertigo with weak back, tinnitus, and deficiency signs.", ingredients.zuoGuiWan),
  fuYuanHuoXueTang: formula("复元活血汤", "Fu Yuan Huo Xue Tang", ["Moves Blood", "Spreads Liver Qi", "Stops hypochondrial pain"], "Fixed stabbing hypochondrial pain after trauma or with clear Blood stasis signs.", ingredients.fuYuanHuoXueTang),
  yinChenHaoTang: formula("茵陈蒿汤", "Yin Chen Hao Tang", ["Clears Damp-Heat", "Relieves jaundice"], "Bright yellow jaundice with fever, thirst, scant dark urine, and yellow greasy coat.", ingredients.yinChenHaoTang),
  ganLuXiaoDuDan: formula("甘露消毒丹", "Gan Lu Xiao Du Dan", ["Clears Heat", "Transforms Dampness", "Relieves toxicity"], "Jaundice with Damp predominance, heaviness, nausea, low fever, and thick greasy coat.", ingredients.ganLuXiaoDuDan),
  qingWenBaiDuYin: formula("清瘟败毒饮", "Qing Wen Bai Du Yin", ["Clears severe Heat toxin", "Cools Blood", "Relieves jaundice"], "Rapid deep jaundice with high fever, delirium, bleeding, or severe toxic Heat signs.", ingredients.qingWenBaiDuYin),
  yinChenZhuFuTang: formula("茵陈术附汤", "Yin Chen Zhu Fu Tang", ["Warms Yang", "Transforms Cold-Damp", "Relieves jaundice"], "Dull dark jaundice with cold limbs, fatigue, poor appetite, and pale swollen tongue.", ingredients.yinChenZhuFuTang),
  xiaoChaiHuTang: formula("小柴胡汤", "Xiao Chai Hu Tang", ["Harmonizes Shaoyang", "Stops alternating chills and fever"], "Typical intermittent chills and fever with bitter taste, nausea, and wiry pulse.", ingredients.xiaoChaiHuTang),
  baiHuJiaGuiZhiTang: formula("白虎加桂枝汤", "Bai Hu Jia Gui Zhi Tang", ["Clears Heat", "Unblocks the exterior", "Stops warm malaria"], "Fever more pronounced than chills, thirst, sweating, and a rapid forceful pulse.", ingredients.baiHuJiaGuiZhiTang),
  chaiHuGuiZhiGanJiangTang: formula("柴胡桂枝干姜汤", "Chai Hu Gui Zhi Gan Jiang Tang", ["Harmonizes Shaoyang", "Warms Cold", "Transforms fluids"], "Chills more pronounced than fever, chest constraint, thirst, and a wiry slow pulse.", ingredients.chaiHuGuiZhiGanJiangTang),
  heRenYin: formula("何人饮", "He Ren Yin", ["Tonifies Qi and Blood", "Stops chronic malaria"], "Recurrent malaria with fatigue, weight loss, pale complexion, and weak pulse.", ingredients.heRenYin),
  qingZhangTang: formula("清瘴汤", "Qing Zhang Tang", ["Clears miasmic Heat", "Transforms Phlegm", "Stops malaria"], "Miasmic malaria with severe fever, headache, vomiting, confusion, and greasy coat.", ingredients.qingZhangTang),
  guiPiTang: formula("归脾汤", "Gui Pi Tang", ["Tonifies Qi and Blood", "Strengthens Spleen", "Nourishes Heart"], "Vertigo with pale complexion, fatigue, palpitations, poor appetite, and weak pulse.", ingredients.guiPiTang),
} satisfies Record<string, FormulaDetail>;

export const liverContent: Record<number, LungConditionDetail> = {
  22: {
    overview: "Goitre (Ying Bing) is swelling in the anterior neck caused chiefly by Qi constraint, Phlegm, Fire, Blood stasis, or Yin deficiency.",
    redFlags: ["Rapidly enlarging neck swelling", "Difficulty breathing or swallowing", "Hoarseness", "Hard fixed thyroid nodule", "Symptoms of severe thyroid dysfunction"],
    patterns: [
      { name: "Qi Stagnation with Phlegm", principle: "Move Liver Qi, transform Phlegm, soften swelling.", points: "CV 22, ST 9, LI 18, PC 6, LR 3, ST 40.", formula: formulas.haiZaoYuHuTang },
      { name: "Qi Stagnation with Spleen Qi Deficiency and Phlegm", principle: "Strengthen Spleen, move Qi, transform Phlegm.", points: "CV 22, ST 9, ST 36, BL 20, SP 6, ST 40.", formula: formulas.liuJunZiTang },
      { name: "Liver Fire Blazing with Phlegm-Heat", principle: "Drain Liver Fire, clear Phlegm-Heat, soften swelling.", points: "LR 2, LR 3, GB 34, ST 40, CV 22, LI 11.", formula: formulas.zhiZiQingGanTang },
      { name: "Phlegm and Blood Stasis", principle: "Transform Phlegm, move Blood, soften fixed masses.", points: "CV 22, ST 9, ST 40, SP 10, BL 17, LR 3.", formula: formulas.taoHongSiWuTang },
      { name: "Liver-Heart Yin Deficiency with Phlegm", principle: "Nourish Yin, soften Liver, transform Phlegm.", points: "KI 3, SP 6, LR 3, HT 7, ST 40, CV 22.", formula: formulas.yiGuanJian },
    ],
  },
  23: {
    overview: "Headache (Tou Tong) is differentiated by external Wind, internal Liver disorders, Phlegm, food, Blood stasis, Heat, or deficiency.",
    redFlags: ["Sudden worst headache", "Headache with weakness, speech or vision change", "Fever with stiff neck", "Head injury", "New headache during pregnancy or after age 50"],
    patterns: [
      { name: "Exterior Wind-Cold", principle: "Disperse Wind-Cold, unblock channels, stop pain.", points: "GB 20, GV 16, BL 10, LI 4, LU 7, TE 5.", formula: formulas.chuanXiongChaTiaoSan },
      { name: "Exterior Wind-Heat", principle: "Disperse Wind-Heat, clear the head, stop pain.", points: "GB 20, GV 14, LI 4, LI 11, TE 5, GB 14.", formula: formulas.xiongZhiShiGaoTang },
      { name: "Exterior Wind-Damp", principle: "Expel Wind-Damp, clear the head, stop pain.", points: "GB 20, GV 16, BL 10, SP 9, ST 40, LI 4.", formula: formulas.qiangHuoShengShiTang },
      { name: "Liver Yang Rising", principle: "Subdue Liver Yang, nourish Yin, stop headache.", points: "LR 3, KI 3, SP 6, GB 20, GB 34, GV 20.", formula: formulas.tianMaGouTengYin },
      { name: "Liver Fire", principle: "Drain Liver Fire, clear the head, stop pain.", points: "LR 2, LR 3, GB 20, GB 34, LI 11, Taiyang.", formula: formulas.longDanXieGanTang },
      { name: "Liver Wind", principle: "Extinguish Wind, subdue Yang, clear the head.", points: "LR 3, GB 20, GV 20, KI 3, SP 6, GB 34.", formula: formulas.zhenGanXiFengTang },
      { name: "Liver Qi Stagnation", principle: "Spread Liver Qi, move constraint, stop pain.", points: "LR 3, GB 34, PC 6, CV 17, Taiyang, Yintang.", formula: formulas.chaiHuShuGanSan },
      { name: "Cold Stagnation in Liver Channel", principle: "Warm Liver channel, scatter Cold, stop vertex pain.", points: "LR 3, LR 14, CV 4, ST 29, GV 20, KI 1. Use moxa.", formula: formulas.wuZhuYuTang },
      { name: "Dampness", principle: "Transform Dampness, strengthen Spleen, clear the head.", points: "SP 9, ST 36, CV 12, BL 20, ST 40, GV 20.", formula: formulas.pingWeiSan },
      { name: "Turbid Phlegm", principle: "Transform Phlegm, harmonize middle, clear the head.", points: "ST 40, CV 12, PC 6, SP 9, GB 20, GV 20.", formula: formulas.banXiaBaiZhuTianMaTang },
      { name: "Turbid Phlegm-Wind", principle: "Transform Phlegm, extinguish Wind, stop dizziness and pain.", points: "ST 40, LR 3, GB 20, GV 20, SP 6, PC 6.", formula: formulas.banXiaBaiZhuTianMaTang },
      { name: "Food Retention", principle: "Reduce food stagnation, harmonize Stomach, clear the head.", points: "CV 12, ST 36, ST 40, SP 4, PC 6, ST 44.", formula: formulas.baoHeWan },
      { name: "Blood Stasis", principle: "Move Blood, open collaterals, stop fixed pain.", points: "SP 10, BL 17, LR 3, LI 4, Taiyang, Ashi points.", formula: formulas.tongQiaoHuoXueTang },
      { name: "Stomach Heat", principle: "Clear Stomach Heat, raise clear Qi, stop frontal pain.", points: "ST 44, LI 11, ST 36, LI 4, Yintang, GB 14.", formula: formulas.baiHuTang },
      { name: "Qi Deficiency", principle: "Tonify Qi, raise clear Yang, stop headache.", points: "ST 36, CV 6, BL 20, GV 20, SP 6, LI 4.", formula: formulas.buZhongYiQiTang },
      { name: "Blood Deficiency", principle: "Nourish Blood, fill the channels, stop headache.", points: "SP 6, ST 36, BL 17, LR 8, HT 7, GV 20.", formula: formulas.siWuTang },
      { name: "Kidney Deficiency", principle: "Tonify Kidney Essence, nourish marrow, stop chronic headache.", points: "KI 3, BL 23, GV 20, GB 39, SP 6, CV 4.", formula: formulas.zuoGuiWan },
    ],
  },
  25: {
    overview: "Hypochondrial Pain (Xie Tong) involves pain beneath the ribs from Liver Qi constraint, Blood stasis, Damp-Heat, or Liver Blood/Yin deficiency.",
    redFlags: ["Severe right upper abdominal pain", "Fever with jaundice", "Persistent vomiting", "Chest pain or shortness of breath", "Recent trauma"],
    patterns: [
      { name: "Liver Qi Stagnation", principle: "Spread Liver Qi, harmonize collaterals, stop pain.", points: "LR 3, GB 34, LR 14, PC 6, TE 6, CV 17.", formula: formulas.chaiHuShuGanSan },
      { name: "Blood Stasis", principle: "Move Blood, disperse stasis, stop fixed pain.", points: "LR 3, LR 14, SP 10, BL 17, GB 34, Ashi points.", formula: formulas.fuYuanHuoXueTang },
      { name: "Damp-Heat in Liver and Gallbladder", principle: "Clear Liver-Gallbladder Damp-Heat, relieve pain.", points: "LR 2, GB 34, SP 9, LI 11, LR 14, GB 24.", formula: formulas.longDanXieGanTang },
      { name: "Liver Blood Deficiency", principle: "Nourish Liver Blood, soften Liver, relieve pain.", points: "LR 8, SP 6, BL 17, BL 18, ST 36, LR 14.", formula: formulas.siWuTang },
      { name: "Liver Yin Deficiency", principle: "Nourish Liver Yin, soften Liver, regulate Qi.", points: "KI 3, SP 6, LR 3, LR 8, BL 18, LR 14.", formula: formulas.yiGuanJian },
    ],
  },
  31: {
    overview: "Jaundice (Huang Dan) is yellowing of the eyes, skin, and urine due to Damp-Heat, Heat toxin, or Cold-Damp obstructing the middle burner.",
    redFlags: ["New jaundice", "Confusion or unusual sleepiness", "Fever with abdominal pain", "Vomiting blood or black stool", "Rapidly worsening yellowing"],
    patterns: [
      { name: "Yang Jaundice: Damp-Heat with Heat Predominant", principle: "Clear Heat, drain Dampness, relieve jaundice.", points: "GV 9, SP 9, GB 34, LI 11, ST 44, LR 3.", formula: formulas.yinChenHaoTang },
      { name: "Yang Jaundice: Damp-Heat with Damp Predominant", principle: "Transform Dampness, clear Heat, regulate middle burner.", points: "GV 9, SP 9, CV 12, ST 36, GB 34, BL 20.", formula: formulas.ganLuXiaoDuDan },
      { name: "Extreme Repletion of Heat Toxins", principle: "Clear Heat toxin, cool Blood, open orifices.", points: "GV 14, LI 11, PC 8, LR 2, SP 10, 12 Jing-well points.", formula: formulas.qingWenBaiDuYin },
      { name: "Yin Jaundice: Cold-Damp in Middle Burner", principle: "Warm middle, transform Cold-Damp, relieve jaundice.", points: "GV 9, CV 12, ST 36, SP 9, BL 20, GV 4. Use moxa.", formula: formulas.yinChenZhuFuTang },
    ],
  },
  34: {
    overview: "Malaria (Nue Ji) refers to periodic chills and fever caused by pathogens lodged between the exterior and interior, with Heat, Cold, deficiency, or miasmic variants.",
    redFlags: ["Recent travel to a malaria region", "High fever with confusion", "Seizure", "Breathing difficulty", "Pregnancy or severe weakness"],
    patterns: [
      { name: "Typical Malaria", principle: "Harmonize Shaoyang, expel pathogen, stop alternating chills and fever.", points: "TE 5, GB 41, GB 20, GV 14, LI 4, LR 3.", formula: formulas.xiaoChaiHuTang },
      { name: "Warm Malaria", principle: "Clear Heat, harmonize Shaoyang, stop malaria.", points: "GV 14, LI 11, TE 5, GB 41, ST 44, PC 8.", formula: formulas.baiHuJiaGuiZhiTang },
      { name: "Cold Malaria", principle: "Warm Cold, harmonize Shaoyang, transform fluids.", points: "TE 5, GB 41, CV 12, ST 36, SP 6, GV 14. Use moxa.", formula: formulas.chaiHuGuiZhiGanJiangTang },
      { name: "Taxation Malaria", principle: "Tonify Qi and Blood, support upright Qi, eliminate lingering pathogen.", points: "ST 36, CV 6, SP 6, BL 20, TE 5, GB 41.", formula: formulas.heRenYin },
      { name: "Miasmic Malaria", principle: "Clear miasmic toxin, transform Phlegm, open orifices.", points: "GV 14, GV 26, PC 6, ST 40, LI 11, TE 5.", formula: formulas.qingZhangTang },
    ],
  },
  43: {
    overview: "Vertigo (Xuan Yun) includes dizziness, spinning, disequilibrium, or visual dimness caused by Liver Yang/Wind, Phlegm, Qi-Blood deficiency, or Kidney Essence deficiency.",
    redFlags: ["Sudden vertigo with weakness or speech change", "New severe headache", "Inability to walk", "Chest pain or fainting", "Persistent vomiting or hearing loss"],
    patterns: [
      { name: "Liver Yang, Liver Fire, or Liver Wind Rising", principle: "Subdue Liver Yang, extinguish Wind, clear the head.", points: "LR 3, GB 20, GV 20, KI 3, SP 6, GB 34.", formula: formulas.tianMaGouTengYin },
      { name: "Turbid Phlegm in Head / Phlegm Retention in Middle Burner", principle: "Transform Phlegm, strengthen Spleen, clear the head.", points: "ST 40, CV 12, PC 6, SP 9, ST 36, GV 20.", formula: formulas.banXiaBaiZhuTianMaTang },
      { name: "Qi and Blood Deficiency", principle: "Tonify Qi and Blood, nourish the head and eyes.", points: "ST 36, SP 6, CV 6, BL 17, BL 20, GV 20.", formula: formulas.guiPiTang },
      { name: "Kidney Essence Deficiency", principle: "Tonify Kidney Essence, nourish marrow, stabilize vertigo.", points: "KI 3, BL 23, GV 20, GB 39, CV 4, SP 6.", formula: formulas.zuoGuiWan },
    ],
  },
};
