export const sectionLecturePoints: Record<string, string> = {
  "4|epistaxis|lung heat": "GB 20, LI 20, LI 4, LI 11",
  "4|epistaxis|stomach heat": "ST 44, SP 1, GV 23, LI 2",
  "4|epistaxis|liver fire": "LR 2, BL 40, GV 27, LR 8, BL 45",
  "4|epistaxis|liver-kidney yin deficiency": "BL 23, KI 3, KI 1, LR 3, BL 7",
  "4|epistaxis|spleen qi failing to control blood": "CV 12, BL 20, ST 36, SP 1",
  "4|coughing blood|wind-dry heat": "LU 11, LI 4, BL 12, LU 6, LU 9, CV 12, SP 6",
  "4|coughing blood|liver fire invading lung": "LR 2, LI 11, SP 10, BL 17, LU 10, LU 6",
  "4|coughing blood|lung yin deficiency with empty heat": "LU 9, CV 12, SP 6, ST 36, KI 3, LU 10, LU 6",
  "4|vomiting blood|stomach heat": "CV 12, PC 6, TE 6, LI 4, LI 11, ST 44",
  "4|vomiting blood|liver fire invading stomach": "LI 4, LI 11, LR 14, LR 2, LR 3",
  "4|vomiting blood|spleen-stomach qi deficiency": "CV 12, CV 6, SP 8, PC 6, ST 36, ST 34",
  "4|blood in stool|damp-heat in intestines": "ST 37, ST 25, ST 40, ST 44, LI 4, LI 11",
  "4|blood in stool|spleen-stomach deficient cold": "ST 37, ST 25, ST 36, CV 12, BL 20, BL 21",
  "4|blood in urine|bladder heat / heart fire": "HT 8, CV 3, BL 28, LI 11, SP 10, BL 63",
  "4|blood in urine|kidney yin deficiency with empty heat": "KI 3, KI 6, CV 4, SP 6, KI 5, CV 3, BL 28, KI 2, SP 10",
  "4|blood in urine|spleen failing to control blood": "ST 36, SP 6, CV 12, BL 20, BL 21, CV 6, SP 10, BL 63, BL 23, BL 28, GV 20",
  "4|blood in urine|kidney qi not firm": "BL 23, BL 28, BL 20, BL 17, SP 10, KI 3",
  "4|petechiae|blood heat": "LI 11, SP 10, KI 2, LR 3, SP 6, SP 4",
  "4|petechiae|yin deficiency with empty heat": "KI 3, KI 6, CV 4, SP 6, KI 2, LR 3, LI 11, SP 10",
  "4|petechiae|qi deficiency not holding blood": "ST 36, SP 6, CV 12, BL 20, BL 21, CV 6, SP 10, LU 9, SP 4",
  "4|bleeding gums|stomach heat": "LI 4, LI 11, LI 7, ST 21, ST 34, ST 44",
  "4|bleeding gums|stomach yin deficiency with empty heat": "ST 36, SP 6, CV 12, ST 44, LI 4, ST 34, LI 11, SP 10",
  "4|bleeding gums|stomach-spleen deficiency": "ST 36, SP 6, CV 12, BL 20, BL 21, LI 4, ST 34, BL 17",
};

export const sectionLectureTechniques: Record<string, string[]> = {
  "4|epistaxis|lung heat": ["Reducing method."],
  "4|epistaxis|stomach heat": ["Reducing method."],
  "4|epistaxis|liver fire": ["Reducing method."],
  "4|epistaxis|liver-kidney yin deficiency": ["Even method."],
  "4|epistaxis|spleen qi failing to control blood": ["Reinforcing method.", "Moxa is specified by the course protocol."],
  "4|coughing blood|wind-dry heat": ["Mixed point-specific methods; follow the course protocol."],
  "4|coughing blood|lung yin deficiency with empty heat": ["Mixed point-specific methods; follow the course protocol."],
  "4|vomiting blood|stomach heat": ["Reducing method."],
  "4|vomiting blood|liver fire invading stomach": ["Reducing method."],
  "4|vomiting blood|spleen-stomach qi deficiency": ["Reinforcing method."],
  "4|blood in stool|damp-heat in intestines": ["Reducing method."],
  "4|blood in stool|spleen-stomach deficient cold": ["Reinforcing method.", "Moxa is specified by the course protocol."],
  "4|blood in urine|bladder heat / heart fire": ["Reducing method."],
  "4|blood in urine|kidney yin deficiency with empty heat": ["Mixed reinforcing and even methods; follow the course protocol point by point."],
  "4|blood in urine|spleen failing to control blood": ["Reinforcing method.", "Moxa is specified by the course protocol."],
  "4|blood in urine|kidney qi not firm": ["Reinforcing method.", "Moxa is specified by the course protocol."],
  "4|petechiae|blood heat": ["Reducing method."],
  "4|petechiae|yin deficiency with empty heat": ["Mixed reinforcing and even methods; follow the course protocol point by point.", "No moxa."],
  "4|petechiae|qi deficiency not holding blood": ["Reinforcing method."],
  "4|bleeding gums|stomach heat": ["Reducing method.", "No moxa."],
  "4|bleeding gums|stomach yin deficiency with empty heat": ["Mixed reinforcing and even methods; follow the course protocol point by point.", "No moxa."],
  "4|bleeding gums|stomach-spleen deficiency": ["Mixed reinforcing and even methods; follow the course protocol point by point."],
};
