import type { FormulaDetail, LungConditionDetail } from "./lungContent";

const formulas = {
  chaiHuShuGanSan: {
    chineseName: "柴胡疏肝散",
    pinyin: "Chai Hu Shu Gan San",
    actions: ["Spreads Liver Qi", "Harmonizes Stomach", "Stops pain"],
    indications: "Pain or distention worsened by emotion, frequent sighing, belching, wiry pulse.",
  },
  baoHeWan: {
    chineseName: "保和丸",
    pinyin: "Bao He Wan",
    actions: ["Reduces food stagnation", "Harmonizes Stomach", "Transforms turbidity"],
    indications: "Fullness, foul belching, nausea, acid regurgitation, loose stool or constipation after overeating.",
  },
  xueFuZhuYuTang: {
    chineseName: "血府逐瘀汤",
    pinyin: "Xue Fu Zhu Yu Tang",
    actions: ["Moves Blood", "Moves Qi", "Unblocks stasis pain"],
    indications: "Fixed or stabbing pain with dark complexion, purple tongue, stasis signs, or chronic obstruction.",
  },
  liangFuWan: {
    chineseName: "良附丸",
    pinyin: "Liang Fu Wan",
    actions: ["Warms Stomach", "Moves Qi", "Stops pain"],
    indications: "Cold epigastric or abdominal pain relieved by warmth, worse with cold food/drink.",
  },
  zuoJinWan: {
    chineseName: "左金丸",
    pinyin: "Zuo Jin Wan",
    actions: ["Clears Liver/Stomach Heat", "Descends rebellious Qi", "Stops acid regurgitation"],
    indications: "Burning epigastric pain, acid reflux, bitter taste, irritability, red tongue, wiry rapid pulse.",
  },
  qingZhongTang: {
    chineseName: "清中汤",
    pinyin: "Qing Zhong Tang",
    actions: ["Clears Stomach Heat", "Harmonizes middle burner", "Stops pain"],
    indications: "Burning epigastric pain, thirst, bad breath, constipation, red tongue with yellow coat.",
  },
  shiXiaoSan: {
    chineseName: "失笑散",
    pinyin: "Shi Xiao San",
    actions: ["Moves Blood", "Dispels stasis", "Stops pain"],
    indications: "Fixed stabbing abdominal or epigastric pain, dark complexion, purple tongue or stasis spots.",
  },
  huangQiJianZhongTang: {
    chineseName: "黄芪建中汤",
    pinyin: "Huang Qi Jian Zhong Tang",
    actions: ["Warms and tonifies middle burner", "Relieves deficiency pain", "Supports Qi"],
    indications: "Dull pain relieved by pressure/warmth, fatigue, poor appetite, loose stool, pale tongue.",
  },
  yiGuanJian: {
    chineseName: "一贯煎",
    pinyin: "Yi Guan Jian",
    actions: ["Nourishes Yin", "Soothe Liver", "Harmonizes Stomach"],
    indications: "Dull burning pain, dry mouth/throat, hunger without desire to eat, red dry tongue.",
  },
  daChengQiTang: {
    chineseName: "大承气汤",
    pinyin: "Da Cheng Qi Tang",
    actions: ["Purges Heat accumulation", "Moves stool", "Drains excess"],
    indications: "Severe constipation with abdominal fullness/pain, fever or tidal fever, dry yellow coat.",
  },
  maZiRenWan: {
    chineseName: "麻子仁丸",
    pinyin: "Ma Zi Ren Wan",
    actions: ["Moistens Intestines", "Drains Heat", "Unblocks stool"],
    indications: "Dry stool from Heat or fluid deficiency, mild abdominal fullness, dry mouth.",
  },
  jiChuanJian: {
    chineseName: "济川煎",
    pinyin: "Ji Chuan Jian",
    actions: ["Warms Kidney", "Moistens Intestines", "Promotes bowel movement"],
    indications: "Constipation in elderly/deficiency patients with cold lower back, clear urine, pale tongue.",
  },
  siJunZiTang: {
    chineseName: "四君子汤",
    pinyin: "Si Jun Zi Tang",
    actions: ["Tonifies Spleen Qi", "Strengthens transformation", "Supports middle burner"],
    indications: "Fatigue, poor appetite, loose stool, weak limbs, pale tongue, weak pulse.",
  },
  liuJunZiTang: {
    chineseName: "六君子汤",
    pinyin: "Liu Jun Zi Tang",
    actions: ["Tonifies Spleen Qi", "Transforms Phlegm", "Harmonizes Stomach"],
    indications: "Spleen deficiency with nausea, phlegm, poor appetite, loose stool, greasy coat.",
  },
  shenLingBaiZhuSan: {
    chineseName: "参苓白术散",
    pinyin: "Shen Ling Bai Zhu San",
    actions: ["Tonifies Spleen", "Drains Dampness", "Stops diarrhea"],
    indications: "Chronic loose stool, poor appetite, fatigue, abdominal bloating, pale tongue.",
  },
  liZhongWan: {
    chineseName: "理中丸",
    pinyin: "Li Zhong Wan",
    actions: ["Warms middle burner", "Dispels Cold", "Stops vomiting/diarrhea"],
    indications: "Cold deficiency vomiting or diarrhea with cold abdomen, no thirst, pale tongue.",
  },
  siShenWan: {
    chineseName: "四神丸",
    pinyin: "Si Shen Wan",
    actions: ["Warms Kidney and Spleen", "Binds Intestines", "Stops dawn diarrhea"],
    indications: "Early morning diarrhea, cold abdomen, cold limbs, soreness of low back/knees.",
  },
  geGenQinLianTang: {
    chineseName: "葛根芩连汤",
    pinyin: "Ge Gen Qin Lian Tang",
    actions: ["Clears Damp-Heat", "Releases exterior", "Stops diarrhea/dysentery"],
    indications: "Diarrhea or dysentery with burning anus, fever, thirst, foul stool, yellow greasy coat.",
  },
  huoXiangZhengQiSan: {
    chineseName: "藿香正气散",
    pinyin: "Huo Xiang Zheng Qi San",
    actions: ["Transforms Dampness", "Releases exterior", "Harmonizes middle burner"],
    indications: "Nausea, vomiting, diarrhea, chest/epigastric oppression with exterior Damp or summer Damp.",
  },
  pingWeiSan: {
    chineseName: "平胃散",
    pinyin: "Ping Wei San",
    actions: ["Dries Dampness", "Moves Qi", "Harmonizes Stomach"],
    indications: "Epigastric fullness, poor appetite, nausea, heavy body, thick greasy coat.",
  },
  xiaoYaoSan: {
    chineseName: "逍遥散",
    pinyin: "Xiao Yao San",
    actions: ["Soothe Liver", "Strengthens Spleen", "Harmonizes middle burner"],
    indications: "Digestive symptoms worse with stress, hypochondriac tension, fatigue, wiry pulse.",
  },
  xuanFuDaiZheTang: {
    chineseName: "旋覆代赭汤",
    pinyin: "Xuan Fu Dai Zhe Tang",
    actions: ["Descends rebellious Stomach Qi", "Transforms Phlegm", "Tonifies deficiency"],
    indications: "Belching, hiccup, nausea or vomiting with epigastric hardness and weak Stomach Qi.",
  },
  wenDanTang: {
    chineseName: "温胆汤",
    pinyin: "Wen Dan Tang",
    actions: ["Clears Phlegm-Heat", "Harmonizes Stomach", "Descends rebellious Qi"],
    indications: "Nausea, epigastric oppression, bitter taste, dizziness, greasy yellow coat, slippery rapid pulse.",
  },
  dingXiangShiDiTang: {
    chineseName: "丁香柿蒂汤",
    pinyin: "Ding Xiang Shi Di Tang",
    actions: ["Warms Stomach", "Descends rebellious Qi", "Stops hiccup"],
    indications: "Cold hiccup or belching with cold epigastrium, clear fluids, pale tongue.",
  },
  zhuYeShiGaoTang: {
    chineseName: "竹叶石膏汤",
    pinyin: "Zhu Ye Shi Gao Tang",
    actions: ["Clears Heat", "Benefits Qi and Yin", "Harmonizes Stomach"],
    indications: "Residual Heat injuring Qi/Yin with thirst, dry mouth, nausea, and red tongue.",
  },
  shaShenMaiDongTang: {
    chineseName: "沙参麦冬汤",
    pinyin: "Sha Shen Mai Dong Tang",
    actions: ["Nourishes Stomach/Lung Yin", "Generates fluids", "Clears mild Heat"],
    indications: "Dry mouth/throat, poor appetite, dry retching, red peeled tongue.",
  },
  zengYeTang: {
    chineseName: "增液汤",
    pinyin: "Zeng Ye Tang",
    actions: ["Nourishes Yin", "Generates fluids", "Moistens Intestines"],
    indications: "Dry constipation or wasting-thirst with dry mouth, thirst, red dry tongue.",
  },
  baiTouWengTang: {
    chineseName: "白头翁汤",
    pinyin: "Bai Tou Weng Tang",
    actions: ["Clears Heat toxin", "Cools Blood", "Stops dysentery"],
    indications: "Dysentery with pus and blood, tenesmus, burning anus, fever, thirst.",
  },
  zhenRenYangZangTang: {
    chineseName: "真人养脏汤",
    pinyin: "Zhen Ren Yang Zang Tang",
    actions: ["Warms and tonifies Spleen/Kidney", "Binds Intestines", "Stops chronic dysentery"],
    indications: "Chronic dysentery or diarrhea with cold pain, fatigue, prolapse tendency, pale tongue.",
  },
  qiGeSan: {
    chineseName: "启膈散",
    pinyin: "Qi Ge San",
    actions: ["Opens diaphragm", "Moves Qi", "Transforms Phlegm"],
    indications: "Dysphagia with obstruction sensation, phlegm, chest/diaphragm oppression.",
  },
  tongYouTang: {
    chineseName: "通幽汤",
    pinyin: "Tong You Tang",
    actions: ["Nourishes Blood", "Moves stasis", "Unblocks obstruction"],
    indications: "Dysphagia from dryness/stasis with difficult swallowing and dry stool.",
  },
} satisfies Record<string, FormulaDetail>;

export const spleenContent: Record<number, LungConditionDetail> = {
  1: {
    overview: "Abdominal Mass / Ji Ju covers palpable or subjective abdominal accumulations. Ju masses are more Qi-based and mobile; Ji masses are more Blood-based, fixed, and deeper.",
    redFlags: ["New, growing, hard, or fixed abdominal mass", "Unexplained weight loss", "Blood in stool or black stool", "Persistent vomiting or severe pain"],
    patterns: [
      { name: "Qi Mass: Liver Qi Stagnation", principle: "Soothe Liver, regulate Qi, soften mass.", points: "LR 3, LR 14, CV 12, CV 6, ST 25, SP 15.", formula: formulas.chaiHuShuGanSan },
      { name: "Qi Mass: Retention of Food and Phlegm", principle: "Reduce food stagnation, transform Phlegm, move Qi.", points: "CV 12, ST 25, ST 40, ST 36, SP 4, PC 6.", formula: formulas.baoHeWan },
      { name: "Blood Mass: Stagnation of Qi and Blood", principle: "Move Qi, invigorate Blood, soften mass.", points: "LR 3, SP 10, BL 17, CV 6, ST 25, SP 15.", formula: formulas.xueFuZhuYuTang },
      { name: "Blood Mass: Blood Stasis Knotted in the Interior", principle: "Break stasis, soften hardness, relieve pain.", points: "SP 10, BL 17, ST 25, CV 6, LR 3, SP 6.", formula: formulas.shiXiaoSan },
      { name: "Blood Mass: Deficiency of Upright Qi with Blood Stasis", principle: "Support upright Qi, move Blood, soften mass.", points: "ST 36, CV 6, SP 6, BL 20, BL 17, SP 10.", formula: formulas.huangQiJianZhongTang },
    ],
  },
  2: {
    overview: "Abdominal Pain (Fu Tong) is differentiated by Cold, Damp-Heat, food, Qi, Blood, or deficiency-Cold obstructing abdominal Qi dynamics.",
    redFlags: ["Severe sudden abdominal pain", "Rebound tenderness or rigid abdomen", "Fever with persistent vomiting", "Blood in stool", "Pregnancy with abdominal pain"],
    patterns: [
      { name: "Cold in the Intestines", principle: "Warm interior, scatter Cold, move Qi, stop pain.", points: "CV 12, CV 6, ST 25, ST 36, SP 6. Use moxa.", formula: formulas.liangFuWan },
      { name: "Damp-Heat in the Intestines", principle: "Clear Heat, transform Dampness, regulate intestines.", points: "ST 25, ST 37, LI 11, SP 9, CV 12.", formula: formulas.geGenQinLianTang },
      { name: "Food Retention", principle: "Reduce food stagnation, harmonize middle, stop pain.", points: "CV 12, ST 25, ST 36, SP 4, ST 40.", formula: formulas.baoHeWan },
      { name: "Qi Stagnation", principle: "Move Qi, soothe Liver, stop abdominal pain.", points: "LR 3, SP 4, PC 6, CV 12, ST 25, CV 6.", formula: formulas.chaiHuShuGanSan },
      { name: "Blood Stasis", principle: "Move Blood, transform stasis, unblock pain.", points: "SP 10, BL 17, ST 25, CV 6, LR 3.", formula: formulas.shiXiaoSan },
      { name: "Qi Deficiency with Empty-Cold in the Abdomen", principle: "Tonify Qi, warm middle, stop deficiency pain.", points: "CV 6, CV 12, ST 36, BL 20, SP 6. Use moxa.", formula: formulas.huangQiJianZhongTang },
    ],
  },
  7: {
    overview: "Constipation (Bian Bi) is difficult, infrequent, or dry stool due to Heat, Qi stagnation, Cold, or deficiency of Qi, Yang, Blood, or Yin.",
    redFlags: ["New constipation after age 50", "Blood in stool", "Unexplained weight loss", "Severe abdominal pain/vomiting", "No gas or stool with distention"],
    patterns: [
      { name: "Chronic Interior Heat", principle: "Clear Heat, moisten intestines, unblock stool.", points: "ST 25, ST 37, LI 11, TE 6, SP 15.", formula: formulas.maZiRenWan },
      { name: "Acute Heat in Febrile Disease", principle: "Purge Heat, move stool, drain accumulation.", points: "ST 25, ST 37, LI 11, ST 44, TE 6.", formula: formulas.daChengQiTang },
      { name: "Liver Qi Stagnation", principle: "Move Qi, soothe Liver, unblock bowels.", points: "LR 3, SP 4, TE 6, ST 25, CV 6.", formula: formulas.chaiHuShuGanSan },
      { name: "Cold", principle: "Warm interior, disperse Cold, unblock stool.", points: "CV 6, CV 12, ST 25, ST 36, KI 7. Use moxa.", formula: formulas.jiChuanJian },
      { name: "Qi Deficiency", principle: "Tonify Qi, support bowel movement.", points: "ST 36, CV 6, BL 20, SP 6, ST 25.", formula: formulas.siJunZiTang },
      { name: "Yang Deficiency", principle: "Warm Yang, tonify Kidney/Spleen, unblock stool.", points: "CV 4, CV 6, GV 4, BL 23, ST 25. Use moxa.", formula: formulas.jiChuanJian },
      { name: "Blood Deficiency", principle: "Nourish Blood, moisten intestines.", points: "SP 6, BL 17, ST 36, ST 25, HT 7.", formula: formulas.maZiRenWan },
      { name: "Yin Deficiency", principle: "Nourish Yin, generate fluids, moisten stool.", points: "KI 6, SP 6, ST 36, ST 25, CV 12.", formula: formulas.zengYeTang },
    ],
  },
  9: {
    overview: "Consumptive Thirst / Xiao Ke centers on excessive thirst, hunger, urination, and wasting due to Heat and Yin-fluid depletion in the Lung, Stomach, and Kidney.",
    redFlags: ["Very high blood sugar symptoms", "Unexplained weight loss", "Excessive urination with dehydration", "Confusion, vomiting, fruity breath"],
    patterns: [
      { name: "Upper Xiao: Lung Heat Damaging Fluids", principle: "Clear Lung Heat, generate fluids, stop thirst.", points: "LU 5, LU 10, CV 12, ST 36, SP 6, KI 6.", formula: formulas.zhuYeShiGaoTang },
      { name: "Middle Xiao: Excessive Stomach Heat", principle: "Clear Stomach Heat, nourish fluids, reduce hunger/thirst.", points: "ST 44, ST 36, CV 12, SP 6, LI 11.", formula: formulas.qingZhongTang },
      { name: "Lower Xiao: Kidney Yin Deficiency", principle: "Nourish Kidney Yin, generate fluids, secure essence.", points: "KI 3, KI 6, SP 6, CV 4, BL 23.", formula: formulas.zengYeTang },
    ],
  },
  13: {
    overview: "Diarrhea (Xie Xie) is frequent loose stool from Dampness, food retention, Liver overacting, Spleen deficiency, or Kidney Yang deficiency.",
    redFlags: ["Blood or black stool", "High fever", "Severe dehydration", "Persistent diarrhea over several days", "Recent travel or antibiotic use with severe symptoms"],
    patterns: [
      { name: "Cold-Damp Retention", principle: "Warm middle, transform Cold-Damp, stop diarrhea.", points: "CV 12, ST 25, ST 36, SP 9, SP 6. Use moxa.", formula: formulas.huoXiangZhengQiSan },
      { name: "Damp-Heat Retention", principle: "Clear Damp-Heat, regulate intestines, stop diarrhea.", points: "ST 25, ST 37, LI 11, SP 9, CV 12.", formula: formulas.geGenQinLianTang },
      { name: "Food Retention", principle: "Reduce food stagnation, harmonize intestines.", points: "CV 12, ST 25, ST 36, SP 4, ST 40.", formula: formulas.baoHeWan },
      { name: "Liver Qi Stagnation", principle: "Soothe Liver, strengthen Spleen, stop diarrhea.", points: "LR 3, SP 4, PC 6, ST 25, ST 36.", formula: formulas.xiaoYaoSan },
      { name: "Spleen-Stomach Deficiency", principle: "Tonify Spleen/Stomach Qi, transform Dampness.", points: "ST 36, CV 12, BL 20, SP 6, ST 25.", formula: formulas.shenLingBaiZhuSan },
      { name: "Kidney Yang Deficiency", principle: "Warm Kidney Yang, strengthen Spleen, stop dawn diarrhea.", points: "CV 4, GV 4, BL 23, ST 36, SP 6. Use moxa.", formula: formulas.siShenWan },
    ],
  },
  14: {
    overview: "Drum Distension (Gu Zhang) is abdominal distention with fluid, Qi, Blood, Dampness, or deficiency, clinically overlapping with ascites-type presentations.",
    redFlags: ["New abdominal swelling", "Jaundice", "Shortness of breath", "Fever with abdominal pain", "Vomiting blood or black stool"],
    patterns: [
      { name: "Qi Stagnation with Damp Obstruction", principle: "Move Qi, transform Dampness, reduce distention.", points: "LR 3, SP 9, CV 9, CV 12, ST 25, SP 6.", formula: formulas.chaiHuShuGanSan },
      { name: "Cold-Damp Blocking Spleen", principle: "Warm Spleen, transform Cold-Damp, move water.", points: "CV 9, CV 12, ST 36, SP 9, BL 20. Use moxa.", formula: formulas.pingWeiSan },
      { name: "Damp-Heat Accumulation", principle: "Clear Damp-Heat, move water, reduce distention.", points: "SP 9, CV 9, ST 25, LI 11, ST 36.", formula: formulas.geGenQinLianTang },
      { name: "Spleen Qi Stagnation with Liver Blood Stasis", principle: "Tonify Spleen, move Liver Qi and Blood.", points: "ST 36, SP 6, LR 3, SP 10, BL 17, CV 6.", formula: formulas.xueFuZhuYuTang },
      { name: "Spleen-Kidney Yang Deficiency", principle: "Warm Spleen/Kidney Yang, move water.", points: "CV 4, CV 6, GV 4, BL 20, BL 23, SP 9. Use moxa.", formula: formulas.liZhongWan },
      { name: "Liver-Kidney Yin Deficiency", principle: "Nourish Liver/Kidney Yin, soften Liver, move water gently.", points: "KI 3, SP 6, BL 18, BL 23, CV 4, SP 9.", formula: formulas.yiGuanJian },
    ],
  },
  15: {
    overview: "Dysentery (Li Ji) presents with abdominal pain, tenesmus, and stool containing mucus, pus, or blood.",
    redFlags: ["Blood in stool with fever", "Severe dehydration", "Persistent abdominal pain", "Recent travel outbreak symptoms", "Immunocompromised patient"],
    patterns: [
      { name: "Damp-Heat Dysentery", principle: "Clear Damp-Heat, cool Blood, stop dysentery.", points: "ST 25, ST 37, LI 11, SP 9, SP 6.", formula: formulas.geGenQinLianTang },
      { name: "Epidemic Toxic Dysentery", principle: "Clear Heat toxin, cool Blood, open obstruction.", points: "LI 11, ST 25, ST 37, GV 14, SP 10.", formula: formulas.baiTouWengTang },
      { name: "Cold-Damp Dysentery", principle: "Warm middle, transform Cold-Damp, stop dysentery.", points: "CV 12, ST 25, ST 36, SP 9, BL 20. Use moxa.", formula: formulas.huoXiangZhengQiSan },
      { name: "Yin Deficiency Dysentery", principle: "Nourish Yin, clear empty Heat, stop dysentery.", points: "KI 3, SP 6, ST 36, ST 25, BL 23.", formula: formulas.shaShenMaiDongTang },
      { name: "Deficient Cold Dysentery", principle: "Warm and tonify Spleen/Kidney, bind intestines.", points: "CV 6, CV 12, ST 36, BL 20, BL 23. Use moxa.", formula: formulas.zhenRenYangZangTang },
      { name: "Intermittent Dysentery", principle: "Tonify Spleen, regulate intestines, clear lingering pathogen.", points: "ST 36, CV 12, ST 25, SP 6, SP 9.", formula: formulas.shenLingBaiZhuSan },
      { name: "Food-Resistant Dysentery", principle: "Reduce food stagnation, harmonize intestines.", points: "CV 12, ST 25, ST 37, SP 4, ST 40.", formula: formulas.baoHeWan },
    ],
  },
  16: {
    overview: "Dysphagia Occlusion Syndrome (Ye Ge) is difficulty swallowing with obstruction, often involving Qi, Phlegm, Heat, Yin depletion, Blood stasis, or Yang/Qi collapse.",
    redFlags: ["Progressive difficulty swallowing", "Unexplained weight loss", "Vomiting blood", "Choking/aspiration", "New dysphagia in older adults"],
    patterns: [
      { name: "Congestion of Qi and Phlegm", principle: "Move Qi, transform Phlegm, open diaphragm.", points: "CV 17, CV 22, PC 6, ST 40, CV 12, LR 3.", formula: formulas.qiGeSan },
      { name: "Depletion of Fluids with Accumulation of Heat", principle: "Nourish Yin, clear Heat, moisten throat/Stomach.", points: "KI 6, SP 6, CV 12, ST 36, LU 10.", formula: formulas.shaShenMaiDongTang },
      { name: "Accumulation of Blood Stasis", principle: "Move Blood, transform stasis, unblock diaphragm.", points: "BL 17, SP 10, PC 6, CV 17, LR 3.", formula: formulas.tongYouTang },
      { name: "Deficiency of Qi with Devitalization of Yang", principle: "Tonify Qi, warm Yang, support swallowing.", points: "CV 6, CV 12, ST 36, BL 20, GV 4. Use moxa.", formula: formulas.huangQiJianZhongTang },
    ],
  },
  19: {
    overview: "Epigastric Pain (Wei Tong) involves Stomach Qi obstruction or malnourishment from Cold, food, Liver overacting, Heat, Phlegm, Dampness, Blood stasis, or deficiency.",
    redFlags: ["Severe or sudden epigastric pain", "Black stool or vomiting blood", "Unexplained weight loss", "Persistent vomiting", "Chest pain mimicking epigastric pain"],
    patterns: [
      { name: "Cold Invading Stomach", principle: "Warm Stomach, scatter Cold, stop pain.", points: "CV 12, ST 36, ST 34, PC 6. Use moxa.", formula: formulas.liangFuWan },
      { name: "Food Retention", principle: "Reduce food stagnation, harmonize Stomach.", points: "CV 12, ST 21, ST 36, SP 4, ST 40.", formula: formulas.baoHeWan },
      { name: "Liver Qi Invading Stomach", principle: "Soothe Liver, harmonize Stomach, stop pain.", points: "LR 3, PC 6, CV 12, ST 21, SP 4.", formula: formulas.chaiHuShuGanSan },
      { name: "Stomach Fire", principle: "Clear Stomach Heat, harmonize middle.", points: "ST 44, LI 11, CV 12, ST 36, PC 6.", formula: formulas.qingZhongTang },
      { name: "Stomach Phlegm-Fire", principle: "Clear Phlegm-Fire, harmonize Stomach.", points: "ST 40, ST 44, CV 12, PC 6, LI 11.", formula: formulas.wenDanTang },
      { name: "Stomach Damp-Heat", principle: "Clear Damp-Heat, harmonize Stomach.", points: "SP 9, ST 36, CV 12, ST 25, LI 11.", formula: formulas.pingWeiSan },
      { name: "Stomach and Liver Heat", principle: "Clear Liver/Stomach Heat, descend rebellious Qi.", points: "LR 2, ST 44, CV 12, PC 6, LR 3.", formula: formulas.zuoJinWan },
      { name: "Blood Stasis in Stomach", principle: "Move Blood, transform stasis, stop fixed pain.", points: "BL 17, SP 10, CV 12, ST 34, PC 6.", formula: formulas.shiXiaoSan },
      { name: "Phlegm-Fluids in Stomach", principle: "Transform Phlegm-fluid, harmonize Stomach, descend Qi.", points: "ST 40, CV 12, CV 9, PC 6, ST 36.", formula: formulas.liuJunZiTang },
      { name: "Stomach-Spleen Deficient Cold", principle: "Warm and tonify middle burner, stop pain.", points: "CV 12, CV 6, ST 36, BL 20, SP 6. Use moxa.", formula: formulas.huangQiJianZhongTang },
      { name: "Stomach Yin Deficiency", principle: "Nourish Stomach Yin, harmonize middle.", points: "KI 6, SP 6, ST 36, CV 12, ST 44.", formula: formulas.yiGuanJian },
    ],
  },
  24: {
    overview: "Hiccoughing and Belching (E Ni) are rebellious Stomach Qi rising upward due to Cold, Heat, food, Liver Qi, Yang deficiency, or Yin deficiency.",
    patterns: [
      { name: "Stomach Cold", principle: "Warm Stomach, descend rebellious Qi, stop hiccup.", points: "CV 12, CV 13, ST 36, PC 6. Use moxa.", formula: formulas.dingXiangShiDiTang },
      { name: "Effulgent Stomach Fire", principle: "Clear Stomach Fire, descend Qi.", points: "ST 44, CV 12, PC 6, LI 11.", formula: formulas.zhuYeShiGaoTang },
      { name: "Liver Qi Stagnation", principle: "Soothe Liver, harmonize Stomach, descend Qi.", points: "LR 3, PC 6, CV 17, CV 12, ST 36.", formula: formulas.chaiHuShuGanSan },
      { name: "Spleen-Stomach Yang Deficiency", principle: "Warm and tonify Spleen/Stomach, descend Qi.", points: "CV 12, CV 6, ST 36, BL 20. Use moxa.", formula: formulas.liZhongWan },
      { name: "Stomach Yin Deficiency", principle: "Nourish Stomach Yin, descend Qi.", points: "KI 6, SP 6, CV 12, ST 36, PC 6.", formula: formulas.shaShenMaiDongTang },
      { name: "Food Retention", principle: "Reduce food stagnation, harmonize Stomach, descend Qi.", points: "CV 12, ST 21, ST 36, SP 4, PC 6.", formula: formulas.baoHeWan },
    ],
  },
  44: {
    overview: "Vomiting (Ou Tu) is rebellious Stomach Qi with failure of descending, caused by exterior invasion, food, Phlegm-Damp, Liver overacting, deficiency Cold, or Stomach Yin deficiency.",
    redFlags: ["Persistent vomiting with dehydration", "Vomiting blood", "Severe abdominal pain", "Neurologic symptoms", "Pregnancy with severe vomiting"],
    patterns: [
      { name: "Exogenous Evils Invading Stomach", principle: "Release exterior, harmonize Stomach, stop vomiting.", points: "PC 6, CV 12, ST 36, LI 4, TE 5.", formula: formulas.huoXiangZhengQiSan },
      { name: "Food Retention", principle: "Reduce food stagnation, descend Stomach Qi.", points: "CV 12, ST 21, ST 36, SP 4, PC 6.", formula: formulas.baoHeWan },
      { name: "Phlegm-Damp Retention", principle: "Transform Phlegm-Damp, harmonize Stomach, stop vomiting.", points: "ST 40, CV 12, PC 6, ST 36, SP 9.", formula: formulas.liuJunZiTang },
      { name: "Liver Qi Invading Stomach", principle: "Soothe Liver, harmonize Stomach, descend Qi.", points: "LR 3, PC 6, CV 12, CV 17, ST 36.", formula: formulas.xiaoYaoSan },
      { name: "Spleen-Stomach Deficiency Cold", principle: "Warm middle, tonify Spleen/Stomach, stop vomiting.", points: "CV 12, CV 6, ST 36, BL 20. Use moxa.", formula: formulas.liZhongWan },
      { name: "Stomach Yin Deficiency", principle: "Nourish Stomach Yin, descend rebellious Qi.", points: "KI 6, SP 6, CV 12, ST 36, PC 6.", formula: formulas.shaShenMaiDongTang },
    ],
  },
};
