import type { FormulaDetail, FormulaIngredient, LungConditionDetail } from "./lungContent";

const ingredient = (chineseName: string, pinyin: string, dose: string): FormulaIngredient => ({
  chineseName,
  pinyin,
  englishName: "",
  dose,
});

const spleenIngredients = {
  chaiHuShuGanSan: [
    ingredient("陈皮", "Chen Pi", "6 g"), ingredient("柴胡", "Chai Hu", "6 g"),
    ingredient("川芎", "Chuan Xiong", "4.5 g"), ingredient("枳壳", "Zhi Ke", "4.5 g"),
    ingredient("芍药", "Shao Yao", "4.5 g"), ingredient("炙甘草", "Zhi Gan Cao", "1.5 g"),
    ingredient("香附", "Xiang Fu", "4.5 g"),
  ],
  baoHeWan: [
    ingredient("山楂", "Shan Zha", "180 g"), ingredient("神曲", "Shen Qu", "60 g"),
    ingredient("半夏", "Ban Xia", "90 g"), ingredient("茯苓", "Fu Ling", "90 g"),
    ingredient("陈皮", "Chen Pi", "30 g"), ingredient("连翘", "Lian Qiao", "30 g"),
    ingredient("莱菔子", "Lai Fu Zi", "30 g"),
  ],
  xueFuZhuYuTang: [
    ingredient("桃仁", "Tao Ren", "12 g"), ingredient("红花", "Hong Hua", "9 g"),
    ingredient("当归", "Dang Gui", "9 g"), ingredient("生地黄", "Sheng Di Huang", "9 g"),
    ingredient("川芎", "Chuan Xiong", "4.5 g"), ingredient("赤芍", "Chi Shao", "6 g"),
    ingredient("牛膝", "Niu Xi", "9 g"), ingredient("桔梗", "Jie Geng", "4.5 g"),
    ingredient("柴胡", "Chai Hu", "3 g"), ingredient("枳壳", "Zhi Ke", "6 g"),
    ingredient("甘草", "Gan Cao", "3 g"),
  ],
  liangFuWan: [
    ingredient("高良姜", "Gao Liang Jiang", "9 g"), ingredient("香附", "Xiang Fu", "9 g"),
  ],
  zuoJinWan: [
    ingredient("黄连", "Huang Lian", "18 g"), ingredient("吴茱萸", "Wu Zhu Yu", "3 g"),
  ],
  qingZhongTang: [
    ingredient("黄连", "Huang Lian", "6 g"), ingredient("栀子", "Zhi Zi", "6 g"),
    ingredient("陈皮", "Chen Pi", "4.5 g"), ingredient("茯苓", "Fu Ling", "4.5 g"),
    ingredient("半夏", "Ban Xia", "4.5 g"), ingredient("草豆蔻", "Cao Dou Kou", "3 g"),
    ingredient("甘草", "Gan Cao", "3 g"),
  ],
  shiXiaoSan: [
    ingredient("蒲黄", "Pu Huang", "6 g"), ingredient("五灵脂", "Wu Ling Zhi", "6 g"),
  ],
  huangQiJianZhongTang: [
    ingredient("桂枝", "Gui Zhi", "9 g"), ingredient("炙甘草", "Zhi Gan Cao", "6 g"),
    ingredient("大枣", "Da Zao", "6枚"), ingredient("芍药", "Shao Yao", "18 g"),
    ingredient("生姜", "Sheng Jiang", "9 g"), ingredient("饴糖", "Yi Tang", "30 g"),
    ingredient("黄芪", "Huang Qi", "15 g"),
  ],
  yiGuanJian: [
    ingredient("北沙参", "Bei Sha Shen", "9 g"), ingredient("麦冬", "Mai Dong", "9 g"),
    ingredient("当归身", "Dang Gui Shen", "9 g"), ingredient("生地黄", "Sheng Di Huang", "18 g"),
    ingredient("枸杞子", "Gou Qi Zi", "12 g"), ingredient("川楝子", "Chuan Lian Zi", "4.5 g"),
  ],
  daChengQiTang: [
    ingredient("大黄", "Da Huang", "12 g"), ingredient("厚朴", "Hou Po", "24 g"),
    ingredient("枳实", "Zhi Shi", "12 g"), ingredient("芒硝", "Mang Xiao", "9 g"),
  ],
  maZiRenWan: [
    ingredient("火麻仁", "Huo Ma Ren", "20 g"), ingredient("白芍", "Bai Shao", "9 g"),
    ingredient("枳实", "Zhi Shi", "9 g"), ingredient("大黄", "Da Huang", "12 g"),
    ingredient("厚朴", "Hou Po", "9 g"), ingredient("杏仁", "Xing Ren", "10 g"),
  ],
  jiChuanJian: [
    ingredient("肉苁蓉", "Rou Cong Rong", "9 g"), ingredient("当归", "Dang Gui", "15 g"),
    ingredient("牛膝", "Niu Xi", "6 g"), ingredient("泽泻", "Ze Xie", "4.5 g"),
    ingredient("升麻", "Sheng Ma", "3 g"), ingredient("枳壳", "Zhi Ke", "3 g"),
  ],
  siJunZiTang: [
    ingredient("人参", "Ren Shen", "9 g"), ingredient("白术", "Bai Zhu", "9 g"),
    ingredient("茯苓", "Fu Ling", "9 g"), ingredient("炙甘草", "Zhi Gan Cao", "6 g"),
  ],
  liuJunZiTang: [
    ingredient("人参", "Ren Shen", "9 g"), ingredient("白术", "Bai Zhu", "9 g"),
    ingredient("茯苓", "Fu Ling", "9 g"), ingredient("炙甘草", "Zhi Gan Cao", "6 g"),
    ingredient("陈皮", "Chen Pi", "3 g"), ingredient("半夏", "Ban Xia", "4.5 g"),
    ingredient("生姜", "Sheng Jiang", "3片"), ingredient("大枣", "Da Zao", "2枚"),
  ],
  shenLingBaiZhuSan: [
    ingredient("莲子", "Lian Zi", "15 g"), ingredient("薏苡仁", "Yi Yi Ren", "15 g"),
    ingredient("砂仁", "Sha Ren", "6 g"), ingredient("桔梗", "Jie Geng", "6 g"),
    ingredient("白扁豆", "Bai Bian Dou", "12 g"), ingredient("茯苓", "Fu Ling", "15 g"),
    ingredient("人参", "Ren Shen", "15 g"), ingredient("甘草", "Gan Cao", "9 g"),
    ingredient("白术", "Bai Zhu", "15 g"), ingredient("山药", "Shan Yao", "15 g"),
  ],
  liZhongWan: [
    ingredient("人参", "Ren Shen", "9 g"), ingredient("干姜", "Gan Jiang", "9 g"),
    ingredient("炙甘草", "Zhi Gan Cao", "9 g"), ingredient("白术", "Bai Zhu", "9 g"),
  ],
  siShenWan: [
    ingredient("肉豆蔻", "Rou Dou Kou", "60 g"), ingredient("补骨脂", "Bu Gu Zhi", "120 g"),
    ingredient("五味子", "Wu Wei Zi", "60 g"), ingredient("吴茱萸", "Wu Zhu Yu", "30 g"),
    ingredient("生姜", "Sheng Jiang", "适量"), ingredient("大枣", "Da Zao", "50枚"),
  ],
  geGenQinLianTang: [
    ingredient("葛根", "Ge Gen", "15 g"), ingredient("炙甘草", "Zhi Gan Cao", "6 g"),
    ingredient("黄芩", "Huang Qin", "9 g"), ingredient("黄连", "Huang Lian", "9 g"),
  ],
  huoXiangZhengQiSan: [
    ingredient("藿香", "Huo Xiang", "90 g"), ingredient("厚朴", "Hou Po", "60 g"),
    ingredient("陈皮", "Chen Pi", "60 g"), ingredient("紫苏叶", "Zi Su Ye", "30 g"),
    ingredient("白芷", "Bai Zhi", "30 g"), ingredient("半夏曲", "Ban Xia Qu", "60 g"),
    ingredient("大腹皮", "Da Fu Pi", "30 g"), ingredient("白术", "Bai Zhu", "60 g"),
    ingredient("茯苓", "Fu Ling", "30 g"), ingredient("桔梗", "Jie Geng", "60 g"),
    ingredient("炙甘草", "Zhi Gan Cao", "75 g"), ingredient("生姜", "Sheng Jiang", "3片"),
    ingredient("大枣", "Da Zao", "1枚"),
  ],
  pingWeiSan: [
    ingredient("苍术", "Cang Zhu", "12 g"), ingredient("厚朴", "Hou Po", "9 g"),
    ingredient("陈皮", "Chen Pi", "6 g"), ingredient("炙甘草", "Zhi Gan Cao", "3 g"),
    ingredient("生姜", "Sheng Jiang", "2片"), ingredient("大枣", "Da Zao", "2枚"),
  ],
  xiaoYaoSan: [
    ingredient("柴胡", "Chai Hu", "9 g"), ingredient("当归", "Dang Gui", "9 g"),
    ingredient("白芍", "Bai Shao", "9 g"), ingredient("白术", "Bai Zhu", "9 g"),
    ingredient("茯苓", "Fu Ling", "9 g"), ingredient("炙甘草", "Zhi Gan Cao", "4.5 g"),
    ingredient("薄荷", "Bo He", "3 g"), ingredient("生姜", "Sheng Jiang", "3片"),
  ],
  xuanFuDaiZheTang: [
    ingredient("旋覆花", "Xuan Fu Hua", "9 g"), ingredient("代赭石", "Dai Zhe Shi", "3 g"),
    ingredient("人参", "Ren Shen", "6 g"), ingredient("生姜", "Sheng Jiang", "15 g"),
    ingredient("半夏", "Ban Xia", "9 g"), ingredient("炙甘草", "Zhi Gan Cao", "9 g"),
    ingredient("大枣", "Da Zao", "4枚"),
  ],
  wenDanTang: [
    ingredient("半夏", "Ban Xia", "6 g"), ingredient("竹茹", "Zhu Ru", "6 g"),
    ingredient("枳实", "Zhi Shi", "6 g"), ingredient("陈皮", "Chen Pi", "9 g"),
    ingredient("甘草", "Gan Cao", "3 g"), ingredient("茯苓", "Fu Ling", "4.5 g"),
    ingredient("生姜", "Sheng Jiang", "5片"), ingredient("大枣", "Da Zao", "1枚"),
  ],
  dingXiangShiDiTang: [
    ingredient("丁香", "Ding Xiang", "6 g"), ingredient("柿蒂", "Shi Di", "9 g"),
    ingredient("人参", "Ren Shen", "3 g"), ingredient("生姜", "Sheng Jiang", "6 g"),
  ],
  zhuYeShiGaoTang: [
    ingredient("竹叶", "Zhu Ye", "6 g"), ingredient("石膏", "Shi Gao", "50 g"),
    ingredient("半夏", "Ban Xia", "9 g"), ingredient("麦冬", "Mai Dong", "20 g"),
    ingredient("人参", "Ren Shen", "6 g"), ingredient("炙甘草", "Zhi Gan Cao", "6 g"),
    ingredient("粳米", "Jing Mi", "10 g"),
  ],
  shaShenMaiDongTang: [
    ingredient("沙参", "Sha Shen", "9 g"), ingredient("玉竹", "Yu Zhu", "6 g"),
    ingredient("生甘草", "Sheng Gan Cao", "3 g"), ingredient("桑叶", "Sang Ye", "4.5 g"),
    ingredient("麦冬", "Mai Dong", "9 g"), ingredient("生扁豆", "Sheng Bian Dou", "4.5 g"),
    ingredient("天花粉", "Tian Hua Fen", "4.5 g"),
  ],
  zengYeTang: [
    ingredient("玄参", "Xuan Shen", "30 g"), ingredient("麦冬", "Mai Dong", "24 g"),
    ingredient("生地黄", "Sheng Di Huang", "24 g"),
  ],
  baiTouWengTang: [
    ingredient("白头翁", "Bai Tou Weng", "15 g"), ingredient("黄柏", "Huang Bai", "12 g"),
    ingredient("黄连", "Huang Lian", "6 g"), ingredient("秦皮", "Qin Pi", "12 g"),
  ],
  zhenRenYangZangTang: [
    ingredient("人参", "Ren Shen", "6 g"), ingredient("当归", "Dang Gui", "9 g"),
    ingredient("白术", "Bai Zhu", "9 g"), ingredient("肉豆蔻", "Rou Dou Kou", "6 g"),
    ingredient("肉桂", "Rou Gui", "3 g"), ingredient("炙甘草", "Zhi Gan Cao", "6 g"),
    ingredient("白芍", "Bai Shao", "12 g"), ingredient("木香", "Mu Xiang", "6 g"),
    ingredient("诃子", "He Zi", "9 g"), ingredient("罂粟壳", "Ying Su Ke", "9 g"),
  ],
  qiGeSan: [
    ingredient("沙参", "Sha Shen", "9 g"), ingredient("丹参", "Dan Shen", "9 g"),
    ingredient("茯苓", "Fu Ling", "9 g"), ingredient("川贝母", "Chuan Bei Mu", "4.5 g"),
    ingredient("郁金", "Yu Jin", "4.5 g"), ingredient("砂仁", "Sha Ren", "3 g"),
    ingredient("荷叶蒂", "He Ye Di", "2枚"),
  ],
  tongYouTang: [
    ingredient("生地黄", "Sheng Di Huang", "15 g"), ingredient("熟地黄", "Shu Di Huang", "15 g"),
    ingredient("桃仁", "Tao Ren", "9 g"), ingredient("红花", "Hong Hua", "3 g"),
    ingredient("当归", "Dang Gui", "9 g"), ingredient("升麻", "Sheng Ma", "3 g"),
    ingredient("炙甘草", "Zhi Gan Cao", "3 g"),
  ],
} satisfies Record<string, FormulaIngredient[]>;

const formulas = {
  chaiHuShuGanSan: {
    chineseName: "柴胡疏肝散",
    pinyin: "Chai Hu Shu Gan San",
    actions: ["Spreads Liver Qi", "Harmonizes Stomach", "Stops pain"],
    indications: "Pain or distention worsened by emotion, frequent sighing, belching, wiry pulse.",
    ingredients: spleenIngredients.chaiHuShuGanSan,
  },
  baoHeWan: {
    chineseName: "保和丸",
    pinyin: "Bao He Wan",
    actions: ["Reduces food stagnation", "Harmonizes Stomach", "Transforms turbidity"],
    indications: "Fullness, foul belching, nausea, acid regurgitation, loose stool or constipation after overeating.",
    ingredients: spleenIngredients.baoHeWan,
  },
  xueFuZhuYuTang: {
    chineseName: "血府逐瘀汤",
    pinyin: "Xue Fu Zhu Yu Tang",
    actions: ["Moves Blood", "Moves Qi", "Unblocks stasis pain"],
    indications: "Fixed or stabbing pain with dark complexion, purple tongue, stasis signs, or chronic obstruction.",
    ingredients: spleenIngredients.xueFuZhuYuTang,
  },
  liangFuWan: {
    chineseName: "良附丸",
    pinyin: "Liang Fu Wan",
    actions: ["Warms Stomach", "Moves Qi", "Stops pain"],
    indications: "Cold epigastric or abdominal pain relieved by warmth, worse with cold food/drink.",
    ingredients: spleenIngredients.liangFuWan,
  },
  zuoJinWan: {
    chineseName: "左金丸",
    pinyin: "Zuo Jin Wan",
    actions: ["Clears Liver/Stomach Heat", "Descends rebellious Qi", "Stops acid regurgitation"],
    indications: "Burning epigastric pain, acid reflux, bitter taste, irritability, red tongue, wiry rapid pulse.",
    ingredients: spleenIngredients.zuoJinWan,
  },
  qingZhongTang: {
    chineseName: "清中汤",
    pinyin: "Qing Zhong Tang",
    actions: ["Clears Stomach Heat", "Harmonizes middle burner", "Stops pain"],
    indications: "Burning epigastric pain, thirst, bad breath, constipation, red tongue with yellow coat.",
    ingredients: spleenIngredients.qingZhongTang,
  },
  shiXiaoSan: {
    chineseName: "失笑散",
    pinyin: "Shi Xiao San",
    actions: ["Moves Blood", "Dispels stasis", "Stops pain"],
    indications: "Fixed stabbing abdominal or epigastric pain, dark complexion, purple tongue or stasis spots.",
    ingredients: spleenIngredients.shiXiaoSan,
  },
  huangQiJianZhongTang: {
    chineseName: "黄芪建中汤",
    pinyin: "Huang Qi Jian Zhong Tang",
    actions: ["Warms and tonifies middle burner", "Relieves deficiency pain", "Supports Qi"],
    indications: "Dull pain relieved by pressure/warmth, fatigue, poor appetite, loose stool, pale tongue.",
    ingredients: spleenIngredients.huangQiJianZhongTang,
  },
  yiGuanJian: {
    chineseName: "一贯煎",
    pinyin: "Yi Guan Jian",
    actions: ["Nourishes Yin", "Soothe Liver", "Harmonizes Stomach"],
    indications: "Dull burning pain, dry mouth/throat, hunger without desire to eat, red dry tongue.",
    ingredients: spleenIngredients.yiGuanJian,
  },
  daChengQiTang: {
    chineseName: "大承气汤",
    pinyin: "Da Cheng Qi Tang",
    actions: ["Purges Heat accumulation", "Moves stool", "Drains excess"],
    indications: "Severe constipation with abdominal fullness/pain, fever or tidal fever, dry yellow coat.",
    ingredients: spleenIngredients.daChengQiTang,
  },
  maZiRenWan: {
    chineseName: "麻子仁丸",
    pinyin: "Ma Zi Ren Wan",
    actions: ["Moistens Intestines", "Drains Heat", "Unblocks stool"],
    indications: "Dry stool from Heat or fluid deficiency, mild abdominal fullness, dry mouth.",
    ingredients: spleenIngredients.maZiRenWan,
  },
  jiChuanJian: {
    chineseName: "济川煎",
    pinyin: "Ji Chuan Jian",
    actions: ["Warms Kidney", "Moistens Intestines", "Promotes bowel movement"],
    indications: "Constipation in elderly/deficiency patients with cold lower back, clear urine, pale tongue.",
    ingredients: spleenIngredients.jiChuanJian,
  },
  siJunZiTang: {
    chineseName: "四君子汤",
    pinyin: "Si Jun Zi Tang",
    actions: ["Tonifies Spleen Qi", "Strengthens transformation", "Supports middle burner"],
    indications: "Fatigue, poor appetite, loose stool, weak limbs, pale tongue, weak pulse.",
    ingredients: spleenIngredients.siJunZiTang,
  },
  liuJunZiTang: {
    chineseName: "六君子汤",
    pinyin: "Liu Jun Zi Tang",
    actions: ["Tonifies Spleen Qi", "Transforms Phlegm", "Harmonizes Stomach"],
    indications: "Spleen deficiency with nausea, phlegm, poor appetite, loose stool, greasy coat.",
    ingredients: spleenIngredients.liuJunZiTang,
  },
  shenLingBaiZhuSan: {
    chineseName: "参苓白术散",
    pinyin: "Shen Ling Bai Zhu San",
    actions: ["Tonifies Spleen", "Drains Dampness", "Stops diarrhea"],
    indications: "Chronic loose stool, poor appetite, fatigue, abdominal bloating, pale tongue.",
    ingredients: spleenIngredients.shenLingBaiZhuSan,
  },
  liZhongWan: {
    chineseName: "理中丸",
    pinyin: "Li Zhong Wan",
    actions: ["Warms middle burner", "Dispels Cold", "Stops vomiting/diarrhea"],
    indications: "Cold deficiency vomiting or diarrhea with cold abdomen, no thirst, pale tongue.",
    ingredients: spleenIngredients.liZhongWan,
  },
  siShenWan: {
    chineseName: "四神丸",
    pinyin: "Si Shen Wan",
    actions: ["Warms Kidney and Spleen", "Binds Intestines", "Stops dawn diarrhea"],
    indications: "Early morning diarrhea, cold abdomen, cold limbs, soreness of low back/knees.",
    ingredients: spleenIngredients.siShenWan,
  },
  geGenQinLianTang: {
    chineseName: "葛根芩连汤",
    pinyin: "Ge Gen Qin Lian Tang",
    actions: ["Clears Damp-Heat", "Releases exterior", "Stops diarrhea/dysentery"],
    indications: "Diarrhea or dysentery with burning anus, fever, thirst, foul stool, yellow greasy coat.",
    ingredients: spleenIngredients.geGenQinLianTang,
  },
  huoXiangZhengQiSan: {
    chineseName: "藿香正气散",
    pinyin: "Huo Xiang Zheng Qi San",
    actions: ["Transforms Dampness", "Releases exterior", "Harmonizes middle burner"],
    indications: "Nausea, vomiting, diarrhea, chest/epigastric oppression with exterior Damp or summer Damp.",
    ingredients: spleenIngredients.huoXiangZhengQiSan,
  },
  pingWeiSan: {
    chineseName: "平胃散",
    pinyin: "Ping Wei San",
    actions: ["Dries Dampness", "Moves Qi", "Harmonizes Stomach"],
    indications: "Epigastric fullness, poor appetite, nausea, heavy body, thick greasy coat.",
    ingredients: spleenIngredients.pingWeiSan,
  },
  xiaoYaoSan: {
    chineseName: "逍遥散",
    pinyin: "Xiao Yao San",
    actions: ["Soothe Liver", "Strengthens Spleen", "Harmonizes middle burner"],
    indications: "Digestive symptoms worse with stress, hypochondriac tension, fatigue, wiry pulse.",
    ingredients: spleenIngredients.xiaoYaoSan,
  },
  xuanFuDaiZheTang: {
    chineseName: "旋覆代赭汤",
    pinyin: "Xuan Fu Dai Zhe Tang",
    actions: ["Descends rebellious Stomach Qi", "Transforms Phlegm", "Tonifies deficiency"],
    indications: "Belching, hiccup, nausea or vomiting with epigastric hardness and weak Stomach Qi.",
    ingredients: spleenIngredients.xuanFuDaiZheTang,
  },
  wenDanTang: {
    chineseName: "温胆汤",
    pinyin: "Wen Dan Tang",
    actions: ["Clears Phlegm-Heat", "Harmonizes Stomach", "Descends rebellious Qi"],
    indications: "Nausea, epigastric oppression, bitter taste, dizziness, greasy yellow coat, slippery rapid pulse.",
    ingredients: spleenIngredients.wenDanTang,
  },
  dingXiangShiDiTang: {
    chineseName: "丁香柿蒂汤",
    pinyin: "Ding Xiang Shi Di Tang",
    actions: ["Warms Stomach", "Descends rebellious Qi", "Stops hiccup"],
    indications: "Cold hiccup or belching with cold epigastrium, clear fluids, pale tongue.",
    ingredients: spleenIngredients.dingXiangShiDiTang,
  },
  zhuYeShiGaoTang: {
    chineseName: "竹叶石膏汤",
    pinyin: "Zhu Ye Shi Gao Tang",
    actions: ["Clears Heat", "Benefits Qi and Yin", "Harmonizes Stomach"],
    indications: "Residual Heat injuring Qi/Yin with thirst, dry mouth, nausea, and red tongue.",
    ingredients: spleenIngredients.zhuYeShiGaoTang,
  },
  shaShenMaiDongTang: {
    chineseName: "沙参麦冬汤",
    pinyin: "Sha Shen Mai Dong Tang",
    actions: ["Nourishes Stomach/Lung Yin", "Generates fluids", "Clears mild Heat"],
    indications: "Dry mouth/throat, poor appetite, dry retching, red peeled tongue.",
    ingredients: spleenIngredients.shaShenMaiDongTang,
  },
  zengYeTang: {
    chineseName: "增液汤",
    pinyin: "Zeng Ye Tang",
    actions: ["Nourishes Yin", "Generates fluids", "Moistens Intestines"],
    indications: "Dry constipation or wasting-thirst with dry mouth, thirst, red dry tongue.",
    ingredients: spleenIngredients.zengYeTang,
  },
  baiTouWengTang: {
    chineseName: "白头翁汤",
    pinyin: "Bai Tou Weng Tang",
    actions: ["Clears Heat toxin", "Cools Blood", "Stops dysentery"],
    indications: "Dysentery with pus and blood, tenesmus, burning anus, fever, thirst.",
    ingredients: spleenIngredients.baiTouWengTang,
  },
  zhenRenYangZangTang: {
    chineseName: "真人养脏汤",
    pinyin: "Zhen Ren Yang Zang Tang",
    actions: ["Warms and tonifies Spleen/Kidney", "Binds Intestines", "Stops chronic dysentery"],
    indications: "Chronic dysentery or diarrhea with cold pain, fatigue, prolapse tendency, pale tongue.",
    ingredients: spleenIngredients.zhenRenYangZangTang,
  },
  qiGeSan: {
    chineseName: "启膈散",
    pinyin: "Qi Ge San",
    actions: ["Opens diaphragm", "Moves Qi", "Transforms Phlegm"],
    indications: "Dysphagia with obstruction sensation, phlegm, chest/diaphragm oppression.",
    ingredients: spleenIngredients.qiGeSan,
  },
  tongYouTang: {
    chineseName: "通幽汤",
    pinyin: "Tong You Tang",
    actions: ["Nourishes Blood", "Moves stasis", "Unblocks obstruction"],
    indications: "Dysphagia from dryness/stasis with difficult swallowing and dry stool.",
    ingredients: spleenIngredients.tongYouTang,
  },
} satisfies Record<string, FormulaDetail>;

export const spleenContent: Record<number, LungConditionDetail> = {
  1: {
    overview: "Abdominal Mass / Ji Ju covers palpable or subjective abdominal accumulations. Ju masses are more Qi-based and mobile; Ji masses are more Blood-based, fixed, and deeper.",
    redFlags: ["New, growing, hard, or fixed abdominal mass", "Unexplained weight loss", "Blood in stool or black stool", "Persistent vomiting or severe pain"],
    patterns: [
      { name: "Qi Mass: Liver Qi Stagnation", principle: "Soothe Liver, regulate Qi, soften mass.", points: "LR 3, LR 14, CV 12, CV 6, ST 25, SP 15.", formula: formulas.chaiHuShuGanSan },
      { name: "Qi Mass: Retention of Food and Phlegm", principle: "Reduce food stagnation, transform Phlegm, move Qi.", points: "CV 12, ST 25, ST 40, ST 36, SP 4, PC 6.", formula: formulas.baoHeWan },
      { name: "Blood Mass: Stagnation of Qi and Blood", principle: "Move Qi, invigorate Blood, soften mass.", points: "LR 3, SP 10, BL 17, CV 6, ST 25, SP 15.", formula: formulas.xueFuZhuYuTang },
      { name: "Blood Mass: Blood Stasis Knotted in the Interior", principle: "Break stasis, soften hardness, relieve pain.", points: "SP 10, BL 17, ST 25, CV 6, LR 3, SP 6.", formula: formulas.shiXiaoSan },
      { name: "Blood Mass: Deficiency of Upright Qi with Blood Stasis", principle: "Support upright Qi, move Blood, soften mass.", points: "ST 36, CV 6, SP 6, BL 20, BL 17, SP 10.", formula: formulas.huangQiJianZhongTang },
    ],
  },
  2: {
    overview: "Abdominal Pain (Fu Tong) is differentiated by Cold, Damp-Heat, food, Qi, Blood, or deficiency-Cold obstructing abdominal Qi dynamics.",
    redFlags: ["Severe sudden abdominal pain", "Rebound tenderness or rigid abdomen", "Fever with persistent vomiting", "Blood in stool", "Pregnancy with abdominal pain"],
    patterns: [
      { name: "Cold in the Intestines", principle: "Warm interior, scatter Cold, move Qi, stop pain.", points: "CV 12, CV 6, ST 25, ST 36, SP 6. Use moxa.", formula: formulas.liangFuWan },
      { name: "Damp-Heat in the Intestines", principle: "Clear Heat, transform Dampness, regulate intestines.", points: "ST 25, ST 37, LI 11, SP 9, CV 12.", formula: formulas.geGenQinLianTang },
      { name: "Food Retention", principle: "Reduce food stagnation, harmonize middle, stop pain.", points: "CV 12, ST 25, ST 36, SP 4, ST 40.", formula: formulas.baoHeWan },
      { name: "Qi Stagnation", principle: "Move Qi, soothe Liver, stop abdominal pain.", points: "LR 3, SP 4, PC 6, CV 12, ST 25, CV 6.", formula: formulas.chaiHuShuGanSan },
      { name: "Blood Stasis", principle: "Move Blood, transform stasis, unblock pain.", points: "SP 10, BL 17, ST 25, CV 6, LR 3.", formula: formulas.shiXiaoSan },
      { name: "Qi Deficiency with Empty-Cold in the Abdomen", principle: "Tonify Qi, warm middle, stop deficiency pain.", points: "CV 6, CV 12, ST 36, BL 20, SP 6. Use moxa.", formula: formulas.huangQiJianZhongTang },
    ],
  },
  7: {
    overview: "Constipation (Bian Bi) is difficult, infrequent, or dry stool due to Heat, Qi stagnation, Cold, or deficiency of Qi, Yang, Blood, or Yin.",
    redFlags: ["New constipation after age 50", "Blood in stool", "Unexplained weight loss", "Severe abdominal pain/vomiting", "No gas or stool with distention"],
    patterns: [
      { name: "Chronic Interior Heat", principle: "Clear Heat, moisten intestines, unblock stool.", points: "ST 25, ST 37, LI 11, TE 6, SP 15.", formula: formulas.maZiRenWan },
      { name: "Acute Heat in Febrile Disease", principle: "Purge Heat, move stool, drain accumulation.", points: "ST 25, ST 37, LI 11, ST 44, TE 6.", formula: formulas.daChengQiTang },
      { name: "Liver Qi Stagnation", principle: "Move Qi, soothe Liver, unblock bowels.", points: "LR 3, SP 4, TE 6, ST 25, CV 6.", formula: formulas.chaiHuShuGanSan },
      { name: "Cold", principle: "Warm interior, disperse Cold, unblock stool.", points: "CV 6, CV 12, ST 25, ST 36, KI 7. Use moxa.", formula: formulas.jiChuanJian },
      { name: "Qi Deficiency", principle: "Tonify Qi, support bowel movement.", points: "ST 36, CV 6, BL 20, SP 6, ST 25.", formula: formulas.siJunZiTang },
      { name: "Yang Deficiency", principle: "Warm Yang, tonify Kidney/Spleen, unblock stool.", points: "CV 4, CV 6, GV 4, BL 23, ST 25. Use moxa.", formula: formulas.jiChuanJian },
      { name: "Blood Deficiency", principle: "Nourish Blood, moisten intestines.", points: "SP 6, BL 17, ST 36, ST 25, HT 7.", formula: formulas.maZiRenWan },
      { name: "Yin Deficiency", principle: "Nourish Yin, generate fluids, moisten stool.", points: "KI 6, SP 6, ST 36, ST 25, CV 12.", formula: formulas.zengYeTang },
    ],
  },
  9: {
    overview: "Consumptive Thirst / Xiao Ke centers on excessive thirst, hunger, urination, and wasting due to Heat and Yin-fluid depletion in the Lung, Stomach, and Kidney.",
    redFlags: ["Very high blood sugar symptoms", "Unexplained weight loss", "Excessive urination with dehydration", "Confusion, vomiting, fruity breath"],
    patterns: [
      { name: "Upper Xiao: Lung Heat Damaging Fluids", principle: "Clear Lung Heat, generate fluids, stop thirst.", points: "LU 5, LU 10, CV 12, ST 36, SP 6, KI 6.", formula: formulas.zhuYeShiGaoTang },
      { name: "Middle Xiao: Excessive Stomach Heat", principle: "Clear Stomach Heat, nourish fluids, reduce hunger/thirst.", points: "ST 44, ST 36, CV 12, SP 6, LI 11.", formula: formulas.qingZhongTang },
      { name: "Lower Xiao: Kidney Yin Deficiency", principle: "Nourish Kidney Yin, generate fluids, secure essence.", points: "KI 3, KI 6, SP 6, CV 4, BL 23.", formula: formulas.zengYeTang },
    ],
  },
  13: {
    overview: "Diarrhea (Xie Xie) is frequent loose stool from Dampness, food retention, Liver overacting, Spleen deficiency, or Kidney Yang deficiency.",
    redFlags: ["Blood or black stool", "High fever", "Severe dehydration", "Persistent diarrhea over several days", "Recent travel or antibiotic use with severe symptoms"],
    patterns: [
      { name: "Cold-Damp Retention", principle: "Warm middle, transform Cold-Damp, stop diarrhea.", points: "CV 12, ST 25, ST 36, SP 9, SP 6. Use moxa.", formula: formulas.huoXiangZhengQiSan },
      { name: "Damp-Heat Retention", principle: "Clear Damp-Heat, regulate intestines, stop diarrhea.", points: "ST 25, ST 37, LI 11, SP 9, CV 12.", formula: formulas.geGenQinLianTang },
      { name: "Food Retention", principle: "Reduce food stagnation, harmonize intestines.", points: "CV 12, ST 25, ST 36, SP 4, ST 40.", formula: formulas.baoHeWan },
      { name: "Liver Qi Stagnation", principle: "Soothe Liver, strengthen Spleen, stop diarrhea.", points: "LR 3, SP 4, PC 6, ST 25, ST 36.", formula: formulas.xiaoYaoSan },
      { name: "Spleen-Stomach Deficiency", principle: "Tonify Spleen/Stomach Qi, transform Dampness.", points: "ST 36, CV 12, BL 20, SP 6, ST 25.", formula: formulas.shenLingBaiZhuSan },
      { name: "Kidney Yang Deficiency", principle: "Warm Kidney Yang, strengthen Spleen, stop dawn diarrhea.", points: "CV 4, GV 4, BL 23, ST 36, SP 6. Use moxa.", formula: formulas.siShenWan },
    ],
  },
  14: {
    overview: "Drum Distension (Gu Zhang) is abdominal distention with fluid, Qi, Blood, Dampness, or deficiency, clinically overlapping with ascites-type presentations.",
    redFlags: ["New abdominal swelling", "Jaundice", "Shortness of breath", "Fever with abdominal pain", "Vomiting blood or black stool"],
    patterns: [
      { name: "Qi Stagnation with Damp Obstruction", principle: "Move Qi, transform Dampness, reduce distention.", points: "LR 3, SP 9, CV 9, CV 12, ST 25, SP 6.", formula: formulas.chaiHuShuGanSan },
      { name: "Cold-Damp Blocking Spleen", principle: "Warm Spleen, transform Cold-Damp, move water.", points: "CV 9, CV 12, ST 36, SP 9, BL 20. Use moxa.", formula: formulas.pingWeiSan },
      { name: "Damp-Heat Accumulation", principle: "Clear Damp-Heat, move water, reduce distention.", points: "SP 9, CV 9, ST 25, LI 11, ST 36.", formula: formulas.geGenQinLianTang },
      { name: "Spleen Qi Stagnation with Liver Blood Stasis", principle: "Tonify Spleen, move Liver Qi and Blood.", points: "ST 36, SP 6, LR 3, SP 10, BL 17, CV 6.", formula: formulas.xueFuZhuYuTang },
      { name: "Spleen-Kidney Yang Deficiency", principle: "Warm Spleen/Kidney Yang, move water.", points: "CV 4, CV 6, GV 4, BL 20, BL 23, SP 9. Use moxa.", formula: formulas.liZhongWan },
      { name: "Liver-Kidney Yin Deficiency", principle: "Nourish Liver/Kidney Yin, soften Liver, move water gently.", points: "KI 3, SP 6, BL 18, BL 23, CV 4, SP 9.", formula: formulas.yiGuanJian },
    ],
  },
  15: {
    overview: "Dysentery (Li Ji) presents with abdominal pain, tenesmus, and stool containing mucus, pus, or blood.",
    redFlags: ["Blood in stool with fever", "Severe dehydration", "Persistent abdominal pain", "Recent travel outbreak symptoms", "Immunocompromised patient"],
    patterns: [
      { name: "Damp-Heat Dysentery", principle: "Clear Damp-Heat, cool Blood, stop dysentery.", points: "ST 25, ST 37, LI 11, SP 9, SP 6.", formula: formulas.geGenQinLianTang },
      { name: "Epidemic Toxic Dysentery", principle: "Clear Heat toxin, cool Blood, open obstruction.", points: "LI 11, ST 25, ST 37, GV 14, SP 10.", formula: formulas.baiTouWengTang },
      { name: "Cold-Damp Dysentery", principle: "Warm middle, transform Cold-Damp, stop dysentery.", points: "CV 12, ST 25, ST 36, SP 9, BL 20. Use moxa.", formula: formulas.huoXiangZhengQiSan },
      { name: "Yin Deficiency Dysentery", principle: "Nourish Yin, clear empty Heat, stop dysentery.", points: "KI 3, SP 6, ST 36, ST 25, BL 23.", formula: formulas.shaShenMaiDongTang },
      { name: "Deficient Cold Dysentery", principle: "Warm and tonify Spleen/Kidney, bind intestines.", points: "CV 6, CV 12, ST 36, BL 20, BL 23. Use moxa.", formula: formulas.zhenRenYangZangTang },
      { name: "Intermittent Dysentery", principle: "Tonify Spleen, regulate intestines, clear lingering pathogen.", points: "ST 36, CV 12, ST 25, SP 6, SP 9.", formula: formulas.shenLingBaiZhuSan },
      { name: "Food-Resistant Dysentery", principle: "Reduce food stagnation, harmonize intestines.", points: "CV 12, ST 25, ST 37, SP 4, ST 40.", formula: formulas.baoHeWan },
    ],
  },
  16: {
    overview: "Dysphagia Occlusion Syndrome (Ye Ge) is difficulty swallowing with obstruction, often involving Qi, Phlegm, Heat, Yin depletion, Blood stasis, or Yang/Qi collapse.",
    redFlags: ["Progressive difficulty swallowing", "Unexplained weight loss", "Vomiting blood", "Choking/aspiration", "New dysphagia in older adults"],
    patterns: [
      { name: "Congestion of Qi and Phlegm", principle: "Move Qi, transform Phlegm, open diaphragm.", points: "CV 17, CV 22, PC 6, ST 40, CV 12, LR 3.", formula: formulas.qiGeSan },
      { name: "Depletion of Fluids with Accumulation of Heat", principle: "Nourish Yin, clear Heat, moisten throat/Stomach.", points: "KI 6, SP 6, CV 12, ST 36, LU 10.", formula: formulas.shaShenMaiDongTang },
      { name: "Accumulation of Blood Stasis", principle: "Move Blood, transform stasis, unblock diaphragm.", points: "BL 17, SP 10, PC 6, CV 17, LR 3.", formula: formulas.tongYouTang },
      { name: "Deficiency of Qi with Devitalization of Yang", principle: "Tonify Qi, warm Yang, support swallowing.", points: "CV 6, CV 12, ST 36, BL 20, GV 4. Use moxa.", formula: formulas.huangQiJianZhongTang },
    ],
  },
  19: {
    overview: "Epigastric Pain (Wei Tong) involves Stomach Qi obstruction or malnourishment from Cold, food, Liver overacting, Heat, Phlegm, Dampness, Blood stasis, or deficiency.",
    redFlags: ["Severe or sudden epigastric pain", "Black stool or vomiting blood", "Unexplained weight loss", "Persistent vomiting", "Chest pain mimicking epigastric pain"],
    patterns: [
      { name: "Cold Invading Stomach", principle: "Warm Stomach, scatter Cold, stop pain.", points: "CV 12, ST 36, ST 34, PC 6. Use moxa.", formula: formulas.liangFuWan },
      { name: "Food Retention", principle: "Reduce food stagnation, harmonize Stomach.", points: "CV 12, ST 21, ST 36, SP 4, ST 40.", formula: formulas.baoHeWan },
      { name: "Liver Qi Invading Stomach", principle: "Soothe Liver, harmonize Stomach, stop pain.", points: "LR 3, PC 6, CV 12, ST 21, SP 4.", formula: formulas.chaiHuShuGanSan },
      { name: "Stomach Fire", principle: "Clear Stomach Heat, harmonize middle.", points: "ST 44, LI 11, CV 12, ST 36, PC 6.", formula: formulas.qingZhongTang },
      { name: "Stomach Phlegm-Fire", principle: "Clear Phlegm-Fire, harmonize Stomach.", points: "ST 40, ST 44, CV 12, PC 6, LI 11.", formula: formulas.wenDanTang },
      { name: "Stomach Damp-Heat", principle: "Clear Damp-Heat, harmonize Stomach.", points: "SP 9, ST 36, CV 12, ST 25, LI 11.", formula: formulas.pingWeiSan },
      { name: "Stomach and Liver Heat", principle: "Clear Liver/Stomach Heat, descend rebellious Qi.", points: "LR 2, ST 44, CV 12, PC 6, LR 3.", formula: formulas.zuoJinWan },
      { name: "Blood Stasis in Stomach", principle: "Move Blood, transform stasis, stop fixed pain.", points: "BL 17, SP 10, CV 12, ST 34, PC 6.", formula: formulas.shiXiaoSan },
      { name: "Phlegm-Fluids in Stomach", principle: "Transform Phlegm-fluid, harmonize Stomach, descend Qi.", points: "ST 40, CV 12, CV 9, PC 6, ST 36.", formula: formulas.liuJunZiTang },
      { name: "Stomach-Spleen Deficient Cold", principle: "Warm and tonify middle burner, stop pain.", points: "CV 12, CV 6, ST 36, BL 20, SP 6. Use moxa.", formula: formulas.huangQiJianZhongTang },
      { name: "Stomach Yin Deficiency", principle: "Nourish Stomach Yin, harmonize middle.", points: "KI 6, SP 6, ST 36, CV 12, ST 44.", formula: formulas.yiGuanJian },
    ],
  },
  24: {
    overview: "Hiccoughing and Belching (E Ni) are rebellious Stomach Qi rising upward due to Cold, Heat, food, Liver Qi, Yang deficiency, or Yin deficiency.",
    patterns: [
      { name: "Stomach Cold", principle: "Warm Stomach, descend rebellious Qi, stop hiccup.", points: "CV 12, CV 13, ST 36, PC 6. Use moxa.", formula: formulas.dingXiangShiDiTang },
      { name: "Effulgent Stomach Fire", principle: "Clear Stomach Fire, descend Qi.", points: "ST 44, CV 12, PC 6, LI 11.", formula: formulas.zhuYeShiGaoTang },
      { name: "Liver Qi Stagnation", principle: "Soothe Liver, harmonize Stomach, descend Qi.", points: "LR 3, PC 6, CV 17, CV 12, ST 36.", formula: formulas.chaiHuShuGanSan },
      { name: "Spleen-Stomach Yang Deficiency", principle: "Warm and tonify Spleen/Stomach, descend Qi.", points: "CV 12, CV 6, ST 36, BL 20. Use moxa.", formula: formulas.liZhongWan },
      { name: "Stomach Yin Deficiency", principle: "Nourish Stomach Yin, descend Qi.", points: "KI 6, SP 6, CV 12, ST 36, PC 6.", formula: formulas.shaShenMaiDongTang },
      { name: "Food Retention", principle: "Reduce food stagnation, harmonize Stomach, descend Qi.", points: "CV 12, ST 21, ST 36, SP 4, PC 6.", formula: formulas.baoHeWan },
    ],
  },
  44: {
    overview: "Vomiting (Ou Tu) is rebellious Stomach Qi with failure of descending, caused by exterior invasion, food, Phlegm-Damp, Liver overacting, deficiency Cold, or Stomach Yin deficiency.",
    redFlags: ["Persistent vomiting with dehydration", "Vomiting blood", "Severe abdominal pain", "Neurologic symptoms", "Pregnancy with severe vomiting"],
    patterns: [
      { name: "Exogenous Evils Invading Stomach", principle: "Release exterior, harmonize Stomach, stop vomiting.", points: "PC 6, CV 12, ST 36, LI 4, TE 5.", formula: formulas.huoXiangZhengQiSan },
      { name: "Food Retention", principle: "Reduce food stagnation, descend Stomach Qi.", points: "CV 12, ST 21, ST 36, SP 4, PC 6.", formula: formulas.baoHeWan },
      { name: "Phlegm-Damp Retention", principle: "Transform Phlegm-Damp, harmonize Stomach, stop vomiting.", points: "ST 40, CV 12, PC 6, ST 36, SP 9.", formula: formulas.liuJunZiTang },
      { name: "Liver Qi Invading Stomach", principle: "Soothe Liver, harmonize Stomach, descend Qi.", points: "LR 3, PC 6, CV 12, CV 17, ST 36.", formula: formulas.xiaoYaoSan },
      { name: "Spleen-Stomach Deficiency Cold", principle: "Warm middle, tonify Spleen/Stomach, stop vomiting.", points: "CV 12, CV 6, ST 36, BL 20. Use moxa.", formula: formulas.liZhongWan },
      { name: "Stomach Yin Deficiency", principle: "Nourish Stomach Yin, descend rebellious Qi.", points: "KI 6, SP 6, CV 12, ST 36, PC 6.", formula: formulas.shaShenMaiDongTang },
    ],
  },
};
